<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Accendo</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/layout.css" />
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery.js"></script>
   <base target="mainFrame"/>
    </head>

    <body>
        <div id="navbar">
            <p>Your Location: <a href="javascript:void(0)"title="">First Page</a></p>
        </div>
        <div class="table-div">
            <table >
                <caption></caption>
                <thead>
                    <tr>
                        <th>Function list</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>1: modify its password</th>

                    </tr>
                    <tr>
                        <th>2: update its information</th>

                    </tr>
                    <tr>
                        <th>3: create biller</th>

                    </tr>
                    <tr>
                        <th>4: manage biller</th>

                    </tr>
                </tbody>
            </table>

        </div>
    </body>
</html>