<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>admin-Accendo</title>
	<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/layout.css" />
	<!-- <script language="JavaScript" type="text/javascript">
		top.location.href='<{$baseUrl}>/admin/auth/login';
	</script> -->
            <base target="mainFrame"/>
</head>

<body>

<div id="top">
    <div id="logo"><h1><span><i>Accendo</i></span></h1></div>
    <div id="toplink"><p>Welcome&nbsp;&nbsp;<b><?php echo $this->user_name?></b>&nbsp;&nbsp;billingcompany.
                <a href="<{$baseUrl}>/admin/auth/logout" title="logout">logout</a></p></div>


</div>
</body>
</html>