<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

        <title>biller-Accendo</title>
<!--        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/layout.css" />-->
        <style type="text/css">
            #error {
                width: 80%;
                padding: 5px;
                border: 3px solid #f60;
                text-align: center;

            }
        </style>
    </head>


    <frameset rows="64,*" cols="*" frameborder="NO"  border="0" framespacing="0">
        <frame src="<?php echo $this->baseUrl ?>/biller/index/top/" name="topFrame" scrolling="NO" noresize />
        <frameset  rows="*" cols="180,*" framespacing="0" frameborder="no" border="0">
            <frame src="<?php echo $this->baseUrl ?>/biller/index/menu/" name="leftFrame" scrolling="YES" noresize/>
            <frame src="<?php echo $this->baseUrl ?>/biller/claims/inquiry/" scrolling="YES"  noresize name="mainFrame"/>
        </frameset>
    </frameset>

    <noframes><body>
            <div id="error">Your Explorer Does Not Support Frame!</div>
        </body></noframes>
</html>