<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title> Accendo</title>
	<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/layout.css" />
	<link rel="stylesheet" rev="stylesheet" type="text/css" media="screen, projection" href="<?php echo $this->baseUrl ?>/styles/pagenav.css" />
</head>

<body>
<div id="navbar">
    <p>Your location: <a href="main.html" title="">First Page</a> &gt; change password</p>
</div>
<div class="table-div">
    <form method="post" action="product-search-view.html">
    <table>
	<thead>
	  <tr>
	    <th class="title" colspan="2">change password</th>
	  </tr>
	</thead>
	<tbody>
	  <tr>
	    <th style="width:15%;">old password</th>
		<td><input type="password" name="old_pwd" /></td>
	  </tr>
	  <tr>
	    <th>new password</th>
		<td><input type="password" name="new_pwd" /></td>
	  </tr>
	  <tr>
	    <th>new password(confirm)</th>
		<td><input type="password" name="new_pwd_confirm" /></td>
	  </tr>
	  <tr>
	    <th colspan="2"><input type="submit" value="submit" class="cmd" /></th>
	  </tr>
	  </tbody>
	</table>
    </form>

</div>
</body>
</html>