<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>Accendo</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/colorselector/lib/bootstrap-colorselector-0.2.0/css/bootstrap-colorselector.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/layout.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/datepicker.css" />
        <link rel="stylesheet" rev="stylesheet" type="text/css" media="screen, projection" href="<?php echo $this->baseUrl ?>/styles/pagenav.css" />
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery.js"></script>
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/datepicker.js"></script>
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery-1.3.2.js"></script>
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jshelper.js"></script>


        <script type="text/javascript" language="javascript">
            $(document).ready(function ()
            {
                $.post("<?php echo $this->baseUrl ?>/biller/claims/timeout/",
                        function (data)
                        {
                            if (data != 'no' && data != null) {
                                var a = document.getElementById("relogin");
                                a.click();
                            }
                        }
                );
                $("#time_out").val("60");

                $("#claim_doc_types").change(function () {
                    var claim_doc_types = $("#claim_doc_types").val();
                    $("#claim_doc_types_array").val(claim_doc_types);
                });

                $("#claim_doc_sources").change(function () {
                    var claim_doc_sources = $("#claim_doc_sources").val();
                    $("#claim_doc_sources_array").val(claim_doc_sources);
                });
                $.post("<?php echo $this->baseUrl ?>/biller/data/billingcompanyinput/", function (data) {
                    var myjson = '';
                    eval("myjson=" + data + ";");
                    if (myjson.billingcompany_name != null)
                        $("#billingcompany_name").val(myjson.billingcompany_name);
                    if (myjson.default_provider != null)
                        $("#default_provider").val(myjson.default_provider);
                    if (myjson.street_address != null)
                        $("#street_address").val(myjson.street_address);
                    if (myjson.zip != null)
                        $("#zip").val(myjson.zip);
                    if (myjson.state != null)
                        $("#state").val(myjson.state);
                    if (myjson.city != null)
                        $("#city").val(myjson.city);
                    if (myjson.phone_number != null)
                        $("#phone_number").val(myjson.phone_number);
                    if (myjson.fax_number != null)
                        $("#fax_number").val(myjson.fax_number);
                    if (myjson.notes != null)
                        $("#notes").val(myjson.notes);
                    if (myjson.time_out != null)
                        $("#time_out").val(myjson.time_out);
                    if (myjson.patient_doc_types != null)
                        $("#patient_doc_types").val(myjson.patient_doc_types);
                    if (myjson.claim_doc_types != null)
                        $("#claim_doc_types").val(myjson.claim_doc_types);
                    if (myjson.patient_doc_sources != null)
                        $("#patient_doc_sources").val(myjson.patient_doc_sources);
                    if (myjson.claim_doc_sources != null)
                        $("#claim_doc_sources").val(myjson.claim_doc_sources);
                    if (myjson.appeal1 != null)
                        $("#appeal1").val(myjson.appeal1);
                    if (myjson.appeal2 != null)
                        $("#appeal2").val(myjson.appeal2);
                    if (myjson.appeal3 != null)
                        $("#appeal3").val(myjson.appeal3);
                    if (myjson.paymentfrom != null)
                        $("#paymentfrom").val(myjson.paymentfrom);
                    if (myjson.salutations != null)
                        $("#salutations").val(myjson.salutations);

                    if (myjson.tags_str != null) {
                        $("#tags").val(myjson.tags_str);
                    }
                    if (myjson.tags != null) {
                        var tags = myjson.tags;
                       
                        for (var key in tags) {
                           if(key.length==0){
                               break;
                           }
                            if (key == "FFFFFF") {
                                continue;
                            }

                            var spanObj = document.createElement('span');
                            spanObj.style.backgroundColor = "#" + key;
                            spanObj.className = "btn-colorselector";
                            document.getElementById('cAt').appendChild(spanObj);

                            var inputObj = document.createElement('input');
                            inputObj.onblur = up_tags;
                            inputObj.value = tags[key];
                            document.getElementById('cAt').appendChild(inputObj);

                            var brObj = document.createElement('br');
                            document.getElementById('cAt').appendChild(brObj);
                        }
                    }

                    //   alert(myjson.document_feature);
                    $("#document_feature").val(myjson.document_feature);
                    $("#insurancetags").val(myjson.insurancetags);
                    $("#providertags").val(myjson.providertags);
                    $("#renderingprovidertags").val(myjson.renderingprovidertags);
                    $("#optionstags").val(myjson.optionstags);

                });
            });
        </script>
        <script type="text/javascript" language="javascript">
            var if_is_equal = "0";
            function check_tags_input(position){
                var pos = "#" + position;
                var value = $(pos).val();
                var change_mark = 0;
                $(pos).focus();
//                =othe
//                =binar
                var last_char = value.substr(value.length - 2, value.length);
                var second_last_char = value.substr(value.length - 2, 1);
                if(value.substr(value.length -1, value.length) == "|"){
                    if_is_equal = "0";
                }else if(value.substr(value.length -1, value.length) == "="){
                    if_is_equal = "1";
                }
//                alert(value.substr(value.length - 5, value.length));
//                alert(second_last_char);
                if(last_char == "=b"){
                    change_mark = 1;            
                    var newValue = value + "inary";        
                    $(pos).val(newValue);
                }else if(last_char == "=o"){
                    change_mark = 1;                    
                    var newValue = value + "ther";      
                    $(pos).val(newValue);
                }else if(second_last_char == "="){
                    change_mark = 1;            
                    var newValue = value.substr(0, value.length - 1);       
                    $(pos).val(newValue);                    
                }else if(value.substr(value.length - 5, value.length) == "=othe"){
                    change_mark = 1;            
                    var newValue = value.substr(0,value.length - 4);        
                    $(pos).val(newValue);                    
                }else if(value.substr(value.length - 6, value.length) == "=binar"){
                    change_mark = 1;            
                    var newValue = value.substr(0,value.length - 5);          
                    $(pos).val(newValue);                    
                }else if(value.substr(value.length - 3, value.length) == "=ot"){
                    change_mark = 1;            
                    var newValue = value + "her";           
                    $(pos).val(newValue);                    
                }else if(value.substr(value.length - 4, value.length) == "=oth"){
                    change_mark = 1;            
                    var newValue = value + "er";             
                    $(pos).val(newValue);                    
                }else if(value.substr(value.length - 5, value.length) == "=othe"){
                    change_mark = 1;            
                    var newValue = value + "r";             
                    $(pos).val(newValue);                    
                }else if(value.substr(value.length - 3, value.length) == "=bi"){
                    change_mark = 1;            
                    var newValue = value + "nary";            
                    $(pos).val(newValue);                    
                }else if(value.substr(value.length - 4, value.length) == "=bin"){
                    change_mark = 1;            
                    var newValue = value + "ary";             
                    $(pos).val(newValue);                    
                }else if(value.substr(value.length - 5, value.length) == "=bina"){
                    change_mark = 1;            
                    var newValue = value + "ry";                  
                    $(pos).val(newValue);                    
                }else if(value.substr(value.length - 6, value.length) == "=binar"){
                    change_mark = 1;            
                    var newValue = value + "y";
                    $(pos).val(newValue);                    
                }
                if(value.indexOf("=") > 0){
                var tags_array = new Array();
                tags_array = value.split("=");
                if(if_is_equal == "1" && change_mark == "0" && (tags_array[tags_array.length - 1] != "other") && (tags_array[tags_array.length - 1] != "binary") 
                        && value.substr(value.length - 1, value.length) != "|" ){
                    var newValue = value.substr(0,value.length - tags_array[tags_array.length - 1].length);
                $(pos).val(newValue);      
                }
            }
            $(pos).focus();
//            document.getElementById(position).style.textAlign = "right";
//            $(pos).css("style", "text-align:right");
//            document.getElementById("test").style.textAlign = "right";
//            style="text-align:right "
            }
        </script>
        
        <script type="text/javascript" language="javascript" >
            //rgb to hex
            var reg = /^#([0-9a-fA-f]{3}|[0-9a-fA-f]{6})$/;
            function colorHex(str) {
                var that = str;
                if (/^(rgb|RGB)/.test(that)) {
                    var aColor = that.replace(/(?:\(|\)|rgb|RGB)*/g, "").split(",");
                    var strHex = "#";
                    //var strHex = "";
                    for (var i = 0; i < aColor.length; i++) {
                        var hex = Number(aColor[i]).toString(16);
                        if (hex === "0") {
                            hex += hex;
                        }
                        strHex += hex;
                    }
                    if (strHex.length !== 7) {
                        strHex = that;
                    }
                    //return strHex;
                    return strHex.substring(1);
                } else if (reg.test(that)) {
                    var aNum = that.replace(/#/, "").split("");
                    if (aNum.length === 6) {
                        return that;
                    } else if (aNum.length === 3) {
                        var numHex = "#";
                        for (var i = 0; i < aNum.length; i += 1) {
                            numHex += (aNum[i] + aNum[i]);
                        }
                        //return numHex;
                        return numHex.substring(1);
                    }
                } else {
                    return that;
                }
            }

            /*
             * change the value of input text
             */
            function up_tags() {

                oTbl = $("#cAt");
                aInput = oTbl.find("input");
                aSpan = oTbl.find("span");

                my_tags = "";
                //alert(aInput.length);
                for (i = 0; i < aInput.length; i++) {
                    rgb_color = aSpan[i].style.backgroundColor;
                    color = colorHex(rgb_color);
                    my_tags += (color + '=' + aInput[i].value + '|');
                }

                my_tags = my_tags.substring(0, my_tags.length - 1);
                document.getElementById("tags").value = ('FFFFFF=not color coded|' + my_tags);

            }
            function auto_complete() {
                var billingcompany_id = $("#billingcompany_id").val();
                $.post("<?php echo $this->baseUrl ?>/biller/data/billingcompanyinput/", {billingcompany_id: billingcompany_id}, function (data) {
                    var myjson = '';
                    eval("myjson=" + data + ";");
                    if (myjson.billingcompany_name != null)
                        $("#billingcompany_name").val(myjson.billingcompany_name);
                    if (myjson.default_provider != null)
                        $("#default_provider").val(myjson.default_provider);
                    if (myjson.street_address != null)
                        $("#street_address").val(myjson.street_address);
                    if (myjson.zip != null)
                        $("#zip").val(myjson.zip);
                    if (myjson.state != null)
                        $("#state").val(myjson.state);
                    if (myjson.city != null)
                        $("#city").val(myjson.city);
                    if (myjson.phone_number != null)
                        $("#phone_number").val(myjson.phone_number);
                    if (myjson.fax_number != null)
                        $("#fax_number").val(myjson.fax_number);
                    if (myjson.notes != null)
                        $("#notes").val(myjson.notes);
                    if (myjson.time_out != null)
                        $("#time_out").val(myjson.time_out);
                    if (myjson.appeal1 != null)
                        $("#appeal1").val(myjson.appeal1);
                    if (myjson.appeal2 != null)
                        $("#appeal2").val(myjson.appeal2);
                    if (myjson.appeal3 != null)
                        $("#appeal3").val(myjson.appeal3);
                    if (myjson.paymentfrom != null)
                        $("#paymentfrom").val(myjson.paymentfrom);
                    if (myjson.salutations != null)
                        $("#salutations").val(myjson.salutations);

                });
            }
        </script>
        <script type="text/javascript" language="javascript">
            function displaycheck(name) {
                var value = $(name).val();

                for (var index = 0; index < value.length; index++) {
                    var cur = value.charAt(index);
                    if ((cur <= '9' && cur >= '0') || cur == ' ' || (cur <= 'z' && cur >= 'a') || (cur <= 'Z' && cur >= 'A') || cur == '-' || cur == '_' || cur == '|') {
                    }
                    else {
                        value = value.substr(0, index) + value.substr(index + 1, value.length - index - 1);
                        $(name).val(value);
                        var tempname = name.substr(1, name.length - 1);
                        //alert(tempname);
                        setCaretPosition(document.getElementById(tempname), index);


                    }
                }
            }
            function setCaretPosition(ctrl, pos) {//设置光标位置函数
                if (ctrl.setSelectionRange)
                {
                    ctrl.focus();
                    ctrl.setSelectionRange(pos, pos);
                }
                else if (ctrl.createTextRange) {
                    var range = ctrl.createTextRange();
                    range.collapse(true);
                    range.moveEnd('character', pos);
                    range.moveStart('character', pos);
                    range.select();
                }
            }
            
            function getMergeField(){
//                    var uploadfilepath = document.getElementById("uploadedfil").value;
//                    alert(uploadfilepath);
                    //获取滚动条位置
//                    var scroll_pos = document.body.scrollTop;
                    var scroll_pos = window.scrollY;
                    $("#scroll_pos").val(scroll_pos);
                    $("#uploadfilepath").val(uploadfilepath);
//                    alert("test");
                    $("#getmergelist").click();
//                   alert("test");
//                    fillMergeField();
            }
            
            function change_patientcor_file(){
//                        uploadedfil_patientcor
//                    $("#changefile")                    $("#tags_input").css("display", "none");
//                    $("#tags_checkbox").css("display", "");
                    $("#changefile").css("display", "none");
                    $("#show_file_path").css("display", "none");
                    $("#uploadedfil_patientcor").css("display", "");
            }
            
            function showoptionfield(){
//              showoptionfield    setvalue show_merge_inputmerge_field
                 var select_type = $("#merge_field").val();
                 var temp_value = $("#" + select_type).val();
                 if(select_type == "select_option"){
                     $("#merge_public_input").css("display","none");
                 }else{
                    $("#merge_public_input").css("display","");
                    $("#merge_public_input").val(temp_value);
                 }
            }
            function setValue(){
                var select_position = $("#merge_field").val();
                var temp_value = $("#merge_public_input").val();
                $("#" + select_position).val(temp_value);
            }
            function showoptionfieldExisting(showField){
//                alert();
                var select_type = $("#merge_field_"+showField).val();
                var temp_value = $("#" + select_type + "_" + showField + "_existing").val();
                if(select_type == "select_option"){
                    $("#merge_public_input_"+showField).css("display","none");
                }else{
                    $("#merge_public_input_"+showField).css("display","");
                    $("#merge_public_input_"+showField).val(temp_value);
                }

            }
//            onDeletePatientCorrespondence  patientcorrespondence_doc_" . $i .
        
            function onDeletePatientCorrespondence(url, num, name){
                var r = confirm("The selected document will be permenantly deleted from Accendo, please confirm");
                var sele = "#patientcorrespondence_doc_" + num;
                if (r == true)
                {
                    $.post("<?php echo $this->baseUrl ?>/biller/data/deletebillingdocs/", {url: url, type: "billingcompany",subtype:"patientcorrespondence",deletefilename:name},
                    function (data) {
                        var answer = '';
                        eval("answer=" + data + ";");
                        if (answer.result == "true") {
                            $(sele).remove();
                        } else
                        {
                            alert("Unalbe to delete");
                        }
                    });
                }
                else
                {
                }
            }
//            javascript:update('".$rows['url']."'". "," . $i . ",'".$rows['patientcorrespondence_name']."')\"updatePatientCorrespondence
            function updatePatientCorrespondence(url,num,name){
                var new_name = $("#patientcorrespondence_name_"+name).val();
                var len = new_name.length;
//                alert(name);
//                alert(new_name);
//                        \"patientcorrespondence_name_".$rows['patientcorrespondence_name']."\"
//if(len == 0)
//                    {
//                            $("#"+location).css("border","4px solid red");
//                            $("#"+location).focus();
//                    }else{
//                            $("#"+location).css("border"," 1px solid #aaa");
//                    }
                if(len == 0){
                        $("#patientcorrespondence_name_"+name).css("border","4px solid red");
                        $("#patientcorrespondence_name_"+name).focus();
                }else{
                        $("#patientcorrespondence_name_"+name).css("border"," 1px solid #aaa");
                        var optionList = document.getElementById("merge_field_"+name).options;
        //                var mergefield;
                        var soilder = 0;
                        var merge_list = new Array();
        //                var full_merge_select = new Array();
                        for(var mark = 1; mark < optionList.length; mark ++){
                            var temp = optionList[mark].value;
                            var position = "#"+temp+ "_" + name + "_existing";
                            var tempData = $(position).val();
                            if((tempData!= null) && (tempData != "")){
                                merge_list[soilder] = temp + "=" + tempData;
        //                        alert(merge_list[soilder]);
                            }
        //                    if((tempData != null) && (tempData != "")){
        ////                            mergefield[soilder] = temp+"="+tempData;
        //                            alert(mergefield[temp+"="+tempData]);
        //                    }
                            soilder ++;
                        }
                        var merge_field_list = "";
                        for(var mark = 0; mark < merge_list.length; mark ++){
        //                    alert(merge_list[mark]);
                            if((mark != (merge_list.length - 1)) &&(merge_list[mark])){
                                merge_field_list += merge_list[mark] + "|";
                            }else if(merge_list[mark]){
                                merge_field_list += merge_list[mark];
                            }
                        }
                        $.post("<?php  echo $this->baseUrl ?>/biller/data/patientcorrespondenceupdate/",{url: url, oldname:name, newname:new_name, variables:merge_field_list}, 
                        function (data) {
                            var answer = '';
                            eval("answer=" + data + ";");
                            if(answer.result == "success"){
                                optionList[0].selected = true;
                                $("#merge_public_input_"+name).css("display","none");
        //                        alert("Successfully Updated");
        //                            window.location.reload();
                                    window.location.reload();
                            }
                            if(answer.result == "nameexisting"){
                                alert("Name for Template File Existing");
                                optionList[0].selected = true;
                                $("#merge_public_input_"+name).css("display","none");
                                $("#patientcorrespondence_name_"+name).val(answer.templatename);
        //                            templatename
        //                            
        //                            window.location.reload();
        //                            window.location.reload();
                            }
                        });
            }
                
            }
            
//            
            function setValueExisting(name){
                var position = $("#merge_field_"+name).val() + "_" + name + "_existing";
                var temp_value = $("#merge_public_input_"+name).val();
                $("#"+position).val(temp_value);
            }
            
            function valuecheckandchange(location){
                var name = $("#" + location).val();
//                alert(test);
//                var charat=phone_number.charAt(length-1) ;
//                    if(charat<'0'||charat>'9'){
//                        phone_number=phone_number.substr(0,length-1);
//                        $(name).val(phone_number);
//                    }
//                    //alert(charat);
                var length = name.length;
                var charat = name.charAt(length-1);
//                alert(charat);
                if(!(((charat < '9')&&(charat > '0')) || (charat == '9') || (charat == '0') || ((charat < 'Z') && (charat > 'A')) || (charat == 'Z') || (charat == 'A') || ((charat < 'z') && (charat > 'a')) || (charat == 'z') || (charat == 'a') || (charat == '-') || (charat == '_'))){
                    name=name.substr(0,length-1);
                    $("#"+location).val(name);
                }else{
                }
            }
            
//            function onblur=\"javascript:checkempty('patientcorrespondencename')\"
            function checkempty(location){
                    var name=$("#"+location).val();
                    var len=name.length;
                    // alert(time);
                    if(len == 0)
                    {
                            $("#"+location).css("border","4px solid red");
                            $("#"+location).focus();
                    }else{
                            $("#"+location).css("border"," 1px solid #aaa");
                    }
            }
            
            function patientcorrespondence(){
                var name = $("#patientcorrespondencename").val();
                var len=name.length;
                if(len == 0)
                    {
                            $("#patientcorrespondencename").css("border","4px solid red");
                            $("#patientcorrespondencename").focus();
                    }
                else{
                            $("#"+location).css("border"," 1px solid #aaa");
                            $("#patientcorrespondencesubmit").click();
                }
            }
            
            function onDelete(id, num)
            {
                var r = confirm("The selected document will be permenantly deleted from Accendo, please confirm");
                var url = id.id;
                var sele = "#billingcompany_doc_" + num;
                if (r == true)
                {
                    $.post("<?php echo $this->baseUrl ?>/biller/data/deletebillingdocs/", {url: url, type: "billingcompany"},
                    function (data) {
                        var answer = '';
                        eval("answer=" + data + ";");
                        //alert("abc"+answer.result);
                        if (answer.result == "true") {
                            $(sele).remove();
                        } else
                        {
                            alert("Unalbe to delete");
                        }
                    });
                }
                else
                {
                    //alert("No Doc Exsit!");
                }
                //$(sele).remove();
                //$.post("<?php echo $this->baseUrl ?>/biller/claims/deletedocs/",{url:url},function(data){});
            }
        </script>
    </head>
    <body>
        <a href="<?php echo $this->baseUrl ?>" target="_top" id="relogin" style="display: none" >wwwwww</a>
        <div id="navbar">
            <p>Your Location: <a title="">Data Management</a> &gt; Billing Company</p>
        </div>
        <div class="table-div" >
            <form  method="post" action="" >
                <table width="100%">
                    <tr>
                       <!-- <th align="left">Company Name</th>
                        <td>
                            <select class="select" name="billingcompany_id" id="billingcompany_id" style= "width:100% " onchange="javascript:auto_complete()" >
                                <option value="">Select</option>
                        <?php
                        foreach ($this->billingcompanyList as $row) {
                            echo "<option value='" . $row->id . "'>" . $row->billingcompany_name . "</option>";
                        }
                        ?>
                            </select>
                        </td>-->
                        <th align="left">Phone Number</th><td ><input type="text" name="phone_number" id="phone_number" value=".<?php $this->billingcompanyData->phone_number; ?>."/></td>
                        <th align="left">Fax Number</th><td><input type="text" name="fax_number" id="fax_number" /></td>
                        <th align="left">Default Provider</th><td><input type="text" name="default_provider" id="default_provider" /></td>

                        <th  align="left">Street Address</th><td><input type="text" name="street_address" id="street_address" style="width: 99%" /></td>
                    </tr>
                    <tr>
                        <th align="left">City</th><td><input type="text" name="city" id="city"  /></td>
                        <th align="left">State</th><td><input type="text" name="state" id="state"  /></td>
                        <th align="left">Zip Code</th><td><input type="text" name="zip" id="zip"  /></td>

                        <th alith="left">Time Out</th>
                        <td>
                            <select class="select" name="time_out" id="time_out" style= "width:100% ">
                                <option value="">Select</option>
                                <option value="0">0</option>
                                <option value="15">15</option>
                                <option value="30">30</option>
                                <option value="60">60</option>
                                <option value="120">120</option>
                            </select>
                        </td>
                    </tr>

                    <tr>
                        <th  align="left">Patient Document Types</th><td><input type="text" name="patient_doc_types" id="patient_doc_types" onkeyup="javascript:displaycheck('#patient_doc_types')" /></td>

                        <th align="left">Claim Document Types</th><td><input type="text" name="claim_doc_types" id="claim_doc_types"  onkeyup="javascript:displaycheck('#claim_doc_types')" /></td>

                        <th align="left">Patient DocumentSources</th><td><input type="text" name="patient_doc_sources" id="patient_doc_sources"  onkeyup="javascript:displaycheck('#patient_doc_sources')" /></td>

                        <th align="left">Claim Document Sources</th><td><input type="text" name="claim_doc_sources" id="claim_doc_sources" style="width: 99%" onkeyup="javascript:displaycheck('#claim_doc_sources')" /></td>

                    </tr>
                    <tr>

                        <th align="left">Appeal1</th><td><input type="text" name="appeal1" id="appeal1"  /></td>
                        <th align="left">Appeal2</th><td><input type="text" name="appeal2" id="appeal2"  /></td>

                        <th align="left">Appeal3</th><td><input type="text" name="appeal3" id="appeal3"  /></td>
                        <th align="left">Payment From</th><td><input type="text" name="paymentfrom" id="paymentfrom"  /></td> 
                    </tr>
                    <tr>
                        <th align="left">Salutations</th><td><input type="text" name="salutations" id="salutations"  onkeyup="javascript:displaycheck('#salutations')" /></td>

                        <th >Document Feature</th>
                        <td>
                            <select class="select" name="document_feature" id="document_feature" style= "width:100% ">
                                <option value=1>ON</option>
                                <option value=0>OFF</option>

                            </select>
                        </td>
                         <th >Insurance Tags</th>
                        <td>
                            <input type="text" name="insurancetags" id="insurancetags" onkeyup="javascript:check_tags_input('insurancetags')"/>
                        </td>
                        <th >Provider Tags</th>
                        <td>
                            <input type="text" name="providertags" id="providertags" onkeyup="javascript:check_tags_input('providertags')"/>
                        </td>
                        <tr>
                        <th >Rendering Provider Tags</th>
                        <td>
                            <input type="text" name="renderingprovidertags" id="renderingprovidertags" onkeyup="javascript:check_tags_input('renderingprovidertags')"/>
                        </td>
                        <th >Options Tags</th>
                        <td>
                            <input type="text" name="optionstags" id="optionstags" onkeyup="javascript:check_tags_input('optionstags')"/>
                        </td>
                        </tr>
                        <tr>
                            <tr>
                                <th > Color Coding</th>
                                <td colspan="7">
                                    <div id="cAt">

                                    </div>
                                    <!---------content to DB---------->
                                    <input type="text" name="tags" id="tags" value="" style="display: none"/>
                                </td>
                            </tr>
                            <tr>
                                <th >Notes</th><td colspan="7"><textarea style= "width:100%" rows="4"  name="notes" id="notes" ></textarea></td>
                            </tr>
                            <td ><input type="submit" name="submit" value="Update" /></td>

                            <td colspan="5"></td>
                            <input type="text" name="claim_doc_types_array" id="claim_doc_types_array" style= "display: none "/>
                            <input type="text" name="claim_doc_sources_array" id="claim_doc_sources_array" style= "display: none "/>
                            </table>
                            </form>
                            <br></br>
                            <br></br>  
                            <form id="documentform" enctype="multipart/form-data" method="post">
                                <table width="100%">
                                    <td style="display:none">
                                        <input type ="text" name="uploadtype" id="uploadtype" value="documents">
                                    </td>
                                    <tr>
                                        <th colspan="4">
                                            <p  style="text-align: center;font-size: 16px;">Documents</p>
                                        </th>
                                    </tr>
                                    <tr>
                                        <th width="25%" style="background:#eeeeee;text-align: center">Data and Time</th>
                                        <th width="25%" style="background:#eeeeee;text-align: center">Description</th>
                                        <th width="25%" style="background:#eeeeee;text-align: center">User</th>
                                        <th width="25%" style="background:#eeeeee;text-align: center"></th>
                                    </tr>
                                    <?php
                                    $i = 0;
                                    foreach ($this->billingcompany_doc_list as $rows) {
                                        if ($i % 2 == 0) {
                                            echo"<tr id=\"billingcompany_doc_" . $i . "\" style=\"background:#FF0000\">";
                                            echo "<th width='25%' style='text-align: center' > <a href = \"/accendo/public/" . $rows['url'] . " \" target = \" _blank \">" . $rows['date'] . "</a></th>";
                                            echo "<th width='25%' style='text-align: center'>" . $rows['desc'] . "</th>";
                                            echo "<th width='25%' style='text-align: center'>" . $rows['user'] . "</th>";
                                            echo "<th width='25%' style='text-align: center'><input id = " . $rows['url'] . " style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this" . "," . $i . ")\">" . "</input></th>";
                                        }
                                        if ($i % 2 == 1) {
                                            echo "<tr id=\"billingcompany_doc_" . $i . "\" style=\"background:#00FF00\">";
                                            echo "<th width='25%' style='background:#eeeeee;text-align: center' > <a href = \"/accendo/public/" . $rows['url'] . " \" target = \" _blank \">" . $rows['date'] . "</a></th>";
                                            echo "<th width='25%' style='background:#eeeeee;text-align: center'>" . $rows['desc'] . "</th>";
                                            echo "<th width='25%' style='background:#eeeeee;text-align: center'>" . $rows['user'] . "</th>";
                                            echo "<th width='25%' style='background:#eeeeee;text-align: center'><input id =" . $rows['url'] . " style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this" . "," . $i . ")\">" . "</input></th>";
                                        }
                                        echo "</tr>";
                                        $i = $i + 1;
                                    }
                                    if ($i % 2 == 0) {//echo"<form enctype=\"multipart/form-data\"  method=\"POST\"><tr >";
                                        echo "<tr>";
                                        echo "<th width='25%' style='text-align: center' >" . "<input name=\"uploadedfil\" type=\"file\" id=\"uploadedfil\" /></th>";
                                        echo "<th width = '25%' style='text-align: center' id = \"desc\">
                            <input type=\"text\" name=\"desc\"  id=\"desc\" ></input>
                            </th>";
                                        echo "<th width='25%' style='text-align: center'>" . $this->user_name . "</th>";
                                        echo "<th width='25%' style='text-align: center'><input id=\"upload\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"submit\" name=\"submit\" value=\"UPLOAD\"></input>";
                                    }
                                    if ($i % 2 == 1) {//echo "<form enctype=\"multipart/form-data\"  method=\"POST\"><tr >";
                                        echo "<tr>";
                                        echo "<th width='25%' style='background:#eeeeee; text-align: center' >" . "<input name=\"uploadedfil\" type=\"file\" id=\"uploadedfil\" /></th>";
                                        echo "<th width = '25%' id = \"des\" style='background:#eeeeee;text-align: center'>
                            <input type=\"text\" name=\"desc\"  id=\"desc\" ></input>
                            </th>";
                                        echo "<th width='25%' style='background:#eeeeee; text-align: center'>" . $this->user_name . "</th>";
                                        echo "<th width='25%' style='background:#eeeeee; text-align: center'><input id=\"upload\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"submit\" name=\"submit\" value=\"UPLOAD\" ></input>";
                                    }
                                    //echo "</form></tr>";
                                    echo "</tr>";
                                    ?>
                                </table>
                                <br></br>
                                <br></br> 
                            </form>
                            <form enctype="multipart/form-data" method="post" name="form3" id="form3">
                                <table width="100%">
                                    <td style="display:none">
                                        <input type ="text" name="uploadtype" id="uploadtype" value="patientcorrespondence">
                                        <input type ="text" name="pt_uploadtype" id="pt_uploadtype">
                                        <input type ="text" name="submit" id="submit" value="UPLOAD">
                                        <input type ="text" name="uploadfilepath" id="uploadfilepath">
                                        <input type ="text" name="scroll_pos" id="scroll_pos">
                                    </td>

                                    <tr>
                                        <th colspan="4">
                                            <p  style="text-align: center;font-size: 16px;">Patient Correspondence</p>
                                        </th>
                                    </tr>
                                    <tr>
                                        <th width="25%" style="background:#eeeeee;text-align: center">Name for Template File</th>
                                        <th width="25%" style="background:#eeeeee;text-align: center">File Path</th>
                                        <th width="25%" style="background:#eeeeee;text-align: center">Merge Field</th>
                                        <th width="25%" style="background:#eeeeee;text-align: center"></th>
                                    </tr>
                                    <?php
                                    $i = 0;
                                    foreach ($this->patientcorrespondence_doc_list as $rows) {
                                        if ($i % 2 == 0) {
                                            echo"<tr id=\"patientcorrespondence_doc_" . $i . "\" style=\"background:#FF0000\">";
                                            echo "<th width = '25%' style='text-align: center' id = \"patientcorrespondence_name\">
                                                <input type=\"text\" name=\"patientcorrespondence_name_".$rows['patientcorrespondence_name']."\"  "
                                                    . "id=\"patientcorrespondence_name_".$rows['patientcorrespondence_name']."\" value=\"".$rows['patientcorrespondence_name']."\"
                                                    onkeyup=\"javascript:valuecheckandchange('patientcorrespondence_name_".$rows['patientcorrespondence_name']."')\"
                                                    onblur=\"javascript:checkempty('patientcorrespondence_name_".$rows['patientcorrespondence_name']."')\"></input>
                                                </th>";     
                                            echo "<th width='25%' style='text-align: center' >" . "<input name=\"uploadedfil\" type=\"file\" id=\"uploadedfil_patient_cor\" disabled/></th>";
                                            echo "<th width = '25%' style='text-align: center' id = \"patientcorrespondence_merge\">
                                                <select name=\"merge_field_".$rows['patientcorrespondence_name']."\" "
                                                    . "id=\"merge_field_".$rows['patientcorrespondence_name']."\" 
                                                        style=\"width: 50%;float:left\" onchange=\"javascript:showoptionfieldExisting('".$rows['patientcorrespondence_name']."')\"> 
                                                <option value=\"select_option\">Select</option>";  
                                            for($mark = 0; $mark < count($rows['merge_fields']); $mark ++){
                                             echo "<option value=".$rows['merge_fields'][$mark]['name'].">".$rows['merge_fields'][$mark]['name']."</option>";
                                            }
                                            echo "</select>";
                                            echo "<input type=\"text\" name=\"merge_public_input_".$rows['patientcorrespondence_name']."\" id=\"merge_public_input_".$rows['patientcorrespondence_name']."\" "
                                            . "style=\"display: none;width: 47%\;float:right\" onchange=\"javascript:setValueExisting('".$rows['patientcorrespondence_name']."')\">";
                                            for($mark = 0; $mark < count($rows['merge_fields']); $mark ++){
                                                if(($rows['merge_fields'][$mark]['value'] != null)&&($rows['merge_fields'][$mark]['value'] != "")){
                                                    echo "<td style=\"display:none\">"
                                                        . "<input type=\"text\" name=\"".$rows['merge_fields'][$mark]['name']."_".$rows['patientcorrespondence_name']."_existing\" id=\"".$rows['merge_fields'][$mark]['name']."_".$rows['patientcorrespondence_name']."_existing\""
                                                        . " value=\"".$rows['merge_fields'][$mark]['value']."\">"
                                                        ."</td>";
                                                }else{
                                                     echo "<td style=\"display:none\">"
                                                        . "<input type=\"text\" name=\"".$rows['merge_fields'][$mark]['name']."_".$rows['patientcorrespondence_name']."_existing\" id=\"".$rows['merge_fields'][$mark]['name']."_".$rows['patientcorrespondence_name']."_existing\""
                                                        ."\">"
                                                        ."</td>";                                                   
                                                }
                                            }           
                                            echo "</th>";     
                                   
                                            echo "<th width='25%' style='text-align: center'>"
                                            . "<input id = \"update". $rows['url'] ."\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:30%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"UPDATE\" onclick = \"javascript:updatePatientCorrespondence('".$rows['url']."'". "," . $i . ",'".$rows['patientcorrespondence_name']."')\">" . "</input>"
                                            . "  <input id = \"delete" . $rows['url'] ."\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:30%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDeletePatientCorrespondence('".$rows['url']."'". "," . $i . ",'".$rows['patientcorrespondence_name']."')\">" . "</input></th>";
                                            echo "</tr>";

                                        }
                                        if ($i % 2 == 1) {
                                            
                                            echo"<tr id=\"patientcorrespondence_doc_" . $i . "\" style=\"background:#eeeeee\">";
                                            echo "<th width = '25%' style='background:#eeeeee;text-align: center' id = \"patientcorrespondence_name\">
                                                <input type=\"text\" name=\"patientcorrespondence_name_".$rows['patientcorrespondence_name']."\"  "
                                                    . "id=\"patientcorrespondence_name_".$rows['patientcorrespondence_name']."\" value=\"".$rows['patientcorrespondence_name']."\"
                                                    onkeyup=\"javascript:valuecheckandchange('patientcorrespondence_name_".$rows['patientcorrespondence_name']."')\"
                                                    onblur=\"javascript:checkempty('patientcorrespondence_name_".$rows['patientcorrespondence_name']."')\"></input>
                                                </th>";     
                                            echo "<th width='25%' style='background:#eeeeee;text-align: center' >" . "<input name=\"uploadedfil\" type=\"file\" id=\"uploadedfil_patient_cor\" disabled/></th>";
                                            echo "<th width = '25%' style='background:#eeeeee;text-align: center' id = \"patientcorrespondence_merge\">
                                                <select name=\"merge_field_".$rows['patientcorrespondence_name']."\" "
                                                    . "id=\"merge_field_".$rows['patientcorrespondence_name']."\" 
                                                        style=\"width: 50%;float:left\" onchange=\"javascript:showoptionfieldExisting('".$rows['patientcorrespondence_name']."')\"> 
                                                <option value=\"select_option\">Select</option>";  
                                            for($mark = 0; $mark < count($rows['merge_fields']); $mark ++){
                                             echo "<option value=".$rows['merge_fields'][$mark]['name'].">".$rows['merge_fields'][$mark]['name']."</option>";
                                            }
                                            echo "</select>";
                                            echo "<input type=\"text\" name=\"merge_public_input_".$rows['patientcorrespondence_name']."\" id=\"merge_public_input_".$rows['patientcorrespondence_name']."\" "
                                            . "style=\"display: none;width: 47%\;float:right\" onchange=\"javascript:setValueExisting('".$rows['patientcorrespondence_name']."')\">";
                                            for($mark = 0; $mark < count($rows['merge_fields']); $mark ++){
                                                if(($rows['merge_fields'][$mark]['value'] != null)&&($rows['merge_fields'][$mark]['value'] != "")){
                                                    echo "<td style=\"display:none\">"
                                                        . "<input type=\"text\" name=\"".$rows['merge_fields'][$mark]['name']."_".$rows['patientcorrespondence_name']."_existing\" id=\"".$rows['merge_fields'][$mark]['name']."_".$rows['patientcorrespondence_name']."_existing\""
                                                        . " value=\"".$rows['merge_fields'][$mark]['value']."\">"
                                                        ."</td>";
                                                }else{
                                                     echo "<td style=\"display:none\">"
                                                        . "<input type=\"text\" name=\"".$rows['merge_fields'][$mark]['name']."_".$rows['patientcorrespondence_name']."_existing\" id=\"".$rows['merge_fields'][$mark]['name']."_".$rows['patientcorrespondence_name']."_existing\""
                                                        ."\">"
                                                        ."</td>";                                                   
                                                }
                                            }           
                                            echo "</th>";     
                                   
                                            echo "<th width='25%' style='text-align: center'>"
                                            . "<input id = \"update". $rows['url'] ."\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:30%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"UPDATE\" onclick = \"javascript:updatePatientCorrespondence('".$rows['url']."'". "," . $i . ",'".$rows['patientcorrespondence_name']."')\">" . "</input>"
                                            . "  <input id = \"delete" . $rows['url'] ."\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:30%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDeletePatientCorrespondence('".$rows['url']."'". "," . $i . ",'".$rows['patientcorrespondence_name']."')\">" . "</input></th>";
                                            echo "</tr>";
                                        }
                                        $i = $i + 1;
                                    }
                                    if($this->merge_flag == "merge_flag"){//echo "<form enctype=\"multipart/form-data\"  method=\"POST\"><tr >";
                                        if ($i % 2 == 0) {
                                        echo "<tr>";  
                                        echo "<th width = '25%' style='text-align: center' id = \"patientcorrespondence_name\">
                            <input type=\"text\" name=\"patientcorrespondencename\"  id=\"patientcorrespondencename\" value=\"" .$this->name_for_template."\" 
                                onkeyup=\"javascript:valuecheckandchange('patientcorrespondencename')\"
                                 onblur=\"javascript:checkempty('patientcorrespondencename')\"></input>
                           </th>";      
                                         echo "<th width = '25%' style='text-align: center' id = \"show_file\">
                            <input type=\"button\" name=\"changefile\"  id=\"changefile\" value=\"Change File\" onclick=\"javascript:change_patientcor_file()\" ></input>
                            <input type=\"text\" name=\"show_file_path\" id=\"show_file_path\" value=".$this->front_page_file_name." disabled>
                            <input name=\"uploadedfil_patientcor\" type=\"file\" id=\"uploadedfil_patientcor\" onchange=\"javascript:getMergeField()\" style=\"display: none\"/>                                
                           </th>";  
                                        echo "<th width = '25%' style='text-align: center' id = \"patientcorrespondence_merge\">
                                          <select name=\"merge_field\" id=\"merge_field\" style=\"width: 50%;float:left\" onchange=\"javascript:showoptionfield()\"> 
                                        <option value=\"select_option\">Select</option>";  
                                         for($mark = 0; $mark < count($this->merge_field_list); $mark ++){
                                             echo "<option value=".$this->merge_field_list[$mark].">".$this->merge_field_list[$mark]."</option>";
                                         }
                            echo "</select>";
                            echo "<input type=\"text\" name=\"merge_public_input\" id=\"merge_public_input\" style=\"display: none;width: 47%\;float:right\" onchange=\"javascript:setValue()\">
                           </th>";     
                                         for($mark = 0; $mark < count($this->merge_field_list); $mark ++){
                                              echo "<td style=\"display:none\">"
                                             . "<input type=\"text\" name=".$this->merge_field_list[$mark]." id=".$this->merge_field_list[$mark].">"
                                                 ."</td>";
                                         }
                                        echo "<th width='25%' style='text-align: center'><input id=\"upload\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"submit\" name=\"getMergeFieldSubmit\" value=\"UPLOAD\"></input>";
                                    }
                                    if ($i % 2 == 1) {
                                         echo "<tr>";  
                                        echo "<th width = '25%' style='background:#eeeeee;text-align: center' id = \"patientcorrespondence_name\">
                            <input type=\"text\" name=\"patientcorrespondencename\"  id=\"patientcorrespondencename\" value=\"" .$this->name_for_template."\" 
                                onkeyup=\"javascript:valuecheckandchange('patientcorrespondencename')\"
                                onblur=\"javascript:checkempty('patientcorrespondencename')\"></input>
                                </th>";      
                                         echo "<th width = '25%' style='background:#eeeeee;text-align: center' id = \"show_file\">
                            <input type=\"button\" name=\"changefile\"  id=\"changefile\" value=\"Change File\" onclick=\"javascript:change_patientcor_file()\" ></input>
                            <input type=\"text\" name=\"show_file_path\" id=\"show_file_path\" value=".$this->front_page_file_name." disabled>
                            <input name=\"uploadedfil_patientcor\" type=\"file\" id=\"uploadedfil_patientcor\" onchange=\"javascript:getMergeField()\" style=\"display: none\"/>                                
                           </th>";  
                                        echo "<th width = '25%' style='background:#eeeeee;text-align: center' id = \"patientcorrespondence_merge\">
                                          <select name=\"merge_field\" id=\"merge_field\" style=\"width: 50%;float:left\" onchange=\"javascript:showoptionfield()\"> 
                                        <option value=\"select_option\">Select</option>";  
                                         for($mark = 0; $mark < count($this->merge_field_list); $mark ++){
                                             echo "<option value=".$this->merge_field_list[$mark].">".$this->merge_field_list[$mark]."</option>";
                                         }
                            echo "</select>";  
                            echo "<input type=\"text\" name=\"merge_public_input\" id=\"merge_public_input\" style=\"display: none;width: 47%;float:right\" onchange=\"javascript:setValue()\">
                           </th>";     
                                        for($mark = 0; $mark < count($this->merge_field_list); $mark ++){
                                             echo "<td style=\"display:none\">"
                                             . "<input type=\"text\" name=".$this->merge_field_list[$mark]." id=".$this->merge_field_list[$mark].">"
                                                 ."</td>";
                                        }
                                        echo "<th width='25%' style='background:#eeeeee;text-align: center'><input id=\"upload\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"submit\" name=\"getMergeFieldSubmit\" value=\"UPLOAD\"></input>";                                         
                                    }
                                }
                                else{
                                        if ($i % 2 == 0) {//echo "<form enctype=\"multipart/form-data\"  method=\"POST\"><tr >";
                                        echo "<tr>";
                                        echo "<th width = '25%' style='text-align: center' id = \"patientcorrespondence_name\">
                            <input type=\"text\" name=\"patientcorrespondencename\"  id=\"patientcorrespondencename\" 
                            onkeyup=\"javascript:valuecheckandchange('patientcorrespondencename')\"
                            onblur=\"javascript:checkempty('patientcorrespondencename')\"></input>
                           </th>";                                        
                                        echo "<th width='25%' style='text-align: center' >" . "<input name=\"uploadedfil\" type=\"file\" id=\"uploadedfil_patient_cor\" onchange=\"javascript:getMergeField()\"/></th>";
                                        echo "<th width = '25%' style='text-align: center' id = \"patientcorrespondence_merge\">
                            <select name=\"merge_field\" id=\"merge_field\" style=\"width: 50%;float:left\">
                            <option value=\"select_option\">Select</option>
                            </select>
                            <input type=\"text\" name=\"merge_public_input\" id=\"merge_public_input\" style=\"display: none\">
                           </th>";     
                                        echo "<th width='25%' style='text-align: center'><input id=\"upload\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\""
                                        . " align=\"middle\" type=\"button\" name=\"getMergeFieldSubmit\" value=\"UPLOAD\" "
                                                . "onclick=\"javascript:patientcorrespondence()\"></input>";                                     }
                                    if ($i % 2 == 1) {//echo "<form enctype=\"multipart/form-data\"  method=\"POST\"><tr >";
                                        echo "<tr>";
                                        echo "<th width = '25%' style='background:#eeeeee;text-align: center' id = \"patientcorrespondence_name\">
                            <input type=\"text\" name=\"patientcorrespondencename\"  id=\"patientcorrespondencename\" 
                            onkeyup=\"javascript:valuecheckandchange('patientcorrespondencename')\"
                            onblur=\"javascript:checkempty('patientcorrespondencename')\"></input>
                            </th>";                                        
                                        echo "<th width='25%' style='background:#eeeeee;text-align: center' >" . "<input name=\"uploadedfil\" type=\"file\" id=\"uploadedfil_patient_cor\" onchange=\"javascript:getMergeField()\"/></th>";
                                        echo "<th width = '25%' style='background:#eeeeee;text-align: center' id = \"patientcorrespondence_merge\">
                            <select name=\"merge_field\" id=\"merge_field\" style=\"width: 50%;float:left\">
                            <option value=\"select_option\">Select</option>
                            </select>
                            <input type=\"text\" name=\"merge_public_input\" id=\"merge_public_input\" style=\"display: none\">                            
                           </th>";     
                                        echo "<th width='25%' style='background:#eeeeee;text-align: center'><input id=\"upload\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\""
                                        . " align=\"middle\" type=\"button\" name=\"getMergeFieldSubmit\" value=\"UPLOAD\" "
                                                . "onclick=\"javascript:patientcorrespondence()\"></input>";
                                     }
                                    }
                                    //echo "</form></tr>";
                                    echo "</tr>";
                                    ?>
                                     <td style="display:none">
                                        <input type="submit" name="patientcorrespondencesubmit" id ="patientcorrespondencesubmit">
                                        <input type ="submit" name="getmergelist" id="getmergelist" value="GETMERGELIST">
                                    </td>
                                </table>
                                <br></br>
                                <br></br> 
                            </form>
<!--                            <form enctype="multipart/form-data">
                                <td style="display:none">
                                        <input type ="text" name="uploadtype" id="uploadtype" value="patientcorrespondence">
                                        <input type ="text" name="pt_uploadtype" id="pt_uploadtype">
                                        <input type="submit" name="getMergeFieldSubmit" id="getMergeFieldSubmit"/>
                                    </td>
                            </form>-->
                            <form  method="post" action="" id ="datalogform">
                                <table width="100%">
                                    <td ><input type="submit" name="submit" value="Data Log" /></td>

                                    <table/>

                                    </div>
                                    </body>
                                    </html>