<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Accendo</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/layout.css" />
        <link rel="stylesheet" rev="stylesheet" type="text/css" media="screen, projection" href="<?php echo $this->baseUrl ?>/styles/pagenav.css" />
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery.js"></script>
       
        <script type="text/javascript" language="Javascript" >
        $(document).ready(function(){
            $.post("<?php echo $this->baseUrl ?>/biller/claims/timeout/",
                function(data)
                {
                    if(data!='no'&&data!=null) {
                        var a=document.getElementById("relogin");
                        a.click(); 
                    }
                }
            );
            $("#provider_id").change(function(){
            var provider_id = $("#provider_id").val();
            $(".doc_line").remove();
            if(provider_id){
                  $("#fax_number").val('');
//                    $("#provider_id").val('');
                    $("#street_address").val('');
                    $("#zip").val('');
                    $("#state").val('');
                    $("#city").val('');
                    $("#phone_number").val('');
                    $("#secondary_phone_number").val('');
                    $("#notes").val('');
                $("#id option").remove();
                $("#id").append("<option value=\"\">Select</option>");
                $.post("<?php echo $this->baseUrl ?>/biller/data/renderinglist/",{provider_id:provider_id},function(data){
                    var myjson='';
                    eval("myjson=" + data + ";");
                    for(var i = 0;i<myjson.renderingproviderList.length;i++){
                    $("#id").append("<option value='"+myjson.renderingproviderList[i]['id']+"'>"+myjson.renderingproviderList[i]['last_name']
                        +","+myjson.renderingproviderList[i]['last_name']+"</option>")
                    }
                    
                });
            }
        });
        }
    );
        </script>
        <script type="text/javascript" language="Javascript" >
            function auto_complete()
            {
                var id=$("#id").val();
                 var provider_id = $("#provider_id").val();
                if(id.length!=0)
                {
                    $.post("<?php echo $this->baseUrl ?>/biller/data/renderingproviderinfo/",{id:id,provider_id:provider_id},
                    function(data){
                        var myjson='';
                        eval("myjson=" + data + ";");
                        $("#fax_number").val(myjson.fax_number);
                        $("#provider_name").val(myjson.provider_name);
                        $("#street_address").val(myjson.street_address);
                        $("#zip").val(myjson.zip);
                        $("#state").val(myjson.state);
                        $("#city").val(myjson.city);
                        $("#phone_number").val(myjson.phone_number);
                        $("#secondary_phone_number").val(myjson.secondary_phone_number);
                        $("#notes").val(myjson.notes);
                        $("#payer_id option").remove();
                        $("#payer_id").append("<option value=''>select</option>");
                        for(var i=0;i<myjson.innetworkpayersList.length;i++){
                            $("#payer_id").append("<option value='"+
                                myjson.innetworkpayersList[i]['insurance_id']+
                                "'>"+myjson.innetworkpayersList[i]['insurance_display']+
                                "</option>");
                        }
                        $("#status").val(myjson.status);
                        $(".doc_line").remove();
                        for(var i=0;i<myjson.rprovider_doc_list.length;i++)
                        {   
                            if (i%2 == 0){
                                $("#doc_table").append("<tr class='doc_line' id='provider_doc_" + i + "' style = 'background:#FF0000'>" +
                                        "<td width='33%' style='text-align: center' >" + "<a href = \"/accendo/public/" + myjson.rprovider_doc_list[i]['url'] + "\" target = \" _blank \">" + myjson.rprovider_doc_list[i]['date'] + "</a></td>" +
                                        "<td width='33%' style='text-align: center'>" + myjson.rprovider_doc_list[i]['desc'] + "</td>" +
                                        "<td width='34%' style='text-align: center'>" + myjson.rprovider_doc_list[i]['user'] + "</td>" +
                                        "</tr>");
                            }else{
                                $("#doc_table").append("<tr class='doc_line' id='provider_doc_" + i + "' style = 'background:#FF0000'>" +
                                        "<td width='33%' style='background:#eeeeee;text-align: center' >" + "<a href = \"/accendo/public/" + myjson.rprovider_doc_list[i]['url'] + "\" target = \" _blank \">" + myjson.rprovider_doc_list[i]['date'] + "</a></td>" +
                                        "<td width='33%' style='background:#eeeeee;text-align: center'>" + myjson.rprovider_doc_list[i]['desc'] + "</td>" +
                                        "<td width='34%' style='background:#eeeeee;text-align: center'>" + myjson.rprovider_doc_list[i]['user'] + "</td>" +
                                        "</tr>");
                            }
                        }
                    });
                }
                else
                {
                    $("#fax_number").val('');
                    $("#provider_name").val('');
                    $("#street_address").val('');
                    $("#zip").val('');
                    $("#state").val('');
                    $("#city").val('');
                    $("#phone_number").val('');
                    $("#secondary_phone_number").val('');
                    $("#notes").val('');
                     $("#status").val('')
                }
            }
        </script>
    </head>

    <body>
        <a href="<?php echo $this->baseUrl ?>" target="_top" id="relogin" style="display: none" >wwwwww</a>
        <div id="navbar">
            <p>Your Location: <a  title="">Claim Management</a> &gt; Rendering Provider</p>
        </div>
        <div class="table-div" >
            <form method="post"  action="" >
                <table>
                    <tr >
                        <th align="left">Provider Name</th>
                          <td >
                            <select class="select" name="provider_id" style= "width:100%" id="provider_id"  style= "width:92% ">
                                <option value="">Select</option>
                                 <?php
                                foreach ($this->providerList as $row) {
                                    $tempnumber=$row['num']-$this->allNumRend['num'];
                                    echo "<option value='" . $row['id'] . "'>" . $row['provider_name'] . "--". $row['street_address'] ."(" . $tempnumber . ")" ."</option>";
                                }
                                ?>
                                   <option value="0">ALL&nbsp;&nbsp;(<?php echo $this->allNumRend['num']; ?>)</option>
                            </select>
                        </td>
                        <th align="left">Rendering Provider</th>
                        <td>
                            <select class="select" name="id" id="id" style= "width:100%" onchange="javascript:auto_complete()"  style= "width:92% ">
                                <option value="">Select</option>
                                <?php
                                foreach ($this->renderingproviderList as $row) {
                                    echo "<option value='" . $row['rid'] . "'>" . $row['last_name'] . ", " . $row['first_name'] . "</option>";
                                }
                                ?>
                            </select>
                        </td>
<!--                        <th align="left">Provider Name</th><td><input type="text" style= "width:99%" name="provider_name" id="provider_name" readonly= "true "/></td>-->
                        <th align="left">Phone Number</th><td><input type="text" style= "width:99%" name="phone_number" id="phone_number" readonly= "true "/></td>
                    </tr>
                    <tr>
                        <th align="left">Second Phone Number</th><td><input type="text" style= "width:99%" name="secondary_phone_number" id="secondary_phone_number" readonly= "true "/></td>
                        <th  align="left">Fax Number</th><td><input style= "width:99%" type="text" name="fax_number" id="fax_number" readonly= "true "/></td>
                        <th align="left">Street Address</th><td><input type="text" style= "width:99%" name="street_address" id="street_address" readonly= "true "/></td>
                    </tr>
                    <tr>
                        <th align="left">Zip</th><td><input type="text" name="zip" style= "width:99%" id="zip" readonly= "true "/></td>
                        <th  align="left">City</th><td><input type="text" name="city" style= "width:99%" id="city" readonly= "true "/></td>
                        <th align="left">State</th><td><input type="text" name="state" style= "width:99%" id="state" readonly= "true "/></td>
                    </tr>
                    <tr>
                        <th align="left" >Innetwork Payers</th>
                        <td>
                            <select class="select" name="payer_id" id="payer_id"   style= "width:100% ">
                                <option value="">Select</option>
                                <?php
                                foreach ($this->payerList as $row) {
                                    echo "<option value='" . $row['id'] . "'>" . $row['insurance_display'] . "</option>";
                                }
                                ?>
                            </select>
                        </td>
                        <th align="left">Status</th><td><input type="text" name="status" style= "width:99%" id="status" readonly= "true "/></td>
                        <th align="left"></th><th></th>
                    </tr>
                    
                    <tr>
                        <th>Notes</th><td colspan="5"><textarea rows="4" style= "width:100%" name="notes" id="notes" readonly= "true "></textarea></td>
                    </tr>
                </table>
                <br></br>
                <br></br>  
                <table id="doc_table">
                    <tr>
                        <th colspan="3"><p  style="text-align: center;font-size: 16px;">Documents</p></th>
                    </tr>
                    <tr>
                        <th width="33%" style="background:#eeeeee;text-align: center">Data and Time</th>
                        <th width="33%" style="background:#eeeeee;text-align: center">Description</th>
                        <th width="34%" style="background:#eeeeee;text-align: center">User</th>
                    </tr>
                    
                </table>
            </form>
        </div>
    </body>
</html>