<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Accendo</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/layout.css" />
        <link href="<?php echo $this->baseUrl ?>/styles/bootstrap.min.css" rel="stylesheet" />
        <link rel="stylesheet" rev="stylesheet" type="text/css" media="screen, projection" href="<?php echo $this->baseUrl ?>/styles/pagenav.css" />
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery.js"></script>
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery-1.11.2.min.js"></script>
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/bootstrap.min.js"></script>
        <script type="text/javascript" language="Javascript" >
        $(document).ready(function(){           
            $("#modifierexisting").val("");
            $.post("<?php echo $this->baseUrl ?>/biller/claims/timeout/",
                function(data)
                {
                    if(data!='no'&&data!=null) {
                        var a=document.getElementById("relogin");
                        a.click(); 
                    }
                }
            );
        </script>
        <script type="text/javascript" language="Javascript">
                function auto_complete(){
                    $("#modifierexisting").val("");
                    var modifier_id = $("#modifier_id").val();
                    $("#modifier").css("border"," 1px solid #aaa");
                    $("#existing").hide(); 
                    $.post("<?php echo $this->baseUrl ?>/biller/data/modifierinfo/",{modifier_id:modifier_id},
                        function(data){
                        var myjson='';
                        eval("myjson=" + data + ";");
                        $("#modifier").val(myjson.modifier);
                        $("#description").val(myjson.description);
                        $("#unit").val(myjson.unit);
                        $("#status").val(myjson.status);
                    });
                 }
        </script>
        <script type="text/javascript" language="Javascript">
            function modifier_validate(){
                var modifier = $("#modifier").val();
                var last_char = modifier.substr(modifier.length - 1, modifier.length);
                if(last_char == " "){
                    modifier = modifier.substr(0,(modifier.length - 1));
                    $("#modifier").val(modifier);                    
                }
                else(modifier.length>2)
                {
                    modifier = modifier.substr(0,2);
                    $("#modifier").val(modifier);
                }
            }
        </script>
        <script type="text/javascript" language="Javascript">
            function unit_validate(){
                var unit = $("#unit").val();
                var last_char = unit.substr(unit.length - 1, unit.length);
                if( last_char < "0" || last_char > "9" || last_char == " "){
                    unit = unit.substr(0,unit.length - 1);
                    $("#unit").val(unit);
                }
            }
        </script> 
        
        <script type="text/javascript" language="Javascript">
               
                function modifier_isexisting(){
                    var modifier = $("#modifier").val();
                    var modifier_id = $("#modifier_id").val();
                    $.post("<?php echo $this->baseUrl ?>/biller/data/modifierexisting/",{modifier:modifier,modifier_id:modifier_id},
                        function(data){
                        var myjson='';
                        eval("myjson=" + data + ";");
                        $("#modifier").css("border"," 1px solid #aaa");
                        $("#existing").hide();
                        $("#modifierexisting").val("");                        
                        if(myjson.ifexisting == "existing"){
                            $("#modifierexisting").val("existing");
                           $("#existing").show();
                           $("#modifier").css("border","4px solid red");
                           $("#modifier").focus();
                        }
                    });
                }
        </script>
    </head>
    <body>
        <a href="<?php echo $this->baseUrl ?>" target="_top" id="relogin" style="display: none" >wwwwww</a>
        <div id="navbar">
            <p>Your Location: <a  title="">Data Management</a> &gt; Modifier</p>
        </div>
        <div class="table-div" >
            <form enctype="multipart/form-data" method="post"  action="" >
                <table>
                    <tr >
                         <th align="left">Modifiers</th>
                        <td >
                            <select class="select"  name="modifier_id" id="modifier_id" onchange="javascript:auto_complete()" style= "width:100%" >
                                <option value="-1">Select</option>
                                <?php
                                foreach ($this->modifierList as $row) {
                                    echo "<option value='" . $row['id'] . "'>" . $row['data'] ."</option>";
                                }
                                ?>
                            </select>
                        </td>
                         <th align="left">Modifier</th><td><input type="text" size="55" name="modifier" id="modifier" onkeyup="javascript:modifier_validate()" onblur="javascript:modifier_isexisting()"/>
                         <a name="existing" id="existing"  style='color:red;display:none' >existing</a>
                         </td>
                        <th align="left">Description</th><td><input type="text" size="55" name="description" id="description"/></td>
                      
                        
                    </tr>
                    <tr>
                        <th align="left">Unit</th><td><input type="text" size="55" name="unit" id="unit" onkeyup="javascript:unit_validate()"/></td>
                        <th align="left">Status</th>
                        <td>
                         <select  class="select"  name="status"  style= "width:100%" id="status">
                            <option value='active'>active</option>
                            <option value='inactive'>inactive</option>
                        </select>
                        </td>
                    </tr>                    
                    <tr>
                        <td ><input type="submit" name="submit" value="Update"/></td>
                        <td ><input type="button" name="delete" id="delete" value="Delete" onclick="deleteFac()"/></td>
                        <div class="modal fade" id="login-modal">
                            <div class="modal-dialog modal-lg">
                                 <div class="modal-content">
                                     <div class="modal-header">
                                         <button class="close" data-dismiss="modal">&times</button>
                                         <h4 style="color:red">This Modifier can not be deleted as the claims below are still associated with the Modifier !</h4>
                                     </div>
                                      <div class="modal-body">
                                           <div class="container-fluid">
                                               <div class="row">
                                                   <div class="col-md-3"><strong>Last Name</strong></div>
                                                   <div class="col-md-3"><strong>First Name</strong></div>
                                                   <div class="col-md-3"><strong>DOS</strong></div>
                                                   <div class="col-md-3"><strong>Provider</strong></div>
                                               </div>
                                               <div id="detail">

                                               </div>

                                           </div>
                                          <br>
                                          <div id="more" style="float:right">More...</div>
                                      </div>
                                      <div class="modal-footer">
                                         <button class="btn btn-default" data-dismiss="modal">
                                            Close
                                         </button>
                                      </div>
                                 </div>
                            </div>
                        </div>
                        
                        <script>
                            function deleteFac(){
                               //var showdetail = document.getElementById("showdetail");
                               var status = $("#status").val();
                               //alert(status);
                               var modifier_id = $("#modifier_id").val();
                               //alert(modifier_id);
                               //var facility_id = $("#facility_id").val();
                               //alert(facility_id);
                                $.post("<?php echo $this->baseUrl ?>/biller/data/deletemodify/",{'modifier_id':modifier_id,'status':status},function(data){
                                    var myjson='';
                                    eval("myjson=" + data + ";");
                                    var flag = myjson.flag;
                                    var status = myjson.status;
                                    if(status==1){
                                        alert('you can not delete an active Modifier');
                                    }else{
                                            if(flag==1){
                                                //alert('can not delete');
                                                var patientinfoArray = myjson.patientinfoArray;
                                                //alert(typeof(patientinfoArray));
                                                //showdetail.style.display="";

                                               
                                                $("#login-modal").modal('show');
                                                var len = patientinfoArray.length;
                                                //alert(len);
                                                if(len>10){
                                                    len = 10;
                                                }else{
                                                    $("#more").hide();
                                                }
                                                for (var i=0;i<len;i++){
                                                    $("#detail").append("<div class=\"row\">"+"<div class=\"col-md-3\">"+patientinfoArray[i]['last_name']+"</div>"+"<div class=\"col-md-3\">"+patientinfoArray[i]['first_name']+"</div>"+"<div class=\"col-md-3\">"+patientinfoArray[i]['dos']+"</div>"+"<div class=\"col-md-3\">"+patientinfoArray[i]['providername']+"</div></div>");
                                                }
                                                $('#login-modal').on('hide.bs.modal',function(){
                                                    $("#detail").children().remove(); //删除所有子元素
                                                });
                                            }else{
                                               alert('delete successfully');
                                               window.location.href="<?php echo $this->baseUrl ?>/biller/data/modifier"; 
                                            }
                                    }
                           

                                });
                            }
                        </script>
                        <td ><input type="submit" name="submit" value="New" /></td>                            
                    </tr>
                    <td style="display:none">
                        <input type ="text" name="modifierexisting" id="modifierexisting">
                    </td>
                </table>
            </form>
        </div>
    </body>
</html>