<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title> Accendo</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/layout.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/jquery.multiselect.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/jquery-ui.css" />
        <link rel="stylesheet" rev="stylesheet" type="text/css" media="screen, projection" href="<?php echo $this->baseUrl ?>/styles/pagenav.css" />
<!--        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery.js"></script>-->
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery-1.8.js"></script>
        <script  type="text/javascript" LANGUAGE="JavaScript" SRC="<?php echo $this->baseUrl ?>/scripts/validation.js"></script>
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery-ui.min.js"></script>
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery.multiselect.js"></script>
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jshelper.js"></script>
        <script type="text/javascript" language="Javascript">
        $(document).ready(function(){
            $.post("<?php echo $this->baseUrl ?>/biller/claims/timeout/",
                function(data)
                {
                    if(data!='no'&&data!=null) {
                        var a=document.getElementById("relogin");
                        a.click(); 
                    }
                }
            );
                $("#provider_id").multiselect();
                $("#provider_id").change(function(){
                    var provider_id = $("#provider_id").val();
                    $("#provider_id_array").val(provider_id);
                });
        });
    
         </script>
         <script type="text/javascript" language="Javascript" >
            function validatepwd()
            {
                var pwd=$("#password").val();
                var rpwd=$("#rpassword").val();
                if(pwd!=rpwd)
                   {
                       alert('Password and Confirm Password Inconsistent!');
                       $("#password").val('');
                       $("#rpassword").val('');
                   }
            }
             function displayprovider(){
             var role=$("#role").val();
               if('guest'==role){
                     document.getElementById("provider_display").style.visibility="visible"; 
                }else{
                     document.getElementById("provider_display").style.visibility="hidden"; 
                }
         }
        </script>
    </head>
    <body>
        <a href="<?php echo $this->baseUrl ?>" target="_top" id="relogin" style="display: none" >wwwwww</a>
        <div id="navbar">
            <p>Your Location: <a  title="">System Management</a> &gt;New User</p>
        </div>
        <div class="table-div">
            <form method="post">
                <table >
                    <tr>
                        <td colspan="6">
                            <p align="center"><b>Right Assignment</b></p>
                        </td>
                    </tr>
                    <tr>
                        <th >Biller Name<font color="#FF0000">*</font></th><td ><input type="text" name="biller_name" id="biller_name" /></td>
<!--                        <th >Billing Company<font color="#FF0000">*</font></th>
                        <td >
                            <select class="select" name="billingcompany_name" style= "width:100% " id="billingcompany_name" >
                                <option value=''>Select</option>
                                <?php
                                foreach ($this->billingcompanyList as $row) {
                                    echo "<option value='" . $row['billingcompany_name'] . "'>" . $row['billingcompany_name'] . "</option>";
                                }
                                ?>
                            </select>
                        </td>-->
                        <th >Right<font color="#FF0000">*</font></th>
                        <td ><select name="role" id="role" style="width:100%" onchange="javascript:displayprovider()">
                                <option value="biller">Biller </option>
                                <option value="billingcompany">Billing Company</option>
<!--                                <option value="admin">Admin</option>-->
                                <option value="guest">Guest</option>
                                <option value="super_admin">Super Admin</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <th >Password<font color="#FF0000">*</font></th><td ><input type="password" name="password" id="password" /></td>
                        <th >Password Confirm<font color="#FF0000">*</font></th><td ><input type="password" name="rpassword" id="rpassword" onblur="javascript:validatepwd()"/></td>
                        <th></th><td></td>
                    </tr>
                     <tr id="provider_display" style="visibility: hidden">
                        <th style= "width:20% ">Provider</th>
                        <td style= "width:20.5% ">
                            <select class="select" name="provider_id" id="provider_id" multiple="multiple" style= "width:15%;scroll:overflow-x">
                                <?php
                                foreach ($this->providerList as $row) {
                                    echo "<option value='" . $row['id'] . "'>" . $row['provider_name'] .
                                    "</option>";
                                }
                                ?>
                            </select>
                        </td> 

                    </tr>
                    <tr>
                        <td><input type="submit" name="next" align="center" value="Save" /></td>
                         <input type="text" name="provider_id_array" id="provider_id_array" style= "display: none "/>
                        <td colspan="4"></td>
                    </tr>
                </table>
            </form>
        </div>
    </body>
</html>