<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Accendo</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/layout.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/datepicker.css" />
        <link rel="stylesheet" rev="stylesheet" type="text/css" media="screen, projection" href="<?php echo $this->baseUrl ?>/styles/pagenav.css" />
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery.js"></script>
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/datepicker.js"></script>
<!--        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery-1.3.2.js"></script>-->
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jshelper.js"></script>
        <script type="text/javascript" language="javascript">
         $(document).ready(function()
        {
            $.post("<?php echo $this->baseUrl ?>/biller/claims/timeout/",
                function(data)
                {
                    if(data!='no'&&data!=null) {
                        var a=document.getElementById("relogin");
                        a.click(); 
                    }
                }
            );
            $("#time_out").val("60");
        });
        </script>
        <script type="text/javascript" language="javascript" >
            function auto_complete(){
                var billingcompany_id=$("#billingcompany_id").val();
                $.post("<?php echo $this->baseUrl ?>/biller/data/billingcompanyinput/",{billingcompany_id:billingcompany_id},function(data){
                    var myjson='';
                    eval("myjson=" + data + ";");
                    if(myjson.billingcompany_name!=null)
                        $("#billingcompany_name").val(myjson.billingcompany_name);
                    if(myjson.default_provider!=null)
                        $("#default_provider").val(myjson.default_provider);
                    if(myjson.street_address!=null)
                        $("#street_address").val(myjson.street_address);
                    if(myjson.zip!=null)
                        $("#zip").val(myjson.zip);
                    if(myjson.state!=null)
                        $("#state").val(myjson.state);
                    if(myjson.city!=null)
                        $("#city").val(myjson.city);
                    if(myjson.phone_number!=null)
                        $("#phone_number").val(myjson.phone_number);
                    if(myjson.fax_number!=null)
                        $("#fax_number").val(myjson.fax_number);
                    if(myjson.notes!=null)
                        $("#notes").val(myjson.notes);
                });
            }
        </script>
    </head>
    <body>
        <a href="<?php echo $this->baseUrl ?>" target="_top" id="relogin" style="display: none" >wwwwww</a>
        <div id="navbar">
            <p>Your Location: <a  title="">System Management</a> &gt;New Billing Company</p>
        </div>
        <div class="table-div" >
            <form  method="post" action="" onsubmit="javascript:return check();">
                <table width="100%">
                    <tr>
                        <th align="left">Company Name<font color="#FF0000">*</font></th>
                        <td ><input type="text" name="billingcompany_name" id="billingcompany_name" /></td>
                        <th align="left">Phone Number<font color="#FF0000">*</font></th><td ><input type="text" name="phone_number" id="phone_number" /></td>
                        <th align="left">Fax Number<font color="#FF0000">*</font></th><td><input type="text" name="fax_number" id="fax_number" /></td>
                        <th align="left">Default Provider</th><td><input type="text" name="default_provider" id="default_provider" /></td>
                    </tr>
                    <tr>
                        <th  align="left">Street Address<font color="#FF0000">*</font></th><td><input type="text" name="street_address" id="street_address" /></td>
                        <th align="left">City<font color="#FF0000">*</font></th><td><input type="text" name="city" id="city"  /></td>
                        <th align="left">State<font color="#FF0000">*</font></th><td><input type="text" name="state" id="state"  /></td>
                        <th align="left">Zip<font color="#FF0000">*</font></th><td><input type="text" name="zip" id="zip"  /></td>
                    </tr>
                     <tr>
                        <th alith="left">Time Out</th><td>
                            <select class="select" name="time_out" id="time_out" style= "width:100% ">
                                <option value="">Select</option>
                                <option value="0">0</option>
                                <option value="15">15</option>
                                <option value="30">30</option>
                                <option value="60">60</option>
                                <option value="120">120</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <th >Notes</th><td colspan="7"><textarea style= "width:100%" rows="4"  name="notes" id="notes" ></textarea></td>
                    </tr>
                    <td ><input type="submit" name="next" value="Save" /></td>
                    <td colspan="7"></td>
                </table>
            </form>
        </div>
    </body>
</html>