<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title> Accendo</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/layout.css" />
        <link rel="stylesheet" rev="stylesheet" type="text/css" media="screen, projection" href="<?php echo $this->baseUrl ?>/styles/pagenav.css" />
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery.js"></script>
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jshelper.js"></script>
        <script  type="text/javascript" LANGUAGE="JavaScript" SRC="<?php echo $this->baseUrl ?>/scripts/validation.js"></script>
       <!--by Pandazhao -->
       <script type="text/javascript" language="Javascript">
      $(document).ready(function()
            {
                $.post("<?php echo $this->baseUrl ?>/biller/claims/timeout/",
                function(data)
                {
                    if(data!='no'&&data!=null) {
                        var a=document.getElementById("relogin");
                        a.click(); 
                    }
                }
            );
            });
       </script>
       <!-- by Pandazhao-->
               <script type="text/javascript" language="Javascript" >
            function mydisplaybill(name)
            {
                var status=$(name).val();
                if(status.length == 1){
                    if(status[0]=='b'||status[0]=='B')
                        $(name).val('Bill-');
                    else
                        $(name).val('');
                }
                else{
    
                    //var claimstatus =$('#claim_status').val();
 
                    var billstatusdisplay =$('#bill_status_display').val();
 
                    if(billstatusdisplay.length>0){
                        
                           $('#btosave').removeAttr('disabled');
                        
                    }
                }
                 isexistingbill()
            }
             function isexistingbill()
            {
                var provider_id=$("#provider_id").val();
              
                var bill_status_display=$("#bill_status_display").val();
                
                //                        alert("if");
                //                        alert(myjson.anesthesia_code);
             
                
                //                            alert("else");
                //                            alert(myjson.payment_expected);
               
                $.post("<?php echo $this->baseUrl ?>/biller/data/billstatusexisting/",{provider_id:provider_id,bill_status_display:bill_status_display},
                function(data){
                    var myjson='';
                    eval("myjson=" + data + ";");
                    var bill_status_display = document.getElementById("bill_status_display");
                    bill_status_display.style.borderColor="#ffffff";
                        $("#bexisting").hide();
                        var myexist=myjson.existing;
                        if(myexist)
                        {
                          bill_status_display.style.borderColor="#ff0000";
                          $("#bexisting").show();
                        }else{
                            bill_status_display.style.borderColor="#ffffff";
                          $("#bexisting").hide();
                        }
                        //$('#modifier_1').val(myjson.modifier_1);
                        //$('#modifier_2').val(myjson.modifier_2);
                    
                 
                });
            }
        </script>
        <script type="text/javascript" language="Javascript" >
            function mydisplay(name)
            {
                var status=$(name).val();
                if(status.length == 1){
                    if(status[0]=='i'||status[0]=='I')
                        $(name).val('Inactive-');
                    else if(status[0]=='o'||status[0]=='O')
                        $(name).val('Open-');
                    else if(status[0]=='c'||status[0]=='C')
                        $(name).val('Closed-');
                    else
                        $(name).val('');
                } else{
    
                    //var claimstatus =$('#claim_status').val();
 
                    var claimstatusdisplay =$('#claim_status_display').val();
 
                    if(claimstatusdisplay.length>0){
                        if(claimstatusdisplay!='open'&&claimstatusdisplay!='closed'&&claimstatusdisplay!='inactive'){
                           $('#tosave').removeAttr('disabled');
                        }
                    }
                }
                 isexisting()
            }
             function isexisting()
            {
                var provider_id=$("#provider_id").val();
              
                var claim_status_display=$("#claim_status_display").val();
                
                //                        alert("if");
                //                        alert(myjson.anesthesia_code);
             
                
                //                            alert("else");
                //                            alert(myjson.payment_expected);
               
                $.post("<?php echo $this->baseUrl ?>/biller/data/claimstatusexisting/",{provider_id:provider_id,claim_status_display:claim_status_display},
                function(data){
                    var myjson='';
                    eval("myjson=" + data + ";");
                    var claim_status_display = document.getElementById("claim_status_display");
                    claim_status_display.style.borderColor="#ffffff";
                        $("#cexisting").hide();
                        var myexist=myjson.existing;
                        if(myexist)
                        {
                          claim_status_display.style.borderColor="#ff0000";
                          $("#cexisting").show();
                        }else{
                            claim_status_display.style.borderColor="#ffffff";
                          $("#cexisting").hide();
                        }
                        //$('#modifier_1').val(myjson.modifier_1);
                        //$('#modifier_2').val(myjson.modifier_2);
                    
                 
                });
            }
        </script>
        <script type="text/javascript" language="Javascript" >
            function mydisplaystatement(name)
            {
                var status=$(name).val();
                if(status.length == 1){
                    if(status[0]=='s'||status[0]=='S')
                        $(name).val('STMT-');
                    else
                        $(name).val('');
                } 
                else{
    
                    //var statementstatus =$('#statement_status').val();
 
                    var statementstatusdisplay =$('#statement_status_display').val();
 
                    if(statementstatusdisplay.length>0){
//                        if(statementstatusdisplay!='open'&&statementstatusdisplay!='closed'&&statementstatusdisplay!='inactive'){
                           $('#stosave').removeAttr('disabled');
//                        }
                    }
                }
                 isexistingstatement()
            }
             function isexistingstatement()
            {
                var provider_id=$("#provider_id").val();
              
                var statement_status_display=$("#statement_status_display").val();
                
                //                        alert("if");
                //                        alert(myjson.anesthesia_code);
             
                
                //                            alert("else");
                //                            alert(myjson.payment_expected);
               
                $.post("<?php echo $this->baseUrl ?>/biller/data/statementstatusexisting/",{provider_id:provider_id,statement_status_display:statement_status_display},
                function(data){
                    var myjson='';
                    eval("myjson=" + data + ";");
                    var statement_status_display = document.getElementById("statement_status_display");
                    statement_status_display.style.borderColor="#ffffff";
                        $("#sexisting").hide();
                        var myexist=myjson.existing;
                        if(myexist)
                        {
                          statement_status_display.style.borderColor="#ff0000";
                          $("#sexisting").show();
                        }else{
                            statement_status_display.style.borderColor="#ffffff";
                          $("#sexisting").hide();
                        }
                        //$('#modifier_1').val(myjson.modifier_1);
                        //$('#modifier_2').val(myjson.modifier_2);
                    
                 
                });
            }
        </script>
    </head>
    <body>
        <a href="<?php echo $this->baseUrl ?>" target="_top" id="relogin" style="display: none" >wwwwww</a>
        <div id="navbar">
            <p>Your Location: <a  title="">Data Management</a> &gt; Claim Status</p>
        </div>
        <div class="table-div" >
            <form action="" method="post" name="Option">
                <table>
                    <tr>
                    <th align="center" colspan="15" style="font-size: larger;line-height:30px;background:#eeeeee">
                        <p align="center"><b><big>Claim Status</big></b></p>
                    </th>
                   </tr>
                    <tr >
<!--                        <th align="left" colspan="1" >Claim Status</th><td><input type="text" name="claim_status" id="claim_status" style= "width:99% "  onkeyup="javascript:mydisplay('#claim_status')"/></td> -->
<!--                        <td  colspan="1" >
                            <select class="select" name="status_id" style= "width:100% " id="status_id" onchange="javascript:changeclaimstatus()">
                                <option value="">Select</option>
                            </select>
                        </td>-->
<!--                        <th align="left">Claim Status Display</th>
                        <td>
                            <select class="select" name="diagnosis_code" id="diagnosis_code" onchange="javascript:auto_complete()" style= "width:100% ">
                                <option value="">Select</option>
                            </select>
                        </td>-->
                        <th align="right" colspan="1">Claim Status</th><td><input type="text" name="claim_status_display" id="claim_status_display" size="50" onkeyup="javascript:mydisplay('#claim_status_display')" onblur="javascript:isexisting()"/>   <a name="cexisting" id="cexisting"  style='color:red;display:none' >existing</a></td>
                    </tr>
                    <tr >
                        <td colspan="2"><input type="submit" name="submit" id="tosave" value="Save Claim Status" disabled=""/></td>
                    </tr>
                    <tr>
                        <tr style="height:50px">  </tr>
                    <th align="center" colspan="15" style="font-size: larger;line-height:30px;background:#eeeeee">
                        <p align="center"><b><big>Bill Status</big></b></p>
                    </th>
                   </tr>
                       <tr >

                        <th align="right" colspan="1">Bill Status</th><td><input type="text" name="bill_status_display" id="bill_status_display" size="50" onkeyup="javascript:mydisplaybill('#bill_status_display')" onblur="javascript:isexisting()"/>   <a name="bexisting" id="bexisting"  style='color:red;display:none' >existing</a></td>
                    </tr>
                    <tr >
                        <td colspan="2"><input type="submit" name="submit" id="btosave" value="Save Bill Status" disabled="" /></td>
                    </tr>
                   <tr style="height:50px">  </tr>
                    <tr>
                    <th align="center" colspan="15" style="font-size: larger;line-height:30px;background:#eeeeee">
                        <p align="center"><b><big>Statement Status</big></b></p>
                    </th>
                   </tr>
                        <tr >

                        <th align="right" colspan="1">Statement Status</th><td><input type="text" name="statement_status_display" id="statement_status_display" size="50" onkeyup="javascript:mydisplaystatement('#statement_status_display')" onblur="javascript:isexisting()"/>   <a name="sexisting" id="sexisting"  style='color:red;display:none' >existing</a></td>
                    </tr>
                    <tr >
                        <td colspan="2"><input type="submit" name="submit" id="stosave" value="Save Statement Status"  disabled=""/></td>
                    </tr>
                </table>
            </form>
        </div>
    </body>
</html>