<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title> Accendo</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/layout.css" />
        <link rel="stylesheet" rev="stylesheet" type="text/css" media="screen, projection" href="<?php echo $this->baseUrl ?>/styles/pagenav.css" />
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery.js"></script>
        <script type="text/javascript" language="Javascript">
        $(document).ready(function(){
           $.post("<?php echo $this->baseUrl ?>/biller/claims/timeout/",
                function(data)
                {
                    if(data!='no'&&data!=null) {
                        var a=document.getElementById("relogin");
                        a.click(); 
                    }
                }
            ); 
        });
        </script>
    </head>
    <body>
        <a href="<?php echo $this->baseUrl ?>" target="_top" id="relogin" style="display: none" >wwwwww</a>
        <div id="navbar">
            <p>Your Location: <a  title="">System Management</a> &gt; CPT Code</p>
        </div>
        <div class="table-div" >
            <form action="" method="post" name="Option">
                <table>
                    <tr >
                        <th align="left">CPT Code<font color="#FF0000">*</font></th><td><input type="text" name="CPT_code" id="CPT_code" size="10"/></td>
                        <th align="left">Description<font color="#FF0000">*</font></th><td><input type="text" name="description" id="description" size="10"/></td>
                    </tr>
                    <tr >
                        <td colspan="8"><input type="submit" name="next" value="Save"/></td>
                    </tr>
                </table>
            </form>
        </div>
    </body>
</html>