<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-
    transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Accendo</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/layout.css"/>
        <link rel="stylesheet" rev="stylesheet" type="text/css" media="screen, projection" href="<?php echo $this->baseUrl ?>/styles/pagenav.css" />
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery.js"></script>
        <script type="text/javascript" language="Javascript">
        $(document).ready(function(){
             $("#FullName").hide();
            $.post("<?php echo $this->baseUrl ?>/biller/claims/timeout/",
                function(data)
                {
                    if(data!='no'&&data!=null) {
                        var a=document.getElementById("relogin");
                        a.click(); 
                    }
                }
            ); 
            $("#provider_id").change(function(){
                     $('#import_or_new').val('new');
                     $('#import_or_new').change();
                     var provider_id = $("#provider_id").val();
                     if(provider_id){
                        $("#last_name option").remove();
                        $("#last_name").append("<option value=\"\">Select</option>");
                        $.post("<?php 
                        echo $this->baseUrl
                                ?>/biller/data/referringproviderexistlist/",{provider_id:provider_id},function(data){
                            var myjson='';
                            eval("myjson=" + data + ";");
                            for(var i = 0;i<myjson.exist_data.length;i++){
                            $("#last_name").append("<option value='"+myjson.exist_data[i]['id']+"'>"+myjson.exist_data[i]['last_name']+","+myjson.exist_data[i]['first_name']
                                +"</option>")
                            }

                        });
                    }
                });
             $('#import_or_new').change(function (e){
                var import_or_new = $("#import_or_new").val();
                if(import_or_new == 'new') {
                    $('#last_name').hide();
                    $('#add_last_name').show();
                    $('#add_first_name').show();
                    $('#add_first_name').val('');
                    $("#NPI").val('');
                    $("#status").val('active');
                    $("#FullName").hide();
                    $("#FirstName").show();
                    $("#LastName").show();
                }
                else {
                    $('#last_name').show();
                    $('#add_last_name').hide();
                    $('#add_first_name').hide();
                    $("#LastName").hide();
                    $("#FirstName").hide();
                    $("#FullName").show();
                    
                }
            });    
        });
        </script>
        <script type="text/javascript" language="Javascript" >
            function auto_complete()
            {
                var id=$("#last_name").val();
                var provider_id=$("#provider_id").val();
                if(id.length!=0)
                {
                    $.post("<?php echo $this->baseUrl ?>/biller/data/referringproviderinfo/",{id:id,provider_id:provider_id},
                    function(data){
                        var myjson='';
                        eval("myjson=" + data + ";");
//                        $("#provider_id").val(myjson.provider_id);
                        $("#NPI").val(myjson.NPI);
                        $("#salutation").val(myjson.salutation);
                        $("#add_first_name").val(myjson.first_name);
                        $("#status").val("active");
                        
                    });
                }
                else
                {
                    $("#NPI").val('');
                    $("#status").val('active');
                }
            }
             function isexisting()
            {
                var provider_id=$("#provider_id").val();
                var add_first_name=$("#add_first_name").val();
                var add_last_name=$("#add_last_name").val();
                var NPI=$("#NPI").val();
                var salutation=$("#salutation").val();
           
                
                //                        alert("if");
                //                        alert(myjson.anesthesia_code);
             
                
                //                            alert("else");
                //                            alert(myjson.payment_expected);
               
                $.post("<?php echo $this->baseUrl ?>/biller/data/referringexisting/",{provider_id:provider_id,add_first_name:add_first_name,add_last_name:add_last_name,NPI:NPI,salutation:salutation},
                function(data){
                    var myjson='';
                    eval("myjson=" + data + ";");
                    var add_last_name = document.getElementById("add_last_name");
                    var add_first_name = document.getElementById("add_first_name");
                    var NPI = document.getElementById("NPI");
                    add_last_name.style.borderColor="#ffffff";
                    add_first_name.style.borderColor="#ffffff";
                    NPI.style.borderColor="#ffffff";
                        $("#existing").hide();
                        var myexist=myjson.existing;
                        if(myexist)
                        {
                          add_last_name.style.borderColor="#ff0000";
                          add_first_name.style.borderColor="#ff0000";
                          NPI.style.borderColor="#ff0000";
 
                          $("#existing").show();
                        }
                        //$('#modifier_1').val(myjson.modifier_1);
                        //$('#modifier_2').val(myjson.modifier_2);
                    
                 
                });
            }
        </script>
    </head>
    <body>
        <a href="<?php echo $this->baseUrl ?>" target="_top" id="relogin" style="display: none" >wwwwww</a>
        <div id="navbar">
            <p>Your Location: <a  title="">Data Management</a>
                &gt;New Referring Provider</p>
        </div>
        <div class="table-div" >
            <form method="post"  action="" onsubmit="javascript:return check();">
                <table>
                     <tr>
                        <th style= "width:15%" align="left">Provider<font color="#FF0000">*</font></th>
                        <td style= "width:25%">
                            <select class="select" name="provider_id" id="provider_id" style= "width:100%"    >
                                <option value="">Select</option>
                                <?php
                                foreach ($this->providerList as $row) {
                                    $tempnumber=$row['num']-$this->allNumRef['num'];
                                    echo "<option value='" . $row['id'] . "'>" . $row['provider_name'] ."(" . $tempnumber . ")" . "</option>";
                                }
                                ?>
                                <option value="0">ALL&nbsp;&nbsp;(<?php echo $this->allNumRef['num']; ?>)</option>
                             </select>
                        </td>
                        <th style= "width:10%" align="left" id="LastName">Last Name<font color="#FF0000">*</font></th>
                        <th style= "width:10%" align="left" id="FullName">Full Name<font color="#FF0000">*</font></th>
                        <td style= "width:20%">
                        <select  class="select"  name="import_or_new" style= "width:100%" id="import_or_new">
                            <option value='new'>New</option>
                            <option value='import'>Import</option>
                        </select>
                        <select class="select" style= "width:100%;display:none"  name="last_name" style= "" id="last_name"  onchange="javascript:auto_complete()"  >
                            <option value="">Select</option>
                                <?php
                                foreach ($this->referringproviderList as $row) {
                                    echo "<option value='" . $row['rid'] . "'>". "--". $row['street_address'] .$row['last_name'] . "</option>";
                                }
                                ?>
                        </select>
                            <input type="text"  name="add_last_name" id="add_last_name" size="55" onblur="javascript:isexisting()" style="width: 99%"/>
                        <a name="existing" id="existing"  style='color:red;display:none' >existing</a>
                        </td >
                        <th style= "width:10%" align="left" id="FirstName">First Name<font color="#FF0000">*</font></th>
                        <td style= "width:20%">
                            <input type="text"  name="add_first_name" id="add_first_name" onblur="javascript:isexisting()" size="55"  style="width: 99%"/>
                             <a name="existing" id="existing"  style='color:red;display:none' >existing</a>
                        </td>
                    </tr>
                    <tr>
                        <th align="left">NPI</th>
                        <td><input type="text" size="55" name="NPI" id="NPI" onblur="javascript:isexisting()" style="width: 99%"/> <a name="existing" id="existing"  style='color:red;display:none' >existing</a></td>
                        <th align="left">Status<font color="#FF0000">*</font></th>
                        <td>
                         <select  class="select"  name="status"  style= "width:100%" id="status">
                            <option value='active'>active</option>
                            <option value='inactive'>inactive</option>
                        </select>
                        </td>
                        <   <th align="left"  size="55">Salutation</th>
                        <td>
                           
                            <select class="select" name="salutation" id="salutation" style= "width:300px"   >
                                <option value="">Select</option>
                                <?php
                                foreach ($this->SalutationsList as $row) {
                                       
                                     echo "<option value='".$row."'>" . $row ."</option>";
                                }
                                ?>
                               
                            </select>
                        </td>
                    </tr>
<!--                    <tr>
                        <th align="left">Provider<font color="#FF0000">*</font></th>
                        <td>
                            <select class="select" name="provider_id" id="provider_id" style= "width:100%"    style= "width:92% ">
                                <option value="">Select</option>
                                
                                <option value="0">ALL</option>
                            </select>
                        </td>
                        <th></th><th></th>
                        <th></th><th></th>
                    </tr>-->
                    <tr>
                     
                        <td width="15%" colspan="6"><input type="submit" name="next" value="Save" /></td>
                     

                    </tr>
                </table>
            </form>
        </div>
    </body>
</html>