<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Accendo</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/layout.css" />
        <link rel="stylesheet" rev="stylesheet" type="text/css" media="screen, projection" href="<?php echo $this->baseUrl ?>/styles/pagenav.css" />
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery.js"></script>
         <script type="text/javascript" language="Javascript">
        $(document).ready(function(){
            
            $.post("<?php echo $this->baseUrl ?>/biller/claims/timeout/",
                function(data)
                {
                    if(data!='no'&&data!=null) {
                        var a=document.getElementById("relogin");
                        a.click(); 
                    }
                }
            ); 
//             if($("#options_id").val()==""){
//                    $("#updata").attr("disabled", true);
//                   // $("#city").val("caijun");
//                    
//                }else{
//                    $("#updata").removeAttr("disabled");
//                }
         
            $("#options_id").change(function(){
                 //$("#city").val("caijun1");
                if($("#options_id").val()==""){
                    $("#updata").attr("disabled", true);
                   // $("#city").val("caijun");
                    
                }else{
                    $("#updata").removeAttr("disabled");
                }
            });
                                

        });
        </script>
        <script type="text/javascript" language="Javascript" >
            function auto_complete()
            {
                var provider_id=$("#provider_id").val();
              
                //$("#updata").attr("disabled", true);
                
                $.post("<?php echo $this->baseUrl ?>/biller/data/providerinfo/",{provider_id:provider_id},
                function(data){
                    var myjson='';
                    eval("myjson=" + data + ";");
                    $("#tags_checkbox").css("display","none");
                    $("#tags_input").css("display","none");
                    document.getElementById("tags_select").innerHTML="";
                    document.getElementById("addmark").innerHTML="";
                    $("#tags_select").append("<option value='-1'>Select</option>");
                    if(myjson.id!=null)
                    $("#provider_id").val(myjson.id);
                    $("#fax_number").val(myjson.fax_number);
                    $("#billingcompany_id").val(myjson.billingcompany_id);
          
                    $("#options_id").val(myjson.options_id);
                     if(myjson.options_id==""){
                         $("#updata").attr("disabled", true);
                     }else{
                         $("#updata").removeAttr("disabled");
                     }
                    $("#street_address").val(myjson.street_address);
                    $("#zip").val(myjson.zip);
                    $("#state").val(myjson.state);
                    $("#city").val(myjson.city);
                    $("#id1").val(myjson.id1);
                    $("#id2").val(myjson.id2);
                    $("#taxonomy_code").val(myjson.taxonomy_code);
                    $("#phone_number").val(myjson.phone_number);
                    $("#secondary_phone_number").val(myjson.secondary_phone_number);
                    $("#email_address").val(myjson.email_address);
                    $("#tax_ID_number").val(myjson.tax_ID_number);
                    $("#billing_provider_name").val(myjson.billing_provider_name);
                    $("#billing_provider_NPI").val(myjson.billing_provider_NPI);
                    $("#billing_street_address").val(myjson.billing_street_address);
                    $("#billing_city").val(myjson.billing_city);
                    $("#billing_state").val(myjson.billing_state);
                    $("#billing_zip").val(myjson.billing_zip);
                    $("#billing_email").val(myjson.billing_email);
                    $("#billing_phone_number").val(myjson.billing_phone_number);
                    $("#billing_fax").val(myjson.billing_fax);
                    $("#notes").val(myjson.notes);
                    $("#short_name").val(myjson.short_name);
                    if((myjson.tags_in_billingcompany!=null)){
                        for(i=0;i<myjson.tags_in_billingcompany.length;i++){
                            $("#tags_select").append("<option value='" + myjson.tag_names[i] + "'>" + myjson.tag_names[i] + "</option>");
                            $("#tags_select").append("<input type='text' style='display:none' id='" + myjson.tags_in_billingcompany[i]['tag_name'] + "_type' value='"+ myjson.tags_in_billingcompany[i]['tag_type']+"'>");
                            $("#addmark").append("<input type='text' name='"+ myjson.tags_in_billingcompany[i]['tag_name']+ "' id='" + myjson.tags_in_billingcompany[i]['tag_name'] + "'>");
                        }
                    }
                    /* ZW to get around Provider Document problem
                    if(myjson.tags!=null){
                        for(i=0;i<myjson.tags.length;i++){
                            $("#"+myjson.tags[i]['tag_name']).val(myjson.tags[i]['tag_type']);
                        }
                    }
                    */
                    
                    $("#payer_id option").remove();
                    $("#payer_id").append("<option value=''>select</option>");
                    for(var i=0;i<myjson.innetworkpayersList.length;i++){
                        $("#payer_id").append("<option value='"+
                            myjson.innetworkpayersList[i]['insurance_id']+
                            "'>"+myjson.innetworkpayersList[i]['insurance_display']+
                            "</option>");
                    }
                    $(".doc_line").remove();
                    var i =0;
                    for(i=0;i<myjson.provider_doc_list.length;i++)
                    {   
                        if (i%2 == 0){
                            $("#doc_table").append("<tr class='doc_line' id='provider_doc_" + i + "' style = 'background:#FF0000'>" +
                                    "<td width='25%' style='text-align: center' >" + "<a href = \"/accendo/public/" + myjson.provider_doc_list[i]['url'] + "\" target = \" _blank \">" + myjson.provider_doc_list[i]['date'] + "</a></td>" +
                                    "<td width='25%' style='text-align: center'>" + myjson.provider_doc_list[i]['desc'] + "</td>" +
                                    "<td width='25%' style='text-align: center'>" + myjson.provider_doc_list[i]['user'] + "</td>" +
                                    "<td width='25%' style='text-align: center'><input id = " + myjson.provider_doc_list[i]['url'] + " style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this" + "," + i + ")\">" + "</input></td>" +
                                    "</tr>");
                        }else{
                            $("#doc_table").append("<tr class='doc_line' id='provider_doc_" + i + "' style = 'background:#FF0000'>" +
                                    "<td width='25%' style='background:#eeeeee;text-align: center' >" + "<a href = \"/accendo/public/" + myjson.provider_doc_list[i]['url'] + "\" target = \" _blank \">" + myjson.provider_doc_list[i]['date'] + "</a></td>" +
                                    "<td width='25%' style='background:#eeeeee;text-align: center'>" + myjson.provider_doc_list[i]['desc'] + "</td>" +
                                    "<td width='25%' style='background:#eeeeee;text-align: center'>" + myjson.provider_doc_list[i]['user'] + "</td>" +
                                    "<td width='25%' style='background:#eeeeee;text-align: center'><input id = " + myjson.provider_doc_list[i]['url'] + " style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this" + "," + i + ")\">" + "</input></td>" +
                                    "</tr>");
                        }
                    }
                    if (i%2 == 0){
                            $("#doc_table").append("<tr class='doc_line'>"+
                                    "<td width='25%' style='text-align: center' >" + "<input name=\"uploadedfil\" type=\"file\" id=\"uploadedfil\" /></td>" +
                                    "<td width = '25%' style='text-align: center' id = \"desc\"><input type=\"text\" name=\"desc\"  id=\"desc\" ></input></td>" +
                                    "<td width='25%' style='text-align: center'>" + myjson.user_name + "</td>"+
                                    "<td width='25%' style='text-align: center'><input id=\"upload\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"submit\" name=\"submit\" value=\"UPLOAD\"></input></td>" +
                            "</tr>");
                    }else{
                            $("#doc_table").append("<tr class='doc_line'>"+
                                    "<td width='25%' style='background:#eeeeee;text-align: center' >" + "<input name=\"uploadedfil\" type=\"file\" id=\"uploadedfil\" /></td>" +
                                    "<td width = '25%' style='background:#eeeeee;text-align: center' id = \"desc\"><input type=\"text\" name=\"desc\"  id=\"desc\" ></input></td>" +
                                    "<td width='25%' style='background:#eeeeee;text-align: center'>" + myjson.user_name + "</td>"+
                                    "<td width='25%' style='background:#eeeeee;text-align: center'><input id=\"upload\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"submit\" name=\"submit\" value=\"UPLOAD\"></input></td>" +
                            "</tr>");
                    }
                });
                    $("#rates").val('');
                    $("#insurance_id").val('');
                   
            }
        </script>
        <script type="text/javascript" language="javascript">
            function onDelete(id,num)
            {
                var r=confirm("The selected document will be permenantly deleted from Accendo, please confirm");
                var url = id.id;
                var sele = "#provider_doc_" + num;
                if (r == true)
                {
                    $.post("<?php echo $this->baseUrl ?>/biller/data/deletebillingdocs/",{url:url,type:'provider'},
                    function(data){
                        var answer='' ;
                        eval("answer=" + data + ";");
                        //alert("abc"+answer.result);
                        if(answer.result=="true"){
                            $(sele).remove();
                        }else
                        {
                            alert("Unalbe to delete");
                        }
                    });
                }
                else
                {
                    //alert("No Doc Exsit!");
                }
                //$(sele).remove();
                //$.post("<?php echo $this->baseUrl ?>/biller/claims/deletedocs/",{url:url},function(data){});
            }
        </script>
        <script type="text/javascript" language="Javascript" >
            function rate()
            {
                var provider_id=$("#provider_id").val();
                var payer_id=$("#payer_id").val();
                if(payer_id!='')
                {
                    $.post("<?php echo $this->baseUrl ?>/biller/data/rates/",{provider_id:provider_id,payer_id:payer_id},
                    function(data){

                        var myjson='';
                        eval("myjson=" + data + ";");
                        $("#rates").val(myjson.rates);
                        $("#insurance_id").val('');
                    });
                }
                else
                {
                    $("#rates").val('');
                }
            }

            function defaultrate()
            {
                var insurance_id = $("#insurance_id").val();
                var provider_id = $("#provider_id").val();
                if(insurance_id != '' && provider_id !='')
                {
                    $.post("<?php echo $this->baseUrl ?>/biller/data/defaultrates/",{insurance_id:insurance_id,provider_id:provider_id},
                    function(data){
                        var myjson='';
                        eval("myjson=" + data + ";");
                        $("#rates").val(myjson.rates);
                        $("#payer_id").val("");
                    });
                }
                else
                {
                  $("#rates").val('');
                }
                $("#payer_id").val("");
            }
        </script>
                <script type="text/javascript" language="javascript" >
                function showoptionfield(){
//                    alert("start");
                    var option = $("#tags_select").val();
//                    alert(option);
                    var type_id = "#"+option+"_type";
//                    alert(type_id);
                    var type = $(type_id).val();
//                    alert(type);
                    var option_value = $("#"+option).val();
                    if(type == 'binary'){
//                      alert("a checkbox");
//                      alert(option_value);
                      $("#tags_input").css("display","none");
                      $("#tags_checkbox").css("display","");
                      if(option_value == "yes"){
//                          alert(option_value);
                         document.getElementById("tags_checkbox").checked = true;
                      }else{
//                         alert(option_value);
                         document.getElementById("tags_checkbox").checked = false;
                      }
                     }else if(type == 'other'){
//                      alert("an input field");
//                      alert(option_value);
                      $("#tags_checkbox").css("display","none");
                      $("#tags_input").css("display","");
                      $("#tags_input").val(option_value);
                     }         
                     if(option == "-1"){
                      $("#tags_checkbox").css("display","none");
                      $("#tags_input").css("display","none");
                     }
                }
            </script>
        <script type="text/javascript" language="javascript" >
                function setvalue(type){
                    var option = $("#tags_select").val();
                    if(type == "checkbox"){
//                        alert("should be checkbox");
//                        var value = $("#tags_checkbox").val();
//                        alert(value);
                        if(document.getElementById("tags_checkbox").checked){
                            $("#"+option).val("yes");
//                            alert($("#"+option).val());
                        }else{
                            $("#"+option).val("no");
//                            alert($("#"+option).val());
                        }
//                        alert($("#"+option).val());
                    }else if(type == "input"){
//                        alert("should be inputfield");
                        var value = $("#tags_input").val();
//                        alert(value);
                        $("#"+option).val(value);  
//                        alert($("#"+option).val());
                    }
                }
            </script>
    </head>
    <body>
        <a href="<?php echo $this->baseUrl ?>" target="_top" id="relogin" style="display: none" >wwwwww</a>
        <div id="navbar">
            <p>Your Location: <a title="">Data Management</a> &gt; Provider</p>
        </div>
        <div class="table-div" >
            <form enctype="multipart/form-data" method="post"  action="" >
                <table>
                    <tr>
                        <th align="center" colspan="6" style="background:#eeeeee">
                            <p align="center"><b>Provider Information</b></p>
                        </th>
                    </tr>
                    <tr >
                        <th align="left">Provider Name</th>
                        <td>
                            <select class="select" name="provider_id" id="provider_id" onchange="javascript:auto_complete()" style= "width:100% ">
                                <option value="">Select</option>
                                <?php
                                foreach ($this->providerList as $row) {
                                    echo "<option value='" . $row->id . "'>" . $row->provider_name . "</option>";
                                }
                                ?>
                            </select>
                        </td>
<!--                        <th align="left" style="display: none">Campany Name</th>-->
<!--                        <td>
                            <select class="select" name="billingcompany_id" id="billingcompany_id" style= "width:100%;display: none " disabled="true">
                                <option value="">Select</option>
                                <?php
                                foreach ($this->billingcompanyList as $row) {
                                    echo "<option value='" . $row->id . "'>" . $row->billingcompany_name . "</option>";
                                }
                                ?>
                            </select>
                        </td>-->
                        <th align="left">Option Name</th>
                        <td>
                            <select class="select" name="options_id" id="options_id" style= "width:100% ">
                                <option value="">Select</option>
                                <?php
                                foreach ($this->optionsList as $row) {
                                    echo "<option value='" . $row->id . "'>" . $row->option_name . "</option>";
                                }
                                ?>
                            </select>
                        </td>
                        <th align="left">Phone Number</th><td><input type="text" size="55" name="phone_number" id="phone_number" /></td>
                    </tr>
                    <tr>
                        
                        <th align="left">Second Phone Number</th><td><input type="text" size="55" name="secondary_phone_number" id="secondary_phone_number" /></td>
                        <th  align="left">Fax Number</th><td><input type="text" size="55" name="fax_number" id="fax_number" /></td>
                        <th align="left">Email Address</th><td><input type="text" size="55" name="email_address" id="email_address" /></td>
                    </tr>
                    <tr>
                        
                        <th align="left">Tax ID Number</th><td><input type="text" size="55" name="tax_ID_number" id="tax_ID_number" /></td>
                        <th align="left">Street Address</th><td><input size="55" type="text" name="street_address" id="street_address"/></td>
                        <th  align="left">City</th><td><input type="text" size="55" name="city" id="city" /></td>
                    </tr>
                    <tr>
                        
                        <th align="left">State</th><td><input type="text" size="55" name="state" id="state" /></td>
                        <th align="left">Zip</th><td><input type="text" size="55" name="zip" id="zip" /></td>
                        <th align="left">Short Name</th><td><input type="text" size="55" name="short_name" id="short_name" /></td> 
                    </tr>
                    <tr>
                        
                        <th align="left">ID1</th><td><input type="text" size="55" name="id1" id="id1" /></td>
                        <th align="left">ID2</th><td><input type="text" size="55" name="id2" id="id2" /></td>
                        <th align="left">Taxonomy Code</th><td><input type="text" size="55" name="taxonomy_code" id="taxonomy_code" /></td> 
                    </tr>
                    <tr>
                        <th align="center" colspan="6" style="background:#eeeeee">
                            <p align="center"><b>Billing Provider Information</b></p>
                        </th>
                    </tr>
                    <tr>
                        <th align="left">Provider Name</th><td><input type="text" size="55" name="billing_provider_name" id="billing_provider_name" /></td>
                        <th  align="left">NPI</th><td><input type="text" size="55" name="billing_provider_NPI" id="billing_provider_NPI" /></td>
                        <th align="left">Street Address</th><td><input type="text" size="55" name="billing_street_address" id="billing_street_address" /></td>
                    </tr>
                    <tr>
                        <th  align="left">City</th><td><input type="text" size="55" name="billing_city" id="billing_city" /></td>
                        <th align="left">State</th><td><input type="text" size="55" name="billing_state" id="billing_state" /></td>
                        <th align="left">Zip</th><td><input type="text" size="55" name="billing_zip" id="billing_zip" /></td>
                    </tr>
                    <tr>
                        <th align="left">Phone Number</th><td><input type="text" size="55" name="billing_phone_number" id="billing_phone_number" /></td>
                        <th  align="left">Fax</th><td><input type="text" size="55" name="billing_fax" id="billing_fax" /></td>
                        <th align="left">Email Address</th><td><input type="text" size="55" name="billing_email" id="billing_email" /></td>
                    </tr>
                    <tr>
                        <th align="left" style="background:#eeeeee">Insurance</th>
                        <td>
                            <select class="select" name="insurance_id" id="insurance_id"  onchange="javascript:defaultrate()"  style= "width:100% ">
                                <option value="">Select</option>
                                <?php
                                foreach ($this->insuranceList as $row) {
                                    echo "<option value='" . $row['id'] . "'>" . $row['insurance_display'] . "</option>";
                                }
                                ?>
                            </select>
                        </td>
                        <th align="left" style="background:#eeeeee">Innetwork Payers</th>
                        <td>
                            <select class="select" name="payer_id" id="payer_id"  onchange="javascript:rate()" style= "width:100% ">
                                <option value="">Select</option>
                                <?php
                                foreach ($this->payerList as $row) {
                                    echo "<option value='" . $row['id'] . "'>" . $row['insurance_name'] . "</option>";
                                }
                                ?>
                            </select>
                        </td>
                        <th align="left" style="background:#eeeeee">Rates</th><td><input type="text" size="55" name="rates" id="rates" /></td>
                    </tr>
                    <tr>
                        <th align="left">Tags</th><td>
                            <!--<input type="text" name="tags" id="tags" size="38"  />-->
                            
                            <select class="select" name="tags_select" id="tags_select"  style="width: 49%" onchange="javascript:showoptionfield();" >
                         
                            <option value="-1">Select</option>
                            </select>
                            <input type ="checkbox"  style="display:none" name="tags_checkbox" id="tags_checkbox" onchange="javascript:setvalue('checkbox');">
                            <input type ="text"  style="display:none" name="tags_input" id="tags_input" size="24" onchange="javascript:setvalue('input');">
                        </td>
                        
                    </tr>
                     <tr>
                     <th></th><td style="display:none">
                         <input type ="text" name="addmark" id="addmark">
                   
                         </td>
                     </tr>
                    <tr>
                        <th>Notes</th><td colspan="5" ><textarea rows="4" style= "width:100%" name="notes" id="notes" ></textarea></td>
                    </tr>
                    <tr>
                        <td width="15%"><input type="submit" name="submit" value="Update" id="updata" /></td>
                        <td width="15%"><input type="submit" name="submit" value="Delete" /></td>
                        <td width="15%"><input type="submit" name="submit" value="New" /></td>
                        <td width="15%"><input type="submit" name="submit" value="Add Payer" /></td>
                        <td width="15%"><input type="submit" name="submit" value="Delete Payer" /></td>
                        <td colspan="1" ></td>
                    </tr>
                </table>
                <br></br>
                <br></br>  
                <table id="doc_table">
                    <tr>
                        <th colspan="4"><p  style="text-align: center;font-size: 16px;">Documents</p></th>
                    </tr>
                    <tr>
                        <th width="25%" style="background:#eeeeee;text-align: center">Data and Time</th>
                        <th width="25%" style="background:#eeeeee;text-align: center">Description</th>
                        <th width="25%" style="background:#eeeeee;text-align: center">User</th>
                        <th width="25%" style="background:#eeeeee;text-align: center"></th>
                    </tr>
                    
                </table>
            </form>
        </div>
    </body>
</html>