<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Accendo</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/layout.css" />
        <link href="<?php echo $this->baseUrl ?>/styles/bootstrap.min.css" rel="stylesheet" />
        <link rel="stylesheet" rev="stylesheet" type="text/css" media="screen, projection" href="<?php echo $this->baseUrl ?>/styles/pagenav.css" />
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery.js"></script>
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery-1.11.2.min.js"></script>
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/bootstrap.min.js"></script>
        
        <script type="text/javascript" language="Javascript" >
        $(document).ready(function(){
            $.post("<?php echo $this->baseUrl ?>/biller/claims/timeout/",
                function(data)
                {
                    if(data!='no'&&data!=null) {
                        var a=document.getElementById("relogin");
                        a.click(); 
                    }
                }
            );
            
            $.post("<?php echo $this->baseUrl ?>/biller/data/referringlist/", {provider_id: 0},
                        function (data) {});
                        
            $.get("<?php echo $this->baseUrl ?>/biller/data/selectprovider/",function(data){
                                var myjson='';
                                    eval("myjson=" + data + ";");
                                    $("#provider_id").val(myjson.provider_id);
                                     $("#provider_id").change();  
                                }

                            );
            $("#provider_id").change(function(){
            var provider_id = $("#provider_id").val();
            $(".doc_line").remove();
             if(provider_id == 0 ) {
                    $('#del_provider_id_span').show();
                }
                else {
                    $('#del_provider_id_span').hide();
                }
             $('#del_provider_id').val(provider_id);
            if(provider_id){
                $("#id option").remove();
                $("#id").append("<option value=\"\">Select</option>");
                $.post("<?php echo $this->baseUrl ?>/biller/data/referringlist/",{provider_id:provider_id},function(data){
                    var myjson='';
                    eval("myjson=" + data + ";");
                    for(var i = 0;i<myjson.referringproviderList.length;i++){
                    $("#id").append("<option value='"+myjson.referringproviderList[i]['id']+"'>"+myjson.referringproviderList[i]['last_name']
                        +", "+myjson.referringproviderList[i]['first_name']+"</option>")
                    }
                    
                });
            }
        });
        }
    );
        </script>
        
        
        <script type="text/javascript" language="Javascript" >
            function auto_complete()
            {
                var id=$("#id").val();
                var provider_id=$("#provider_id").val();
                if(id.length!=0)
                {
                    $.post("<?php echo $this->baseUrl ?>/biller/data/referringproviderinfo/",{id:id,provider_id:provider_id},
                    function(data){
                        var myjson='';
                        eval("myjson=" + data + ";");
//                        $("#provider_id").val(myjson.provider_id);
                        $("#NPI").val(myjson.NPI);
                        $("#salutation").val(myjson.salutation);
                        if(myjson.status!=0)
                        $("#status").val(myjson.status);
                        else
                        {
                            $("#status").val("");
                        }
                        $(".doc_line").remove();
                        var i=0;
                        for(i=0;i<myjson.rprovider_doc_list.length;i++)
                        {   
                            if (i%2 == 0){
                                $("#doc_table").append("<tr class='doc_line' id='rprovider_doc_" + i + "' style = 'background:#FF0000'>" +
                                        "<td width='25%' style='text-align: center' >" + "<a href = \"/accendo/public/" + myjson.rprovider_doc_list[i]['url'] + "\" target = \" _blank \">" + myjson.rprovider_doc_list[i]['date'] + "</a></td>" +
                                        "<td width='25%' style='text-align: center'>" + myjson.rprovider_doc_list[i]['desc'] + "</td>" +
                                        "<td width='25%' style='text-align: center'>" + myjson.rprovider_doc_list[i]['user'] + "</td>" +
                                        "<td width='25%' style='text-align: center'><input id = " + myjson.rprovider_doc_list[i]['url'] + " style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this" + "," + i + ")\">" + "</input></td>" +
                                        "</tr>");
                            }else{
                                $("#doc_table").append("<tr class='doc_line' id='rprovider_doc_" + i + "' style = 'background:#FF0000'>" +
                                        "<td width='25%' style='background:#eeeeee;text-align: center' >" + "<a href = \"/accendo/public/" + myjson.rprovider_doc_list[i]['url'] + "\" target = \" _blank \">" + myjson.rprovider_doc_list[i]['date'] + "</a></td>" +
                                        "<td width='25%' style='background:#eeeeee;text-align: center'>" + myjson.rprovider_doc_list[i]['desc'] + "</td>" +
                                        "<td width='25%' style='background:#eeeeee;text-align: center'>" + myjson.rprovider_doc_list[i]['user'] + "</td>" +
                                        "<td width='25%' style='background:#eeeeee;text-align: center'><input id = " + myjson.rprovider_doc_list[i]['url'] + " style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this" + "," + i + ")\">" + "</input></td>" +
                                        "</tr>");
                            }
                        }
                        if (i%2 == 0){
                            $("#doc_table").append("<tr class='doc_line'>"+
                                    "<td width='25%' style='text-align: center' >" + "<input name=\"uploadedfil\" type=\"file\" id=\"uploadedfil\" /></td>" +
                                    "<td width = '25%' style='text-align: center' id = \"desc\"><input type=\"text\" name=\"desc\"  id=\"desc\" ></input></td>" +
                                    "<td width='25%' style='text-align: center'>" + myjson.user_name + "</td>"+
                                    "<td width='25%' style='text-align: center'><input id=\"upload\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"submit\" name=\"submit\" value=\"UPLOAD\"></input></td>" +
                            "</tr>");
                        }else{
                            $("#doc_table").append("<tr class='doc_line'>"+
                                    "<td width='25%' style='background:#eeeeee;text-align: center' >" + "<input name=\"uploadedfil\" type=\"file\" id=\"uploadedfil\" /></td>" +
                                    "<td width = '25%' style='background:#eeeeee;text-align: center' id = \"desc\"><input type=\"text\" name=\"desc\"  id=\"desc\" ></input></td>" +
                                    "<td width='25%' style='background:#eeeeee;text-align: center'>" + myjson.user_name + "</td>"+
                                    "<td width='25%' style='background:#eeeeee;text-align: center'><input id=\"upload\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"submit\" name=\"submit\" value=\"UPLOAD\"></input></td>" +
                            "</tr>");
                        }
                        
                    });
                }
                else
                {
                    $("#NPI").val('');
                    $("#status").val('');
                    $("#salutation").val('');
                }
            }

        </script>
        <script type="text/javascript" language="javascript">
            function onDelete(id,num)
            {
                var provider_id = $("#provider_id").val();
                var r=confirm("The selected document will be permenantly deleted from Accendo, please confirm");
                var url = id.id;
                var sele = "#rprovider_doc_" + num;
                
                if (r == true)
                {
                    if(provider_id != '0'){
                        $.post("<?php echo $this->baseUrl ?>/biller/data/deletebillingdocs/",{url:url,type:"refer"},
                        function(data){
                            var answer='' ;
                            eval("answer=" + data + ";");
                            //alert("abc"+answer.result);
                            if(answer.result=="true"){
                                $(sele).remove();
                            }else
                            {
                                alert("Unalbe to delete");
                            }
                        });
                    }else{
                        $.post("<?php echo $this->baseUrl ?>/biller/data/deletereferproviderdocall/",{url:url},
                        function(data){
                            var answer='' ;
                            eval("answer=" + data + ";");
                            //alert("abc"+answer.result);
                            if(answer.result=="true"){
                                $(sele).remove();
                            }else
                            {
                                alert("Unalbe to delete");
                            }
                        });
                    }
                }
                else
                {
                    //alert("No Doc Exsit!");
                }
                //$(sele).remove();
                //$.post("<?php echo $this->baseUrl ?>/biller/claims/deletedocs/",{url:url},function(data){});
            }
        </script>
    </head>
    <body>
        <a href="<?php echo $this->baseUrl ?>" target="_top" id="relogin" style="display: none" >wwwwww</a>
        <div id="navbar">
            <p>Your Location: <a title="">Data Management</a> &gt; Referring Provider</p>
        </div>
        <div class="table-div" >
            <form enctype="multipart/form-data" method="post"  action="" onsubmit="javascript:return check();">
                <table>
                    <tr >
                         <th align="left"  size="55">Provider</th>
                        <td>
                           
                            <select class="select" name="provider_id" id="provider_id" style= "width:300px"   >
                                <option value="">Select</option>
                                <?php
                                foreach ($this->providerList as $row) {
                                       $tempnumber=$row['num']-$this->allNumRef['num'];
                                     echo "<option value='" . $row['id'] . "'>" . $row['provider_name'] . "--". $row['street_address'] ."(" . $tempnumber . ")" ."</option>";
                                }
                                ?>
                               <option value="0">ALL&nbsp;&nbsp;(<?php echo ($this->allNumRef['num']); ?>)</option>
                            </select>
                        </td>
                        <th align="left"  size="55">Referring Provider</th>
                        <td>
                            <select class="select" name="id" id="id" style= "width:300px" onchange="javascript:auto_complete()" >
                                <option value="">Select</option>
                            </select>
                        </td>
                       
                        <th  align="left"  size="55">NPI</th><td><input type="text" name="NPI" style= "width:300px" id="NPI" /></td>
                    </tr>
                     <tr>
                        <th align="left"  size="55">Status</th>
                        <td>
                         <select  class="select"  name="status"  style= "width:300px" id="status">
                            <option value='active'>active</option>
                            <option value='inactive'>inactive</option>
                        </select>
                        </td>
                  
                     <th align="left"  size="55">Salutation</th>
                        <td>
                           
                            <select class="select" name="salutation" id="salutation" style= "width:300px"   >
                                <option value="">Select</option>
                                <?php
                                foreach ($this->SalutationsList as $row) {
                                       
                                     echo "<option value='".$row."'>" . $row ."</option>";
                                }
                                ?>
                               
                            </select>
                        </td>
                       </tr>
                    <tr>
                 <td colspan="1"><input type="submit" name="submit" value="Update"/></td>
                 <td ><input type="button" name="delete" id="delete" value="Delete" onclick="deleteFac()"/></td>
                        <div class="modal fade" id="login-modal">
                            <div class="modal-dialog modal-lg">
                                 <div class="modal-content">
                                     <div class="modal-header">
                                         <button class="close" data-dismiss="modal">&times</button>
                                         <h4 style="color:red">This referringprovider can not be deleted as the claims below are stilling associated with the referringprovider !</h4>
                                     </div>
                                      <div class="modal-body">
                                           <div class="container-fluid">
                                               <div class="row">
                                                   <div class="col-md-3"><strong>Last Name</strong></div>
                                                   <div class="col-md-3"><strong>First Name</strong></div>
                                                   <div class="col-md-3"><strong>DOS</strong></div>
                                                   <div class="col-md-3"><strong>Provider</strong></div>
                                               </div>
                                               <div id="detail">

                                               </div>

                                           </div>
                                          <br>
                                          <div id="more" style="float:right">More...</div>
                                      </div>
                                      <div class="modal-footer">
                                         <button class="btn btn-default" data-dismiss="modal">
                                            Close
                                         </button>
                                      </div>
                                 </div>
                            </div>
                        </div>
                        <script>
                            function deleteFac(){
                               var status = $("#status").val();
                               //alert(status);
                               var provider_id = $("#provider_id").val();
                               //alert(provider_id);
                               var refer_id = $("#id").val();
                               //alert(refer_id);
                                var del_provider_id = $("#del_provider_id").val();
                                $.post("<?php echo $this->baseUrl ?>/biller/data/deleterefer/",{'provider_id':provider_id,'refer_id':refer_id,'status':status,'del_provider_id':del_provider_id},function(data){
                                    var myjson='';
                                    eval("myjson=" + data + ";");
                                    var flag = myjson.flag;
                                    var status = myjson.status;
                                    if(status==1){
                                        alert('you can not delete an active referringprovider');
                                    }else{
                                            if(flag==1){
                                                //alert('can not delete');
                                                var patientinfoArray = myjson.patientinfoArray;
                                                //alert(typeof(patientinfoArray));
                                                //showdetail.style.display="";

                                               
                                                $("#login-modal").modal('show');
                                                var len = patientinfoArray.length;
                                                //alert(len);
                                                if(len>10){
                                                    len = 10;
                                                }else{
                                                    $("#more").hide();
                                                }
                                                for (var i=0;i<len;i++){
                                                    //alert(patientinfoArray[i]['last_name']);
                                                    $("#detail").append("<div class=\"row\">"+"<div class=\"col-md-3\">"+patientinfoArray[i]['last_name']+"</div>"+"<div class=\"col-md-3\">"+patientinfoArray[i]['first_name']+"</div>"+"<div class=\"col-md-3\">"+patientinfoArray[i]['dos']+"</div>"+"<div class=\"col-md-3\">"+patientinfoArray[i]['providername']+"</div></div>");
        //                                            $("#detail").append("<div class=\"row\">"+"<div class=\"col-md-2\">"+patientinfoArray[i]['last_name']+"</div>"+"<div class=\"col-md-2\">"+patientinfoArray[i]['first_name']+"</div>"+"<div class=\"col-md-4\">"+patientinfoArray[i]['dos']+"</div>"+"<div class=\"col-md-4\">"+patientinfoArray[i]['providername']+"</div></div>");
                                                    //$("#detail").append("<tr><td>"+patientinfoArray[i]['last_name']+"</td><td>"+patientinfoArray[i]['first_name']+"</td><td>"+patientinfoArray[i]['dos']+"</td><td>"+patientinfoArray[i]['providername']+"</td></tr>");
                                                }
                                                $('#login-modal').on('hide.bs.modal',function(){
                                                    $("#detail").children().remove(); //删除所有子元素
                                                });
                                            }else{
                                               alert('delete successfully');
                                               window.location.href="<?php echo $this->baseUrl ?>/biller/data/referringprovider"; 
                                            }
                                    }
                           

                                });
                            }
                        </script>
                        <td colspan="1">
                             <span id='del_provider_id_span' style='display:none'>&nbsp;from&nbsp;
                                <select class="select"  name="del_provider_id"  id="del_provider_id" >
                                    <?php
                                    foreach ($this->providerList as $row) {
                                        echo "<option value='" . $row['id'] . "'>" . $row['provider_name'] . "</option>";
                                    }
                                    ?>
                                    
                                    <option value="0">ALL</option>
                                </select>
                            </span>
                            
                        </td>
                        <td colspan="3"><input type="submit" name="submit" value="New"/></td>
                    </tr>
                </table>
                <br></br>
                <br></br>  
                <table id="doc_table">
                    <tr>
                        <th colspan="4"><p  style="text-align: center;font-size: 16px;">Documents</p></th>
                    </tr>
                    <tr>
                        <th width="25%" style="background:#eeeeee;text-align: center">Data and Time</th>
                        <th width="25%" style="background:#eeeeee;text-align: center">Description</th>
                        <th width="25%" style="background:#eeeeee;text-align: center">User</th>
                        <th width="25%" style="background:#eeeeee;text-align: center"></th>
                    </tr>
                </table>
            </form>
        </div>
    </body> 
</html>