<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Accendo</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/layout.css" />
        <link rel="stylesheet" rev="stylesheet" type="text/css" media="screen, projection" href="<?php echo $this->baseUrl ?>/styles/pagenav.css" />
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery.js"></script>
        <script type="text/javascript" language="Javascript">
        $(document).ready(function(){
            $.post("<?php echo $this->baseUrl ?>/biller/claims/timeout/",
                function(data)
                {
                    if(data!='no'&&data!=null) {
                        var a=document.getElementById("relogin");
                        a.click(); 
                    }
                }
            );
        })
        </script>
        <script type="text/javascript" language="Javascript">
            document.onkeydown=keyListener;
            
            function keyListener(e){    
                e = e ? e : event;   
                if(e.keyCode == 13){
                    RefreshRows();    
                }    
            }
   
        </script>
        
        
        <script type="text/javascript" language="Javascript" >
            function getVal(){
                var table = $("#table1");
                var patient_ids=new Array();
                var statement_ids=new Array();
                var tableTrElement = $("#table1 tr");
                var td1 = $("#table1 td");
                for(var i=0;i<tableTrElement.length-1;i++)
                {
                    if(td1[i*8].firstChild.checked)
                    {
                        var patient_id=td1[i*8+7].innerHTML;
                        var statement_id=td1[i*8+7].innerHTML;
                         patient_ids.push(patient_id);
                         statement_ids.push(statement_id);
                    }
                }
                $("#patient_id").val(patient_ids[0] );
                $("#statement_id").val(statement_ids[0]);
              
            }
        </script>
        <script type="text/javascript">
            function RefreshRows(){
                $("#tbody1").empty();
                var MSN=$("#MSN").val();
                
                $.post("<?php echo $this->baseUrl ?>/biller/data/statementsearch/",{MSN:MSN},
                function(data){
                    var myjson='';
                    $("#error_no").show();
                    $("#error_not_can").hide();
                    //$("#error_not_can").show();
                    eval("myjson=" + data + ";");
                    var tableTrElement = $("#table1 tr");//得到表格所有行
                    var len = tableTrElement.length;//得到总行数
                    var tableElement = $("#table1");//得到表格对象
                     var length=myjson.length;
                      
                    var str="";
                    if(data!=null){
                         $("#error_no").hide();
                         var patients=new Array();;
                        for(var i=0;i<myjson.length;i++){
                         
                                //;color:red
                            str =str+ '<tr id='+i+'><td><input type="checkbox" /></td>'
                                + '<td id="type" style=\"font-weight:normal\" >' + myjson[i]["type"] + '</td>'
                                + '<td id="date" style=\"font-weight:normal\">' + myjson[i]["date"] + '</td>'
                                + '<td id="trigger" style=\"font-weight:normal\">' + myjson[i]["trigger"] + '</td>'
                                + '<td id="remark" style=\"font-weight:normal\">' +  myjson[i]["remark"] + '</td>'
                                + '<td id="DOS" style=\"font-weight:normal\">' + myjson[i]["DOS"] + '</td>'
    //                             + '<td id="SSN" style=\"font-weight:normal\">' + myjson[i]["SSN"] + '</td>'
                               
                                + '<td id="code" style=\"font-weight:normal\">' + myjson[i]["code"] + '</td>'
                                + '<td id="statement_id" style=\"font-weight:normal\">' + myjson[i]["statement_id"] + '</td>'
                            
                                + '</tr>';
                                
                                patients.push(myjson[i]["patient_id"]);
                      
                     }
                       
                        $('#patient_id').val(patients);
                        length=i;
                        tableElement.append(str);
                    }
                    
                     
//                        if(myjson[0]["ilast_name"]==null){
//                             $("#error_not_can").hide();
//                        }
                        
//                    else{
//                    
//                            $("#error_no").show();
//                    }
                });
            }
            function DeleteRows(){
                 var truthBeTold=false;
                 getVal();
             
                 var statement_id=$("#statement_id").val();
                 if(statement_id[0]!=null){
                     var truthBeTold =confirm("The selected statement will be permanently deleted from this patient, please confirm");
                 }else{
                     alert("No insured/insurance checked");
                 }
               if(truthBeTold){
                   
                   
                    $.post("<?php echo $this->baseUrl ?>/biller/data/statementdelete/",{statement_id:statement_id},
                    function(){
                        var tableTrElement = $("#table1 tr");
                        var td1 = $("#table1 td");
                        for(var i=0;i<tableTrElement.length-1;i++)
                        {
                            if(td1[i*8].firstChild.checked)
                            {
                                $("tr[id=\'"+i+"\']").remove();
                                break;
                            }
                        }
                    });
                  }
            }
        </script>
    </head>
    <body>
        <a href="<?php echo $this->baseUrl ?>" target="_top" id="relogin" style="display: none" >wwwwww</a>
        <div id="navbar">
            <p>Your Location: <a  title=""> Data Management</a> &gt; Delete Patient Statement</p>
        </div>
        <div class="table-div">
           

            <form action="" method="post" name="Service">
                <table>
                    <tr>
                        <td>
                            <table>
                                <th  style= "width:30% ">MRN</th><td style= "width:45% "><input type="text" name="MSN" id="MSN" style= "width:98% "/></td> 
                                <th style= "width:20% "></th>
                                
                                <td><input type="button" name="search" value="Search"  onclick="javascript:RefreshRows()" /></td>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        
                    </tr>
                    <tr>
                        
                        <td style="align:center" ><a name="error_no" id="error_no"  style='text-align: center;color:red;display:none' >No patient matches this MRN</a></td>
                    </tr>
                    <tr>
                        <td style="align:center" ><a name="error_not_can" id="error_not_can"  style='text-align: center;color:red;display:none' >No insurance can be deleted as every patient insurance is used by at least one claim by this patient</a></td>
                    </tr>
                    <tr>
                        <td width="100%">
                            <table id="table1">
                                <thead>
                                    
                                    <th width="4%" style="text-align: center"><b>Choose</b></th>
                                    <th width="11%" style="text-align: center"><b>Type</b></th>
<!--                                    <th width="11%" style="text-align: center"><b>First Name</b></th>-->
                                    <th width="14%" style="text-align: center"><b>Statement Date</b></th>
                                    <th width="14%" style="text-align: center"><b>Trigger</b></th>
                                    <th width="14%" style="text-align: center"><b> Remark</b></th>
                                    <th width="14%" style="text-align: center"><b>DOS</b></th>
                                    <th width="14%" style="text-align: center"><b>Anesthesia Code</b></th>
                                    
                                    <th width="14%" style="text-align: center"><b>Statement ID</b></th>
                                    
                                  
                                </thead>
                                <tbody id="tbody1">
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    
                    <tr>
                        <td>
                            <table>
                                <tr>
                                    <td width="15%"><input type="button" name="delete" value="Delete" onclick="javascript:DeleteRows()" /></td>
                                  
                                    <!--td><input type="text" name="patient_id"  id="patient_id" size="20" /> </td-->   
                                     <td><input type="text" name="statement_id"  id="statement_id" size="20" /> </td> 
                                </tr>
                            </table>
                    </tr>
                </table>
            </form>

        </div>
    </body>
</html>