<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title> Accendo</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/layout.css" />
        <link href="<?php echo $this->baseUrl ?>/styles/bootstrap.min.css" rel="stylesheet" />
        <link rel="stylesheet" rev="stylesheet" type="text/css" media="screen, projection" href="<?php echo $this->baseUrl ?>/styles/pagenav.css" />
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery.js"></script>
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery-1.11.2.min.js"></script>
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/bootstrap.min.js"></script>
        <script type="text/javascript" language="Javascript">
            $(document).ready(function()
            {
                $.post("<?php echo $this->baseUrl ?>/biller/claims/timeout/",
                function(data)
                {
                    if(data!='no'&&data!=null) {
                        var a=document.getElementById("relogin");
                        a.click(); 
                    }
                }
            );
                
            $.get("<?php echo $this->baseUrl ?>/biller/data/selectprovider/",function(data){
                        var myjson='';
                            eval("myjson=" + data + ";");
                            $("#provider_id").val(myjson.provider_id);
                             $("#provider_id").change();  
                        }

                    );
            
            $("#provider_id").change(function(){
                    var provider_id = $("#provider_id").val();
            if(provider_id == 0) {
                $('#del_provider_id_span').show();
            }
            else {
                $('#del_provider_id_span').hide();
            }
            $('#del_provider_id').val(provider_id);
                    if(provider_id){       
                        $('#anesthesia_code_id').val('');
                        $('#base_unit').val('');
                        $('#description').val('');
                        $('#expected_amount').val('');
                        $('#charge').val('');
                        $('#cpt_code option').remove();
                        $('#anesthesia_code_id option').remove();
                        $('#status').val('active');//新建的 active 选项
                        $('#cpt_code').append("<option value=\"\">Select</option>");
                        $('#anesthesia_code_id').append("<option value=\"\">Select</option>");

                        $.post("<?php echo $this->baseUrl ?>/biller/data/surgerlist/",{provider_id:provider_id},
                        function(data){
                            var myjson='';
                            eval("myjson=" + data + ";");
                            for(var i = 0;i<myjson.cptcodeList.length;i++){
                                $("#cpt_code").append("<option value='"+
                                    myjson.cptcodeList[i]['id']+
                                    "'>"+myjson.cptcodeList[i]['CPT_code']+
                                    //                                        " "+myjson.diagnosiscodeList[i]['diagnosis_code']+
                                "</option>");
                            }
                            
                             for(var i = 0;i<myjson.crosswalkList.length;i++){
                                
                                $("#anesthesia_code_id").append("<option value='"+
                                    myjson.crosswalkList[i]['anesthesia_code']+
                                    "'>"+myjson.crosswalkList[i]['anesthesia_code']+
                                    //                                        " "+myjson.diagnosiscodeList[i]['diagnosis_code']+
                                "</option>");
                            }
                        });
                    }
                }
            );
                //added by pandazhao 2012/8/13
            
//                $("#provider_id1").change(function(){
//                    var provider_id = $("#provider_id1").val();
//                    if(provider_id){       
//                       
//                        $('#base_unit1').val('');
//                        $('#description1').val('');
//                        $('#anesthesia_code1 option').remove();
//                        $('#anesthesia_code1').append("<option value=\"\">Select</option>");
//                        $.post("<?php echo $this->baseUrl ?>/biller/data/anesthesianlist/",{provider_id:provider_id},
//                        function(data){
//                            var myjson='';
//                            eval("myjson=" + data + ";");
//                            for(var i = 0;i<myjson.crosswalkList.length;i++){
//                                $("#anesthesia_code1").append("<option value='"+
//                                    myjson.crosswalkList[i]['anesthesia_code']+
//                                    "'>"+myjson.crosswalkList[i]['anesthesia_code']+
//                                    //                                        " "+myjson.diagnosiscodeList[i]['diagnosis_code']+
//                                "</option>");
//                            }
//                        });
//                    }
//                }
//            );
            
            
            
//            $("#provider_id_2").change(function(){
//                    var provider_id = $("#provider_id_2").val();
//                    if(provider_id){       
//                       
////                        $('#base_unit1').val('');
//                        $('#description_2').val('');
//                        $('#anesthesia_code_2 option').remove();
//                        $('#anesthesia_code_2').append("<option value=\"\">Select</option>");
//                          $.post("<?php echo $this->baseUrl ?>/biller/data/anesthesianlist/",{provider_id:provider_id},
//                        function(data){
//                            var myjson='';
//                            eval("myjson=" + data + ";");
//                            for(var i = 0;i<myjson.cptcodeList.length;i++){
//                                $("#cpt_code_2").append("<option value='"+
//                                    myjson.cptcodeList[i]['CPT_code']+
//                                    "'>"+myjson.cptcodeList[i]['CPT_code']+
//                                    //                                        " "+myjson.diagnosiscodeList[i]['diagnosis_code']+
//                                "</option>");
//                            }
//                        });
//                    }
//                }
//            );
            
            
            
            
            
            }
        );
        </script>
        <!-- by Pandazhao-->
        <script type="text/javascript" language="Javascript" >
            function auto_complete()
            {
                var cpt_code=$("#cpt_code").val();
                var provider_id=$("#provider_id").val();
                
                $('#anesthesia_code_id').val('');
                //                        alert("if");
                //                        alert(myjson.anesthesia_code);
                $('#base_unit').val('');
                $('#description').val('');
                $('#expected_amount').val('');
                //                            alert("else");
                //                            alert(myjson.payment_expected);
                $('#charge').val('');
                $.post("<?php echo $this->baseUrl ?>/biller/data/surgeryinfo/",{cpt_code:cpt_code,provider_id:provider_id},
                function(data){
                    var myjson='';
                    eval("myjson=" + data + ";");
                   // if(myjson.anesthesia_code!=''&&myjson.anesthesia_code!=null){
                      
                        //                        alert("if");
                        //                        alert(myjson.anesthesia_code);
                        $('#base_unit').val(myjson.base_unit);
                        $('#description').val(myjson.description_cpt);
                   
                        $('#expected_amount').val(myjson.payment_expected);
                        $('#description_anesthesia').val(myjson.description_anes);
                        //                            alert("else");
                        //                            alert(myjson.payment_expected);
                        $('#charge').val(myjson.charge_amount);
                        
                   // }
                  $('#modifier_1').val(myjson.modifier_1);
                  $('#modifier_2').val(myjson.modifier_2);
                  //alert(myjson.status);
                  $("#status").val(myjson.status);
                    $('#anesthesia_code_id').val(myjson.anesthesia_code);
                });
            }
        </script>
        <script type="text/javascript" language="Javascript" >
            function auto_complete_1()
            {
                var cpt_code=$("#cpt_code").val();
                var provider_id=$("#provider_id").val();
                var anesthesia_code_id=  $('#anesthesia_code_id').val();
                
                //$('#anesthesia_code_id').val('');
                //                        alert("if");
                //                        alert(myjson.anesthesia_code);
                $('#base_unit').val('');
//                $('#description').val('');
//                $('#expected_amount').val('');
                //                            alert("else");
                //                            alert(myjson.payment_expected);
               // $('#charge').val('');
                $.post("<?php echo $this->baseUrl ?>/biller/data/surgeryinfoo/",{cpt_code:cpt_code,provider_id:provider_id,anesthesia_code_id:anesthesia_code_id},
                function(data){
                    var myjson='';
                    eval("myjson=" + data + ";");
                    //if(myjson.anesthesia_code!=''&&myjson.anesthesia_code!=null){
                      //  $('#anesthesia_code_id').val(myjson.anesthesia_code);
                        //                        alert("if");
                        //                        alert(myjson.anesthesia_code);
                        $('#base_unit').val(myjson.base_unit);
                        $('#description_anesthesia').val(myjson.description_anes);
                        //alert(myjson.status);
                        //$('#status').val(myjson.status);
                         //$('#expected_amount').val(myjson.payment_expected);
                      //  $('#description').val(myjson.description_cpt);
                        
                        //                            alert("else");
                        //                            alert(myjson.payment_expected);
                        //$('#charge').val(myjson.charge_amount);
                   // }
                 // $('#modifier_1').val(myjson.modifier_1);
                //  $('#modifier_2').val(myjson.modifier_2);
                });
            }
        </script>

<!--        <script type="text/javascript" language="Javascript" >
            function auto_complete_1()
            {
                var provider_id=$("#provider_id1").val();
         
                var anesthesia_code = $('#anesthesia_code1').val();
                //                        alert("if");
                //                        alert(myjson.anesthesia_code);
                $('#base_unit1').val('');
                $('#description1').val('');
                //                alert("wwww");
                //                            alert("else");
                //                            alert(myjson.payment_expected);
                $.post("<?php echo $this->baseUrl ?>/biller/data/anesthesiainfoo/",{anesthesia_code:anesthesia_code,provider_id:provider_id},
                function(data){
                    var myjson='';
                    eval("myjson=" + data + ";");

                    //                        $('#anesthesia_code').val(myjson.anesthesia_code);
                    //                        alert("if");
                    //                        alert(myjson.anesthesia_code);
                    $('#base_unit_1').val(myjson.base_unit);    
                    $('#description_1').val(myjson.description);
                    $('#modifier_3').val(myjson.modifier_1);
                    $('#modifier_4').val(myjson.modifier_2);
                    //                        $('#expected_amount').val(myjson.payment_expected);
                    //                        $('#description').val(myjson.description_1);
                    //                        //                            alert("else");
                    //                        //                            alert(myjson.payment_expected);
                    //                        $('#charge').val(myjson.charge_amount);
                });
            }
        </script>-->

        <script type="text/javascript" language="Javascript" >
            function auto_complete_2()
            {
                var cpt_code=$("#cpt_code_2").val();
                var provider_id=$("#provider_id_2").val();
                
                $('#anesthesia_code_2').val('');
                //                        alert("if");
                //                        alert(myjson.anesthesia_code);
//                $('#base_unit').val('');
                $('#description_2').val('');
                $('#expected_amount_2').val('');
                //                            alert("else");
                //                            alert(myjson.payment_expected);
                $('#charge_2').val('');
                $.post("<?php echo $this->baseUrl ?>/biller/data/anesthesiainfo/",{cpt_code:cpt_code_id,provider_id:provider_id},
                function(data){
                    var myjson='';
                    eval("myjson=" + data + ";");
                    if(myjson.anesthesia_code!=''&&myjson.anesthesia_code!=null){
                        $('#anesthesia_code').val(myjson.anesthesia_code);
                        //                        alert("if");
                        //                        alert(myjson.anesthesia_code);
                        $('#base_unit').val(myjson.base_unit);
                        $('#description_anesthesia').val(myjson.description);
                   
                        $('#expected_amount_2').val(myjson.payment_expected);
                        $('#description').val(myjson.description_1);
                        //                            alert("else");
                        //                            alert(myjson.payment_expected);
                        $('#charge_2').val(myjson.charge_amount);
                    }
 
                });
            }
        </script>


        <script language="javascript" type="text/javascript">
            function check()
            {
                option_name=document.getElementById("option_name").value;
                if(option_name.length==0)
                {
                    alert("Please Select a Exist Option or Create a New One!");
                    return false;
                }
            }
        </script>
    </head>

    <body>
        <a href="<?php echo $this->baseUrl ?>" target="_top" id="relogin" style="display: none" >wwwwww</a>
        <div id="navbar">
            <p>Your Location: <a  title="">Data Management</a> &gt; Surgery Code</p>
        </div>
        <div class="table-div" >
            <form action="" method="post" name="Option">
                <table>
                    <tr >
                         <th align="left" colspan="1" >Provider</th>
                        <td  colspan="1" >
                            <select class="select" name="provider_id" style= "width:100% " id="provider_id" >
                                <option value="">Select</option>
                                <?php
                             
                               
                                foreach ($this->providerList as $row) {
                                     $tempnumber=$row['num']-$this->allNumSur['num'];
                                    echo "<option value='" . $row['id'] . "'>" . $row['provider_name'] . "--". $row['street_address'] ."(" . $tempnumber . ")" ."</option>";
                                }
                                ?>
                                 <option value="0">ALL&nbsp;&nbsp;(<?php echo $this->allNumSur['num']; ?>)</option>
                            </select>
                        </td>


                        <th align="left">Surgery Code</th>
                        <td colspan="1">
                            <select class="select" name="cpt_code" id="cpt_code" onchange="javascript:auto_complete()" style= "width:100% ">
                                <option value="">Select</option>
                              
                            </select>
                        </td>
                        <th align="left">Surgerycode Description</th><td><input colspan="1" type="text" name="description" id="description" size="58"  /></td>
                    </tr>
                    <tr>
                        <th align="left">Charge</th><td><input  colspan="1" type="text" name="charge" id="charge" size="58" /> </td>
                   
                        <th align="left">Expected Amount</th><td><input  colspan="2" type="text" name="expected_amount" id="expected_amount" size="58" /></td>
                        <th align="left">Modifier1</th><td><input  colspan="2" type="text" name="modifier_1" id="modifier_1" size="58"  /></td>
                        <!--td colspan="1">
                            <select class="select" name="modifier_1" id="modifier_1" style= "width:100% ">
                                <option value="">Select</option>
                                <?php
                                foreach ($this->modifierList as $row) {
                                    echo "<option value='" . $row->modifier . "'>" . $row->modifier . "</option>";
                                }
                                ?>
                            </select>
                        </td-->
                        
<!--                        <td><input  colspan="1" type="text" name="modifier_2" id="modifier_2" /> </td>-->
                        <!--td colspan="1">
                            <select class="select" name="modifier_2" id="modifier_2" style= "width:100% ">
                                <option value="">Select</option>
                                <?php
                                foreach ($this->modifierList as $row) {
                                    echo "<option value='" . $row->modifier . "'>" . $row->modifier . "</option>";
                                }
                                ?>
                            </select>
                        </td-->
                    </tr>
                    <tr>
                        <th align="left">Modifier2</th><td><input  colspan="2" type="text" name="modifier_2" id="modifier_2" size="58" /></td>
                          <th align="left">Anesthesia Code</th><!--td >
                            <input class="select" colspan="1" type ="text" name="anesthesia_code" id="anesthesia_code" onchange="javascript:auto_complete()"/>
                        </td-->
                        <td colspan="1">
                            <select class="select" name="anesthesia_code_id" id="anesthesia_code_id" onchange="javascript:auto_complete_1()" style= "width:100% ">
                             <option value="">Select</option>
                            </select>
                        </td>
                          <th align="left">Anesthesia Description</th><td><input size="58"  colspan="1" type="text" name="description_anesthesia" id="description_anesthesia" disabled="true" style="background:white"/></td>
                         
                    </tr>
                    <tr>
                         <th align="left">Base Unit</th><td><input colspan="1" type="text" name="base_unit" id="base_unit"  disabled="true" style="background:white" size="58" /></td>
                         <th align="left">Status</th>
                         <td>
                             <select  class="select"  name="status"  style= "width:100%" id="status">
                                <option value='active'>active</option>
                                <option value='inactive'>inactive</option>
                            </select>
                         </td>
                    </tr>
                    <tr >
                        <td colspan="1"><input type="submit" name="submit" value="Update"/></td>
                        <!--<td colspan="1"><input type="submit" name="submit" value="Delete"/></td>-->
                         <td colspan="1"><input type="button" name="delete" id="delete" value="Delete" onclick="deleteFac()"/></td>
                        <div class="modal fade" id="login-modal">
                            <div class="modal-dialog modal-lg">
                                 <div class="modal-content">
                                     <div class="modal-header">
                                         <button class="close" data-dismiss="modal">&times</button>
                                         <h4 style="color:red">This CPT Code can not be deleted as the claims below are still associated with the CPT Code !</h4>
                                     </div>
                                      <div class="modal-body">
                                           <div class="container-fluid">
                                               <div class="row">
                                                   <div class="col-md-3"><strong>Last Name</strong></div>
                                                   <div class="col-md-3"><strong>First Name</strong></div>
                                                   <div class="col-md-3"><strong>DOS</strong></div>
                                                   <div class="col-md-3"><strong>Provider</strong></div>
                                               </div>
                                               <div id="detail">

                                               </div>

                                           </div>
                                          <br>
                                          <div id="more" style="float:right">More...</div>
                                      </div>
                                      <div class="modal-footer">
                                         <button class="btn btn-default" data-dismiss="modal">
                                            Close
                                         </button>
                                      </div>
                                 </div>
                            </div>
                        </div>
                        <script>
                            function deleteFac(){
                               var status = $("#status").val();
                               //alert(status);
                               var provider_id = $("#provider_id").val();
                               //alert(provider_id);
                               var cpt_code_id = $('#cpt_code').val();
                               //alert("cpt:"+cpt_code_id);
                               var anesthesia_code_id = $("#anesthesia_code_id").val();
                               //alert("anes:"+anesthesia_code_id);
                               var del_provider_id = $("#del_provider_id").val();
                               //alert(del_provider_id);
                                $.post("<?php echo $this->baseUrl ?>/biller/data/deletecpt/",{'provider_id':provider_id,'anesthesia_code_id':anesthesia_code_id,'status':status,'cpt_code_id':cpt_code_id,'del_provider_id':del_provider_id},function(data){
                                    var myjson='';
                                    eval("myjson=" + data + ";");
                                    var flag = myjson.flag;
                                    var status = myjson.status;
                                    if(status==1){
                                        alert('you can not delete an active CPT code');
                                    }else{
                                            if(flag==1){
                                                //alert('can not delete');
                                                var patientinfoArray = myjson.patientinfoArray;
                                                //alert(typeof(patientinfoArray));
                                                //showdetail.style.display="";

                                               
                                                $("#login-modal").modal('show');
                                                var len = patientinfoArray.length;
                                                //alert(len);
                                                if(len>10){
                                                    len = 10;
                                                }else{
                                                    $("#more").hide();
                                                }
                                                for (var i=0;i<len;i++){
                                                    //alert(patientinfoArray[i]['last_name']);
                                                    $("#detail").append("<div class=\"row\">"+"<div class=\"col-md-3\">"+patientinfoArray[i]['last_name']+"</div>"+"<div class=\"col-md-3\">"+patientinfoArray[i]['first_name']+"</div>"+"<div class=\"col-md-3\">"+patientinfoArray[i]['dos']+"</div>"+"<div class=\"col-md-3\">"+patientinfoArray[i]['providername']+"</div></div>");
        //                                            $("#detail").append("<div class=\"row\">"+"<div class=\"col-md-2\">"+patientinfoArray[i]['last_name']+"</div>"+"<div class=\"col-md-2\">"+patientinfoArray[i]['first_name']+"</div>"+"<div class=\"col-md-4\">"+patientinfoArray[i]['dos']+"</div>"+"<div class=\"col-md-4\">"+patientinfoArray[i]['providername']+"</div></div>");
                                                    //$("#detail").append("<tr><td>"+patientinfoArray[i]['last_name']+"</td><td>"+patientinfoArray[i]['first_name']+"</td><td>"+patientinfoArray[i]['dos']+"</td><td>"+patientinfoArray[i]['providername']+"</td></tr>");
                                                }
                                                $('#login-modal').on('hide.bs.modal',function(){
                                                    $("#detail").children().remove(); //删除所有子元素
                                                });
                                            }else{
                                               alert('delete successfully');
                                               window.location.href="<?php echo $this->baseUrl ?>/biller/data/surgerycode";
                                            }
                                    }
                           

                                });
                            }

                        </script>
                        <td>
                            <span id='del_provider_id_span' style='display:none'>&nbsp;from&nbsp;
                                <select class="select"  name="del_provider_id" style= "width: 70%" id="del_provider_id" >
                                    <?php
                                    foreach ($this->providerList as $row) {
                                        echo "<option value='" . $row['id'] . "'>" . $row['provider_name'] . "</option>";
                                    }
                                    ?>
                                    <option value="0">ALL</option>
                                </select>
                            </span>
                            
                        </td>
                        <td colspan="6"><input type="submit" name="submit" value="New"/></td>
                    </tr>

               

                    <!-- added by Pandazhao  2012/8/13-->
                    <!-- added by Pandazhao 2012/9/04-->
<!--                    <tr>
                        <td></td>
                    </tr>
                            <td></td>
                    </tr>
                    <tr>
                        <td></td>
                    </tr>
                            <td></td>
                    </tr>
                     <tr >
                        <th align="left" colspan="1" >Provider</th>
                        <td  colspan="1" >
                            <select class="select" name="provider_id_2" style= "width:100% " id="provider_id_2" onblur="javascript:changeprovider()">
                                <option value="">Select</option>
                                <?php
                                foreach ($this->providerList as $row) {
                                    echo "<option value='" . $row['id'] . "'>" . $row['provider_name'] . "</option>";
                                }
                                ?>
                                <option value="0">ALL</option>
                            </select>
                        </td>


                        <th align="left">Surgery Code</th>
                        <td colspan="1">
                            <select class="select" name="cpt_code_1" id="cpt_code_2" onchange="javascript:auto_complete_2()" style= "width:100% ">
                                <option value="">Select</option>
                                <?php
                                foreach ($this->cptcodeList as $row) {
                                    echo "<option value='" . $row->id . "'>" . $row->CPT_code . "</option>";
                                }
                                ?>
                            </select>
                        </td>
                        <th align="left">Anesthesia Code</th><td >
                            <input class="select" colspan="1" type ="text" name="anesthesia_code" id="anesthesia_code" onchange="javascript:auto_complete()"/>
                        </td>
                        <th align="left">Description</th><td><input colspan="1" type="text" name="description_2" id="description_2" /></td>
                        <th align="left">Base Unit</th><td><input colspan="1" type="text" name="base_unit" id="base_unit" /></td>
                    </tr>
                    <tr>
                        <th align="left">Charge</th><td><input  colspan="1" type="text" name="charge_2" id="charge_2" /> </td>
                        <th align="left">Expected Amount</th><td><input  colspan="2" type="text" name="expected_amount_2" id="expected_amount_2" /></td>
                    </tr>
                    <tr >
                        <td colspan="1"><input type="submit" name="submit" value="Update_CPT"/></td>
                        <td colspan="1"><input type="submit" name="submit" value="Delete_CPT"/></td>
                        <td colspan="6"><input type="submit" name="submit" value="New"/></td>
                    </tr>-->
                    
                    <!-- added by Pandazhao 2012/9/04-->
                    
                    
                    
                    

                </table>
            </form>

        </div>
    </body>
</html>