<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title> Accendo</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/layout.css" />
        <link rel="stylesheet" rev="stylesheet" type="text/css" media="screen, projection" href="<?php echo $this->baseUrl ?>/styles/pagenav.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/navigation.css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl ?>/styles/jquery.megamenu.css" type="text/css" media="screen" />
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery.js"></script>
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jshelper.js"></script>
        <script src="<?php echo $this->baseUrl ?>/scripts/jquery-1.4.2.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl ?>/scripts/jquery.megamenu.js" type="text/javascript"></script>
        <script type="text/javascript" language="javascript" >
            var interactionlogId = 0;
            var role = "<?php echo $this->role ?>";
            $(document).ready(function()
            {    
                 $.post("<?php echo $this->baseUrl ?>/biller/claims/timeout/",
                function(data)
                {
                    if(data!='no'&&data!=null) {
                        var a=document.getElementById("relogin");
                        a.click(); 
                    }
                }
                );
               if(role=='guest'){
                    var inputList = document.getElementsByTagName("input");
//                    var selectList = document.getElementsByTagName("select");
//                    var textList = document.getElementsByTagName("textarea");
//                    for(var i=0;i<textList.length;i++){
//                        textList[i].disabled = "true";
//                    }
                    for(var i = 0;i<inputList.length;i++){
//                        if(inputList[i].type=='checkbox'||inputList[i].type=='radio'||inputList[i].type=='button')
//                            inputList[i].disabled="true";
                        if(inputList[i].type=='submit'&&(inputList[i].value=='Finish Claim'||inputList[i].value=='Save Claim')){
                            inputList[i].disabled="true";
                            inputList[i].style.background="url(<?php echo $this->baseUrl ?>/images/tab_bg_2.png)";
                        } 
                        if(inputList[i].type=='button'){
                               inputList[i].style.display="none";
                        }
                        
                    }
                  
                    $("#select_desc_source_1").css("display","none");
                    $("#select_desc_source_2").css("display","none");
                    $("#select_desc_1").css("display","none");
                    $("#selfdefinition_1").css("display","none");
                    $("#user_name_1").css("display","none");
                    $("#uploadedfile_2").css("display","none");
                    $("#uploadedfile").css("display","none");
                    $("#select_desc_2").css("display","none");
                    $("#selfdefinition_2").css("display","none");
                    $("#user_name_2").css("display","none");
                    
//                    for(var i = 0;i<selectList.length;i++){
//                        selectList[i].disabled="true";
//                    }
                }
                var needsave=( "<?php echo $this->needsave ?>"==1);
                
                    if(needsave==1){
                    
                       document.getElementById('ischanged').style.display="";
                    }else{
                       document.getElementById('ischanged').style.display="none";
                    }
                var newclaimflag=( "<?php echo $this->new_claim_flag ?>"==1);
                if(newclaimflag){
                    $("#saveclaim").attr("disabled",true);
                    $("#saveclaim").css("background","url('<?php echo $this->baseUrl ?>/images/tab_bg_3.png')");
                }
                else
                    $("#saveclaim").removeAttr("disabled");
                $.get("<?php echo $this->baseUrl ?>/biller/claims/interaction/",
                function(data)
                {
                    var myjson='';
                    eval("myjson=" + data + ";");
                    $("#id").val(myjson.id);
                    if(myjson.interactionlogs != null && myjson.interactionlogs !=''){
                        for(var i = 0;i<myjson.interactionlogs.length;i++){            
                            addtable();
                            $("#date_and_time_"+(i+1)+"").val(myjson. interactionlogs[i].date_and_time);
                            $("#log_"+(i+1)+"").val(myjson. interactionlogs[i].log);
                        }
                    }
                   
                });
            });
        </script>
        <script type="text/javascript" language="javascript">
        function myischanged(){
           // alert(1);
           var id=0;
          document.getElementById('ischanged').style.display="";
           $.get("<?php echo $this->baseUrl ?>/biller/claims/needsave/",
                 function(date){
           });
        }
    </script>
        <script type="text/javascript">
              function displaycheck(name){
              //  var value=$('#new_description_type_1').value();
//                var table = document.getElementsByTagName("table")[1];
//                var  th = table.getElementsByTagName('th');
//                var value=th[(index)*4+1].innerHTML;
                 var value=$(name).val();
              //  var value=  document.getElementById('new_description_type_1').innerHTML;
//                 alert(value);
                 for(var index=0;index<value.length;index++){
                      var cur=value.charAt(index) ;
                      if((cur<='9'&&cur>='0')||cur==' '||(cur<='z'&&cur>='a')||(cur<='Z'&&cur>='A')||cur=='-'||cur=='_'){
                      }
                      else{
                          value=value.substr(0,index)+value.substr(index+1,value.length-index-1);
                           $(name).val(value);
                          var tempname=name.substr(1,name.length-1);
                                        //alert(tempname);
                           setCaretPosition(document.getElementById(tempname),index);
    
                                        
                      }
                  }
             }
              function setCaretPosition(ctrl, pos){//设置光标位置函数
                    if(ctrl.setSelectionRange)
                    {
                            ctrl.focus();
                            ctrl.setSelectionRange(pos,pos);
                    }
                    else if (ctrl.createTextRange) {
                            var range = ctrl.createTextRange();
                            range.collapse(true);
                            range.moveEnd('character', pos);
                            range.moveStart('character', pos);
                            range.select();
                    }
            }
//            function displaycheckother()
//            {
//                var value=$('#new_description_type_1').val();
//                alert(value);
//            }
            function desc_selfdef1()
            {
                var doc_desc  = $("#doc_desc_1").val();
                if(doc_desc == 'selfdefinition')
                {
                    $("#select_desc_1").css("display","none");
                    $("#selfdefinition_1").css("display","table-cell");
                }
            }
            function descsource_selfdef1()
            {
                var doc_desc  = $("#doc_desc_source_1_select").val();
                if(doc_desc == 'selfdefinition')
                {
                    $("#select_desc_source_1").css("display","none");
                    $("#selfdefinition_source_1").css("display","table-cell");
                }
               else{
                   var new_doc_desc = doc_desc.replace(/\-/g,"_");
                   $("#doc_desc_source_1").val(new_doc_desc);
               }
               
            }
        </script>
 
        <script type="text/javascript">
            function desc_selfdef2()
            {
                var doc_desc  = $("#doc_desc_2").val();
                if(doc_desc == 'selfdefinition')
                {
                    $("#select_desc_2").css("display","none");
                    $("#selfdefinition_2").css("display","table-cell");
                }
            }
            function descsource_selfdef2()
            {
                var doc_desc  = $("#doc_desc_source_2_select").val();
                if(doc_desc == 'selfdefinition')
                {
                    $("#select_desc_source_2").css("display","none");
                    $("#selfdefinition_source_2").css("display","table-cell");
                }
               else{
                   var new_doc_desc = doc_desc.replace(/\-/g,"_");
//                   alert(new_doc_desc);
                   $("#doc_desc_source_2").val(new_doc_desc);
               }
            }
        </script>
        
        <script type="text/javascript" language="javascript">
             
            function patientdatasort()
            {
                
                $.post("<?php echo $this->baseUrl ?>/biller/claims/sortdocs/",{type:"date",doc:"patient"},
                        function(data){
                            var myjson='';
                            eval("myjson=" + data + ";");
                            
                            
                            for(var i = 0;i<myjson.patient_doc_list.length;i++){
                                
                                $(myjson.patient_doc_list[i]['changeid']).empty();
                                if(i%2==0){
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center' > <a href = \"/accendo/public/" + myjson.patient_doc_list[i]['url'] + " \" target = \" _blank \">" + myjson.patient_doc_list[i]['data'] + "</a></th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" + myjson.patient_doc_list[i]['description'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'> " + myjson.patient_doc_list[i]['description_source'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" +  myjson.patient_doc_list[i]['owner'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='12%' style='text-align: center'><input id=\"" + myjson.patient_doc_list[i]['url'] + "\" style=\"color: #000;background: #ddd;border: 2px solid gray;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this)\"" + "</input></th>");
                                }
                                if(i%2==1)
                                {
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center' > <a href = \"/accendo/public/" + myjson.patient_doc_list[i]['url'] + " \" target = \" _blank \">" + myjson.patient_doc_list[i]['data'] + "</a></th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" + myjson.patient_doc_list[i]['description'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" + myjson.patient_doc_list[i]['description_source'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" +  myjson.patient_doc_list[i]['owner'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='12%' style='background:#eeeeee;text-align: center'><input id=\"" + myjson.patient_doc_list[i]['url'] + "\" style=\"color: #000;background: #ddd;border: 2px solid gray;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this)\"" + "</input></th>");
                                }
                        }
                        }
                    );
            }
            
            function patientdesctypesort()
            {
                
               $.post("<?php echo $this->baseUrl ?>/biller/claims/sortdocs/",{type:"desc_type",doc:"patient"},
                        function(data){
                            var myjson='';
                            eval("myjson=" + data + ";");
                            
                            
                            for(var i = 0;i<myjson.patient_doc_list.length;i++){
                                
                                $(myjson.patient_doc_list[i]['changeid']).empty();
                                if(i%2==0){
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center' > <a href = \"/accendo/public/" + myjson.patient_doc_list[i]['url'] + " \" target = \" _blank \">" + myjson.patient_doc_list[i]['data'] + "</a></th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" + myjson.patient_doc_list[i]['description'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" +  myjson.patient_doc_list[i]['description_source'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" +  myjson.patient_doc_list[i]['owner'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='12%' style='text-align: center'><input id=\"" + myjson.patient_doc_list[i]['url'] + "\" style=\"color: #000;background: #ddd;border: 2px solid gray;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this)\"" + "</input></th>");
                                }
                                if(i%2==1)
                                {
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center' > <a href = \"/accendo/public/" + myjson.patient_doc_list[i]['url'] + " \" target = \" _blank \">" + myjson.patient_doc_list[i]['data'] + "</a></th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" + myjson.patient_doc_list[i]['description'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" +  myjson.patient_doc_list[i]['description_source'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" +  myjson.patient_doc_list[i]['owner'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='12%' style='background:#eeeeee;text-align: center'><input id=\"" + myjson.patient_doc_list[i]['url'] + "\" style=\"color: #000;background: #ddd;border: 2px solid gray;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this)\"" + "</input></th>");
                                }
                        }
                        }
                    );
            }
            function patientdescsourcesort()
            {
                
                $.post("<?php echo $this->baseUrl ?>/biller/claims/sortdocs/",{type:"desc_source",doc:"patient"},
                        function(data){
                            var myjson='';
                            eval("myjson=" + data + ";");
                            
                            
                            for(var i = 0;i<myjson.patient_doc_list.length;i++){
                                
                                $(myjson.patient_doc_list[i]['changeid']).empty();
                                if(i%2==0){
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center' > <a href = \"/accendo/public/" + myjson.patient_doc_list[i]['url'] + " \" target = \" _blank \">" + myjson.patient_doc_list[i]['data'] + "</a></th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" + myjson.patient_doc_list[i]['description'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" +  myjson.patient_doc_list[i]['description_source'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" +  myjson.patient_doc_list[i]['owner'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='12%' style='text-align: center'><input id=\"" + myjson.patient_doc_list[i]['url'] + "\" style=\"color: #000;background: #ddd;border: 2px solid gray;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this)\"" + "</input></th>");
                                }
                                if(i%2==1)
                                {
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center' > <a href = \"/accendo/public/" + myjson.patient_doc_list[i]['url'] + " \" target = \" _blank \">" + myjson.patient_doc_list[i]['data'] + "</a></th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" + myjson.patient_doc_list[i]['description'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" +  myjson.patient_doc_list[i]['description_source'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" +  myjson.patient_doc_list[i]['owner'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='12%' style='background:#eeeeee;text-align: center'><input id=\"" + myjson.patient_doc_list[i]['url'] + "\" style=\"color: #000;background: #ddd;border: 2px solid gray;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this)\"" + "</input></th>");
                                }
                        }
                        }
                    );
            }
            function patientownersort()
            {
                
                $.post("<?php echo $this->baseUrl ?>/biller/claims/sortdocs/",{type:"owner",doc:"patient"},
                        function(data){
                            var myjson='';
                            eval("myjson=" + data + ";");
                            
                            
                            for(var i = 0;i<myjson.patient_doc_list.length;i++){
                                
                                $(myjson.patient_doc_list[i]['changeid']).empty();
                                if(i%2==0){
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center' > <a href = \"/accendo/public/" + myjson.patient_doc_list[i]['url'] + " \" target = \" _blank \">" + myjson.patient_doc_list[i]['data'] + "</a></th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" + myjson.patient_doc_list[i]['description'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" +  myjson.patient_doc_list[i]['description_source'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" +  myjson.patient_doc_list[i]['owner'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='12%' style='text-align: center'><input id=\"" + myjson.patient_doc_list[i]['url'] + "\" style=\"color: #000;background: #ddd;border: 2px solid gray;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this)\"" + "</input></th>");
                                }
                                if(i%2==1)
                                {
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center' > <a href = \"/accendo/public/" + myjson.patient_doc_list[i]['url'] + " \" target = \" _blank \">" + myjson.patient_doc_list[i]['data'] + "</a></th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" + myjson.patient_doc_list[i]['description'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" +  myjson.patient_doc_list[i]['description_source'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" +  myjson.patient_doc_list[i]['owner'] + "</th>");
                                $(myjson.patient_doc_list[i]['changeid']).append("<th width='12%' style='background:#eeeeee;text-align: center'><input id=\"" + myjson.patient_doc_list[i]['url'] + "\" style=\"color: #000;background: #ddd;border: 2px solid gray;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this)\"" + "</input></th>");
                                }
                        }
                        }
                    );
            }
        </script>
        <script type="text/javascript" language="javascript">
            function onDelete(id)
            {
                var r=confirm("The selected document will be permenantly deleted from Accendo, please confirm");
                var url = id.id;
                if (r == true)
                {
                    $.post("<?php echo $this->baseUrl ?>/biller/claims/deletedocs/",{url:url},
                    function(data){
                         
                            $("#Documents").click();
                        
                    });
                }
                else
                {
                    //alert("No Doc Exsit!");
                }
                $("#Documents").click();
                myischanged();
                //$.post("<?php echo $this->baseUrl ?>/biller/claims/deletedocs/",{url:url},function(data){});
            }
        </script>
            
        <script type="text/javascript" language="javascript">
            function upload(Inp)
            {
                //alert(Inp.id);
                var id = Inp.id; 
                if (id == "upload_p")
                {
                    $("#uplaod_p_submit").click();
                }
                if(id == "upload_c")
                {
                    $("#uplaod_c_submit").click();                    
                }
               // myischanged();
              
            }
        </script>
        <script type="text/javascript" language="javascript">
             
            function claimdatasort()
            {
                
                $.post("<?php echo $this->baseUrl ?>/biller/claims/sortdocs/",{type:"date",doc:"claim"},
                        function(data){
                            var myjson='';
                            eval("myjson=" + data + ";");
                            
                            
                            for(var i = 0;i<myjson.claim_doc_list.length;i++){
                                
                                $(myjson.claim_doc_list[i]['changeid']).empty();
                                if(i%2==0){
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center' > <a href = \"/accendo/public/" + myjson.claim_doc_list[i]['url'] + " \" target = \" _blank \">" + myjson.claim_doc_list[i]['data'] + "</a></th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" + myjson.claim_doc_list[i]['description'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" + myjson.claim_doc_list[i]['description_source'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" +  myjson.claim_doc_list[i]['owner'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='12%' style='text-align: center'><input id=\"" + myjson.claim_doc_list[i]['url'] + "\" style=\"color: #000;background: #ddd;border: 2px solid gray;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this)\"" + "</input></th>");
                                }
                                if(i%2==1)
                                {
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center' > <a href = \"/accendo/public/" + myjson.claim_doc_list[i]['url'] + " \" target = \" _blank \">" + myjson.claim_doc_list[i]['data'] + "</a></th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" + myjson.claim_doc_list[i]['description'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" + myjson.claim_doc_list[i]['description_source'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" +  myjson.claim_doc_list[i]['owner'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='12%' style='background:#eeeeee;text-align: center'><input id=\"" + myjson.claim_doc_list[i]['url'] + "\" style=\"color: #000;background: #ddd;border: 2px solid gray;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this)\"" + "</input></th>");
                                }
                        }
                        }
                    );
            }
            
            function claimdesctypesort()
            {
                
               $.post("<?php echo $this->baseUrl ?>/biller/claims/sortdocs/",{type:"desc_type",doc:"claim"},
                        function(data){
                            var myjson='';
                            eval("myjson=" + data + ";");
                            
                            
                            for(var i = 0;i<myjson.claim_doc_list.length;i++){
                                
                                $(myjson.claim_doc_list[i]['changeid']).empty();
                                if(i%2==0){
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center' > <a href = \"/accendo/public/" + myjson.claim_doc_list[i]['url'] + " \" target = \" _blank \">" + myjson.claim_doc_list[i]['data'] + "</a></th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" + myjson.claim_doc_list[i]['description'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" + myjson.claim_doc_list[i]['description_source'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" +  myjson.claim_doc_list[i]['owner'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='12%' style='text-align: center'><input id=\"" + myjson.claim_doc_list[i]['url'] + "\" style=\"color: #000;background: #ddd;border: 2px solid gray;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this)\"" + "</input></th>");
                                }
                                if(i%2==1)
                                {
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center' > <a href = \"/accendo/public/" + myjson.claim_doc_list[i]['url'] + " \" target = \" _blank \">" + myjson.claim_doc_list[i]['data'] + "</a></th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" + myjson.claim_doc_list[i]['description'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" + myjson.claim_doc_list[i]['description_source'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" +  myjson.claim_doc_list[i]['owner'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='12%' style='background:#eeeeee;text-align: center'><input id=\"" + myjson.claim_doc_list[i]['url'] + "\" style=\"color: #000;background: #ddd;border: 2px solid gray;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this)\"" + "</input></th>");
                                }
                        }
                        }
                    );
            }
            function claimdescsourcesort()
            {
                
                $.post("<?php echo $this->baseUrl ?>/biller/claims/sortdocs/",{type:"desc_source",doc:"claim"},
                        function(data){
                            var myjson='';
                            eval("myjson=" + data + ";");
                            
                            
                            for(var i = 0;i<myjson.claim_doc_list.length;i++){
                                
                                $(myjson.claim_doc_list[i]['changeid']).empty();
                                if(i%2==0){
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center' > <a href = \"/accendo/public/" + myjson.claim_doc_list[i]['url'] + " \" target = \" _blank \">" + myjson.claim_doc_list[i]['data'] + "</a></th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" + myjson.claim_doc_list[i]['description'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" + myjson.claim_doc_list[i]['description_source'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" +  myjson.claim_doc_list[i]['owner'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='12%' style='text-align: center'><input id=\"" + myjson.claim_doc_list[i]['url'] + "\" style=\"color: #000;background: #ddd;border: 2px solid gray;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this)\"" + "</input></th>");
                                }
                                if(i%2==1)
                                {
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center' > <a href = \"/accendo/public/" + myjson.claim_doc_list[i]['url'] + " \" target = \" _blank \">" + myjson.claim_doc_list[i]['data'] + "</a></th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" + myjson.claim_doc_list[i]['description'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" + myjson.claim_doc_list[i]['description_source'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" +  myjson.claim_doc_list[i]['owner'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='12%' style='background:#eeeeee;text-align: center'><input id=\"" + myjson.claim_doc_list[i]['url'] + "\" style=\"color: #000;background: #ddd;border: 2px solid gray;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this)\"" + "</input></th>");
                                }
                        }
                        }
                    );
            }
            function claimownersort()
            {
                
                $.post("<?php echo $this->baseUrl ?>/biller/claims/sortdocs/",{type:"owner",doc:"claim"},
                        function(data){
                            var myjson='';
                            eval("myjson=" + data + ";");
                            
                            
                            for(var i = 0;i<myjson.claim_doc_list.length;i++){
                                
                                $(myjson.claim_doc_list[i]['changeid']).empty();
                                if(i%2==0){
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center' > <a href = \"/accendo/public/" + myjson.claim_doc_list[i]['url'] + " \" target = \" _blank \">" + myjson.claim_doc_list[i]['data'] + "</a></th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" + myjson.claim_doc_list[i]['description'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" + myjson.claim_doc_list[i]['description_source'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='text-align: center'>" +  myjson.claim_doc_list[i]['owner'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='12%' style='text-align: center'><input id=\"" + myjson.claim_doc_list[i]['url'] + "\" style=\"color: #000;background: #ddd;border: 2px solid gray;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this)\"" + "</input></th>");
                                }
                                if(i%2==1)
                                {
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center' > <a href = \"/accendo/public/" + myjson.claim_doc_list[i]['url'] + " \" target = \" _blank \">" + myjson.claim_doc_list[i]['data'] + "</a></th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" + myjson.claim_doc_list[i]['description'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" + myjson.claim_doc_list[i]['description_source'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='22%' style='background:#eeeeee;text-align: center'>" +  myjson.claim_doc_list[i]['owner'] + "</th>");
                                $(myjson.claim_doc_list[i]['changeid']).append("<th width='12%' style='background:#eeeeee;text-align: center'><input id=\"" + myjson.claim_doc_list[i]['url'] + "\" style=\"color: #000;background: #ddd;border: 2px solid gray;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this)\"" + "</input></th>");
                                }
                        }
                        }
                    );
            }
        </script>
        <script type="text/javascript" language="javascript" >
            
            function addtable(){
                interactionlogId = interactionlogId +1;
                var count5 = document.getElementById("count");
                var interactionlogTd = document.getElementById("interactionlogTd");
                var interactionlogDiv = document.getElementById("interactionlogDiv");
                var interactionlogTable = document.getElementById("interactionlogTable");
                count5.value = interactionlogId;
                
                if(interactionlogId==1){
                    interactionlogTd.style.display ="";
                    interactionlogDiv.style.display = "";
                    interactionlogDiv.style.height ="25px";
                }
                if(interactionlogId ==2){
                    interactionlogDiv.style.height = "50px";
                }
                if(interactionlogId == 3){
                    interactionlogDiv.style.height = "75px";
                }
                var newTr= interactionlogTable.insertRow(0);
                newTr.id="tr"+interactionlogId+"";
                var newth1 = document.createElement("TH");
                var newtd1 = document.createElement("TD");
                var newth2 = document.createElement("TH");
                if(navigator.userAgent.indexOf("MSIE")!=-1){
                    newth1.style.width="122px";
                    newth1.colspan=1;
                    newth2.style.width="124px";
                }else{
                    newth1.style.width="130px";
                    newth1.colspan=1;
                    newth2.style.width="136px";
                }
                newth1.innerHTML ="Date And Time";
                newth2.innerHTML ="Log";
                newTr.appendChild(newth1,0);
                newTr.appendChild(newtd1,1);
                newTr.appendChild(newth2,2);
                var newtd2 = newTr.insertCell(3);
                if(navigator.userAgent.indexOf("MSIE")!=-1){
                    newtd2.style.width="999px";
                }else{
                    newtd2.style.width="995px";
                }
                newtd1.style.width="130px";
                newtd1.innerHTML ="<input type=\"text\" name=\"date_and_time_"+interactionlogId+"\" id=\"date_and_time_"+interactionlogId+"\" onkeyup=\"javascript:dateandtime(\'#date_and_time_"+interactionlogId+"\')\" onfocus=\"javascript:dateandtimefocus("+interactionlogId+")\"/>";
                newtd2.innerHTML ="<input type=\"text\" name=\"log_"+interactionlogId+"\" id=\"log_"+interactionlogId+"\" style=\"width:99%\"/>";               
        
            }
        </script>
        <script type="text/javascript" language="javascript" >
        function hiddenshowtime(){
            var today=new Date();
            var year=today.getFullYear();
            var month=today.getMonth()+1;
            var day=today.getDate();
            var hours = today.getHours();
            var minutes = today.getMinutes();
            var seconds = today.getSeconds();
            var timeValue = (month<10?"0":"")+month+"/"+(day<10?"0":"")+day+"/"+year + " " + (hours<10?"0":"")+hours +":" + (minutes<10?"0":"")+minutes+":"+seconds; 
            return timeValue;
            }
        function showtime(){
            var today=new Date();
            var year=today.getFullYear();
            var month=today.getMonth()+1;
            var day=today.getDate();
            var hours = today.getHours();
            var minutes = today.getMinutes();
            var timeValue = (month<10?"0":"")+month+"/"+(day<10?"0":"")+day+"/"+year + " " + (hours<10?"0":"")+hours +":" + (minutes<10?"0":"")+minutes; 
            return timeValue;
            }
        </script>
            
        <script type="text/javascript" language="javascript" >
        function addlog(time,log)
            {
                addtable();
                $('#date_and_time_'+interactionlogId).val(time);                     
                $('#log_'+interactionlogId).val(log);
                var hiddentime = hiddenshowtime();
                $('#hidden_date_and_time_'+interactionlogId).val(hiddentime);
            }
        </script>
        <script type="text/javascript" language="javascript" >
            function deletetable   (){
                var interactionlogTd = document.getElementById("interactionlogTd");
                var interactionlogDiv = document.getElementById("interactionlogDiv");
                var count5 = document.getElementById("count");
                if(interactionlogId>1){
                    
                    var theDeleTr = document.getElementById("tr"+interactionlogId+"");
                    
                    theDeleTr.parentNode.removeChild(theDeleTr);
                    --interactionlogId;
                    paymentreceived3(interactionlogId);
                    count5.value = interactionlogId;
                 
                    if(interactionlogId ==1){
                        interactionlogDiv.style.height ="25px";
                    }
                    if(interactionlogId == 2){
                        interactionlogDiv.style.height = "50px";
                    }
                    if(interactionlogId == 3){
                        interactionlogDiv.style.height ="75px";
                    }
                }
            } 
        </script>
    </head>

    <body>
        <a href="<?php echo $this->baseUrl ?>" target="_top" id="relogin" style="display: none" >wwwwww</a>
        <div class="table-div" >
            <form enctype="multipart/form-data"  method="post" >
                <table>
                    <tr class="navigation">
                        <td colspan="8" style="background:#ffffff">
                            <a href="#"><span> <input type="submit" name="submit" id="Previous"value="Previous"/></span></a>
                            <a href="#"><span> <input type="submit"name="submit"id="Patient"value="Patient" /></span></a>
                            <a href="#"><span> <input type="submit" name="submit"id="Insurance"value="Insurance" /></span></a>
                            <a href="#"><span> <input type="submit"name="submit"id="Service"value="Service" /></span></a>
                            <a href="#"><span> <input type="submit" name="submit"id="Claim"value="Claim" style="width:60px" /></span></a>
                            <a href="#"><span> <input type="submit"name="submit"id="Documents"value="Documents" style="width:100px;background:url(<?php echo $this->baseUrl ?>/images/tab_bg_3.png)" /></span></a>
                            <a href="#"><span> <input type="submit"name="submit"id="Next"value="Next" style="background:url(<?php echo $this->baseUrl ?>/images/tab_bg_2.png)" disabled="disabled"/></span></a>       
                            <span style="margin:0 0 0 30px"> 
                             <div id="current">                                      
                             <ul class="megamenu">
                                 <li ><a href="javascript:void(0)" ><font color="FF0000" size="1px"><?php echo $this->cur_service_info['patient_name'] ?></font></a>&nbsp;<!--    </li>
                                 <li>
                                     <a href="javascript:void(0)" style="color:#FF0000;">=</a>-->
                                     <div style="width: 840px; left:3px;">
                                         <!-- <h3>Dropdown Example</h3> -->
                                         <table border="1" cellpadding="0" cellspacing="0" id="tabular-content">
                                             <tr>
                                                <!-- <th style="width: 15px">Number</th> -->
                                                 <th style="text-align:center">DOS</th>
                                                 <th style="width: 26%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Charge</th>
                                                 <th style="width: 25%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Paid</th>
                                                 <th style="width: 25%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">%</th>
                                                 <th style="width: 25%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Due</th>
                                                 <th style="width: 26%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Insurance</th>
                                                 <th style="width: 25%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Provider</th>
                                                 <th style="width: 26%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Rendering Provider</th>
                                                 <th style="width: 25%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Referring Provider</th>
                                                 <th style="width: 32%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Facility</th>
                                                 <th style="width: 32%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Last</th>
                                                 <th style="width: 32%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Claim Status</th>
                                                 <th style="width: 32%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Bill Status</th>
                                                 <th style="width: 32%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Statement Status</th>
                                                  <!--<th style="width: 100px">DOS</th> -->
                                             </tr>
                                             
                                             <?php
                                             $tmp_baseUrl = $this->baseUrl;
                                             $tmp_claim_id = $this->cur_service_info['claim_id'];                                             
                                             foreach($this->tmpList as $row)
                                             {
                                                
                                                if( $row['claim_id'] == $tmp_claim_id )
                                                {
                                                    $rendering_provdier_name = $row['ren_last_name']. ', '. $row['ren_first_name'];
                                                    $referring_provider_name = $row['ref_last_name'].', '.$row['ref_first_name'];
                                                    
                                                    echo "<tr><td style= 'background-color: rgb(150,230,230);'>";                                                  
                                                    echo "<a href=\"". $this->baseUrl."/biller/claims/dropdown?patient_id=".$row['patient_id']. " & encounter_id=".$row['encounter_id'] ." & type=documents \">";
                                                    echo $row['dos']."</a></td>";
                                                     echo "<td style= 'width: 26%;text-overflow:clip ; overflow:hidden; white-space:nowrap; background-color: rgb(150,230,230);'>";
                                                    echo $row['total_charge']."</a></td>";
                                                     echo "<td style= 'width: 26%;text-overflow:clip ; overflow:hidden; white-space:nowrap; background-color: rgb(150,230,230);'>";
                                                    echo $row['amount_paid']."</a></td>";
                                                    echo "<td style= 'width: 26%;text-overflow:clip ; overflow:hidden; white-space:nowrap; background-color: rgb(150,230,230);'>";
                                                    echo $row['percentage']."</a></td>";
                                                    echo "<td style= 'width: 26%;text-overflow:clip ; overflow:hidden; white-space:nowrap; background-color: rgb(150,230,230);'>";
                                                    echo $row['balance_due']."</a></td>";
                                                    echo "<td style= 'width: 26%;text-overflow:clip ; overflow:hidden; white-space:nowrap; background-color: rgb(150,230,230);'>";
                                                    echo $row['insurance_display']."</a></td>";
                                                    echo "<td style= 'width: 26%;text-overflow:clip ; overflow:hidden; white-space:nowrap; background-color: rgb(150,230,230);'>";
                                                    echo $row['provider_short_name']."</a></td>";
                                                    echo "<td style= 'width: 26%;text-overflow:clip ; overflow:hidden; white-space:nowrap; background-color: rgb(150,230,230);'>";
                                                    echo substr($rendering_provdier_name,0,15)."</td>" ;
                                                    echo "<td style= 'width: 25%;text-overflow:clip ; overflow:hidden; white-space:nowrap;background-color: rgb(150,230,230);'>";
                                                    echo substr($referring_provider_name,0,15)."</td>";
                                                     echo "<td style= 'width: 26%;text-overflow:clip ; overflow:hidden; white-space:nowrap; background-color: rgb(150,230,230);'>";
                                                    echo $row['facility_short_name']."</a></td>";
                                                    echo "<td style= 'width: 26%;text-overflow:clip ; overflow:hidden; white-space:nowrap; background-color: rgb(150,230,230);'>";
                                                    echo $row['last']."</a></td>";
                                                    echo "<td style= 'width: 32%;text-overflow:clip ; overflow:hidden; white-space:nowrap;background-color: rgb(150,230,230);'>";
                                                    echo substr($row['claim_status'],0,30)."</a></td>";
                                                     echo "<td style= 'width: 50%;text-overflow:clip ; overflow:hidden; white-space:nowrap;background-color: rgb(150,230,230);'>";
                                                    echo substr($row['bill_status'],0,30)."</a></td>";
                                                     echo "<td style= 'width: 50%;text-overflow:clip ; overflow:hidden; white-space:nowrap;background-color: rgb(150,230,230);'>";
                                                    echo substr($row['statement_status'],0,30)."</a></td>";
                                                    echo "<tr>";
                                                }
                                                else
                                                {
                                                    $rendering_provdier_name = $row['ren_last_name']. ', '. $row['ren_first_name'];
                                                    $referring_provider_name = $row['ref_last_name'].', '.$row['ref_first_name'];
                                                    
                                                    echo "<tr><td>";
                                                    echo "<a href=\"". $this->baseUrl."/biller/claims/dropdown?patient_id=".$row['patient_id']. " & encounter_id=".$row['encounter_id'] ." & type=documents \">";
                                                    echo $row['dos']."</a></td>";
                                                    echo "<td style= 'width: 32%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo $row['total_charge']."</a></td>";
                                                     echo "<td style= 'width: 32%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo $row['amount_paid']."</a></td>";
                                                     echo "<td style= 'width: 32%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo $row['percentage']."</a></td>";
                                                     echo "<td style= 'width: 32%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo $row['balance_due']."</a></td>";
                                                     echo "<td style= 'width: 32%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo $row['insurance_display']."</a></td>";
                                                     echo "<td style= 'width: 32%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo $row['provider_short_name']."</a></td>";
                                                    echo "<td style= 'width: 26%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo substr($rendering_provdier_name,0,15)."</td>" ;
                                                    echo "<td style= 'width: 25%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo substr($referring_provider_name,0,15)."</td>";
                                                    echo "<td style= 'width: 32%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo $row['facility_short_name']."</a></td>";
                                                    echo "<td style= 'width: 32%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo $row['last']."</a></td>";
                                                    echo "<td style= 'width: 32%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo substr($row['claim_status'],0,30)."</a></td>";;
                                                    echo "<td style= 'width: 50%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo substr($row['bill_status'],0,30)."</a></td>";;
                                                    echo "<td style= 'width: 50%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo substr($row['status_status'],0,30)."</a>";;
                                                    echo "</td><tr>";
                                                }
                                             }
                                             ?>
                                         </table>
                                     </div>
                                 </li>
                                 
                                     |&nbsp;<?php echo $this->cur_service_info['gender'] ?>&nbsp;
                                     |&nbsp;<?php echo $this->cur_service_info['DOB'] ?>&nbsp;
                                     |&nbsp;<?php echo $this->cur_service_info['MRN'] ?>&nbsp;
                                     |&nbsp;<?php echo $this->cur_service_info['DOS'] ?>&nbsp;
                                     |&nbsp$<?php echo $this->cur_service_info['total_charge'] ?>&nbsp;
                                
                                     <br/><li>&nbsp;&nbsp;<?php echo $this->cur_service_info['secondary_cpt_code_1'] ?>&nbsp;
                                    |&nbsp;<?php echo $this->cur_service_info['provider_short_name'] ?>&nbsp;
                                    |&nbsp;<?php echo $this->cur_service_info['renderingprovider_name'] ?>&nbsp;
                                    |&nbsp;<?php echo $this->cur_service_info['referingprovider_name'] ?>&nbsp;
                                    |&nbsp;<li><a href="javascript:void(0)"><font color = "FF0000" size ="1px"><?php echo $this->cur_service_info['insurance_display'] ?></font></a>
                                    <div style="width: 840px; left:3px;">
                                         <!-- <h3>Dropdown Example</h3> -->
                                         <table border="1" cellpadding="0" cellspacing="0" id="tabular-content">
                                             <tr>
                                                <!-- <th style="width: 15px">Number</th> -->
<!--                                                 <th style="width: 30%;text-align:center">Name</th>-->
                                                 <th style="width: 32%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Patient Name</th>
                                                 <th style="width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">DOB</th>
                                                 <th style="width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">MRN</th>
                                                 <th style="width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">DOS</th>
                                                 <th style="width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Charge</th>
                                                 <th style="width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Due</th>
                                                 <th style="width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">%</th>
                                                 <th style="width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Paid</th>
                                                
                                                 <th style="width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Insurance</th>
                                                 <th style="width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Provider</th>
                                                 <th style="width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Rendering Provider</th>
                                                 <th style="width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Referring Provider</th>
                                                 <th style="width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Facility</th>
                                                 <th style="width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Last</th>
                                                 <th style="width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Issue</th>
                                                 
                                                  <!--<th style="width: 100px">DOS</th> -->
                                             </tr>
                                             
                                             <?php
                                             $tmp_baseUrl = $this->baseUrl;
                                             $tmp_claim_id = $this->cur_service_info['claim_id'];  
                                             
                                             foreach($this->taiList as $row)
                                             {
                                                
                                                if( $row['claim_id'] == $tmp_claim_id )
                                                {
                                                    $rendering_provdier_name = substr($row['renderingprovider'],0,15) ;
                                                    $referring_provider_name = substr($row['referringprovider'],0,15);
                                                    
                                                    echo "<tr><td style= 'width: 32%;background-color: rgb(150,230,230);'>";                                                  
                                                    echo "<a href=\"". $this->baseUrl."/biller/claims/dropdown?patient_id=".$row['patient_id']. " & encounter_id=".$row['encounter_id'] ." & type=documents\">";
                                                    echo substr($row['name'],0,20)."</a></td>";
                                                     echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap; background-color: rgb(150,230,230);'>";
                                                    echo  date('m/d/Y', strtotime($row['DOB']))."</a></td>";
                                                     echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap; background-color: rgb(150,230,230);'>";
                                                    echo $row['MRN']."</a></td>";
                                                    echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap; background-color: rgb(150,230,230);'>";
                                                    echo date('m/d/Y', strtotime($row['DOS'])) ."</a></td>";
                                                    echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap; background-color: rgb(150,230,230);'>";
                                                    echo $row['total_charge']."</a></td>";
                                                    echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap; background-color: rgb(150,230,230);'>";
                                                    echo $row['due']."</a></td>";
                                                    echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap; background-color: rgb(150,230,230);'>";
                                                    echo $row['percentage']."</a></td>";
                                                    echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap; background-color: rgb(150,230,230);'>";
                                                    echo $row['amount_paid']."</td>" ;
                                                    echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;background-color: rgb(150,230,230);'>";
                                                    echo substr($row['payer'],0,15) ."</td>";
                                                     echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap; background-color: rgb(150,230,230);'>";
                                                    echo $row['provider_short_name']."</a></td>";
                                                    echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap; background-color: rgb(150,230,230);'>";
                                                    echo substr($row['renderingprovider'],0,15) ."</a></td>";
                                                    echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;background-color: rgb(150,230,230);'>";
                                                    echo substr($row['referringprovider'],0,15) ."</a></td>";
                                                     echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;background-color: rgb(150,230,230);'>";
                                                    echo substr($row['facility_short_name'],0,30)."</a></td>";
                                                     echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;background-color: rgb(150,230,230);'>";
                                                    echo substr($row['last'],0,30)."</a></td>";
                                                     echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;background-color: rgb(150,230,230);'>";
                                                    echo substr($row['display'],0,30)."</a></td>";
                                                    echo "<tr>";
                                                }
                                                else
                                                {
                                                     $rendering_provdier_name = substr($row['renderingprovider'],0,15) ;
                                                    $referring_provider_name = substr($row['referringprovider'],0,15);
                                                    
                                                    echo "<tr><td style= 'width: 32%'>";
                                                    echo "<a href=\"". $this->baseUrl."/biller/claims/dropdown?patient_id=".$row['patient_id']. " & encounter_id=".$row['encounter_id'] ." & type=documents \">";
                                                    echo  substr($row['name'],0,20)."</a></td>";
                                                    echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo date('m/d/Y', strtotime($row['DOB']))."</a></td>";
                                                     echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo $row['MRN']."</a></td>";
                                                     echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo date('m/d/Y', strtotime($row['DOS'])) ."</a></td>";
                                                     echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo $row['total_charge']."</a></td>";
                                                     echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo $row['due']."</a></td>";
                                                     echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo $row['percentage']."</a></td>";
                                                    echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo  $row['amount_paid']."</td>" ;
                                                    echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo  substr($row['payer'],0,15) ."</td>";
                                                    echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo $row['provider_short_name']."</a></td>";
                                                    echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo substr($row['renderingprovider'],0,15) ."</a></td>";
                                                    echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo substr($row['referringprovider'],0,15)."</a></td>";;
                                                    echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo substr($row['facility_short_name'],0,30)."</a></td>";;
                                                    echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo substr($row['last'],0,30)."</a>";;
                                                    echo "<td style= 'width: 1%;text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo substr($row['display'],0,30)."</a>";;
                                                    echo "</td><tr>";
                                                }
                                             }
                                             ?>
                                         </table>
                                    </div>|&nbsp;
                                    </li><li><?php echo $this->cur_service_info['insured_ID_number'] ?></li>
                                  </li> </ul>                                                                                                           
                           </div>
                           </span>
                            <a href="#"><span style="float:right;margin:2px 0px 0 0"> <input type="submit"name="submit"value="Finish Claim"  style="width:80px"/></span></a>
                            <a href="#"><span style="float:right;margin:2px 0px 0 0"> <input type="submit"name="submit"value="Save Claim" id="saveclaim" style="width:80px"/></span></a>
                            <a name="ischanged" id="ischanged"  style='color:red;display: none' ><span style="float:right;margin:-25px 5px 0 0;font-size: 50px;font-family:Times New Roman">.</span></a>

                        </td>
                    </tr>
                </table>
            
        
        <p style="height:40px">  </p>
        
            <table id="table_one">
                <tr>
                    <th align="center" colspan="15" style="font-size: larger;line-height:30px;background:#eeeeee">
                        <p align="center"><b><big>Patient Documents</big></b></p>
                    </th>
                </tr>
                <tr>
                    <th width="22%" style="background:#eeeeee;text-align: center"><button id="datasortbutton1" onclick="javascript:patientdatasort()" align="middle" type="button" name="submit">Data and Time</button></th>
                    <th width="22%" style="background:#eeeeee;text-align: center"><button onclick="javascript:patientdesctypesort()"  align="middle" type="button" name="submit">Type</button></th>
                    <th width="22%" style="background:#eeeeee;text-align: center"><button onclick="javascript:patientdescsourcesort()"  align="middle"  type="button" name="submit">Source</button></th>
                    <th width="22%" style="background:#eeeeee;text-align: center"><button onclick="javascript:patientownersort()"  align="middle" type="button" name="submit">User</button></th>
                    <th width="12%" style="background:#eeeeee;text-align: center"></th>
                    
                </tr>
                <?php
                    $i = 0;
                    foreach($this->patient_doc_list as $rows)
                    {
                        if ($i%2 == 0)  
                        {echo"<tr id=\"patient_doc_" . $i . "\" style=\"background:#FF0000\">";
                        echo "<th width='22%' style='text-align: center' > <a href = \"/accendo/public/" . $rows['url'] . " \" target = \" _blank \">" . $rows['data'] . "</a></th>";
                        echo "<th width='22%' style='text-align: center'>" . $rows['description'] . "</th>";
                        echo "<th width='22%' style='text-align: center'>" . $rows['description_source'] . "</th>";
                        echo "<th width='22%' style='text-align: center'>" . $rows['owner'] . "</th>";
                        echo "<th width='12%' style='text-align: center'><input url=\"".$rows['url']."\" id = \"". $rows['url'] . "\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this)\">" . "</input></th>"; 
                        }
                        if ($i%2 == 1)
                        {echo "<tr id=\"patient_doc_" . $i . "\" style=\"background:#00FF00\">";
                        echo "<th width='22%' style='background:#eeeeee;text-align: center' > <a href = \"/accendo/public/" . $rows['url'] . " \" target = \" _blank \">" . $rows['data'] . "</a></th>";
                        echo "<th width='22%' style='background:#eeeeee;text-align: center'>" . $rows['description'] . "</th>";
                        echo "<th width='22%' style='background:#eeeeee;text-align: center'> " .$rows['description_source'] . "</th>";
                        echo "<th width='22%' style='background:#eeeeee;text-align: center'>" . $rows['owner'] . "</th>";
                        echo "<th width='12%' style='background:#eeeeee;text-align: center'><input  url=\"".$rows['url']."\" id =\"". $rows['url'] . "\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this)\">" . "</input></th>"; 
                        }
                          
                        echo "</tr>";
                        $i = $i + 1; 
                    }
                    if ($i%2 == 0)  
                        {echo"<form enctype=\"multipart/form-data\"  method=\"POST\"><tr>";
                        echo "<th width='10%' style='text-align: center' >" . "<input name=\"uploadedfile\" type=\"file\" id=\"uploadedfile\" /></th>";
                        echo "<th id = \"select_desc_1\"  width='22%' style='text-align: center'><select name=\"doc_desc_1\" id=\"doc_desc_1\" style = \"width:60%\" onchange = \"javascript:desc_selfdef1()\">
                            <option value=\"\">Select</option>";
                        
                        foreach ($this->patientdoctypes as $type) {
                            if(($type != "") && ($type != "NULL")){
                            echo"<option value=\"" . $type . "\">" . $type . "</option>";}
                        }
                        echo"<option value=\"selfdefinition\">Misc</option>
                            </select> " . "</th>";
                        echo "<th width = '22%' id = \"selfdefinition_1\" style='display:none' >
                            <input style=\"margin-right:20%\"  type=\"text\" name=\"new_description_type_1\"  id=\"new_description_type_1\" onkeyup=\"javascript:displaycheck('#new_description_type_1')\"  ></input>
                            </th>";
                        echo "<th id = \"select_desc_source_1\"  width='22%' style='text-align: center'><select name=\"doc_desc_source_1_select\" id=\"doc_desc_source_1_select\" style = \"width:60%\" onchange = \"javascript:descsource_selfdef1()\">
                            <option value=\"\">Select</option>";
                        foreach ($this->patientdocsources as $insurance) {
                              if(!strstr($insurance,"Self Pay"))
                            echo"<option value=\"" . $insurance . "\">" . $insurance . "</option>";
                        }    
                        echo"<option value=\"selfdefinition\">Misc</option>
                            </select> " . "</th>";
                        echo "<th width = '22%' id = \"selfdefinition_source_1\" style='display:none'>
                            <input style=\"margin-right:20%\"  type=\"text\" name=\"new_description_source_1\"  id=\"new_description_source_1\"  onkeyup=\"javascript:displaycheck('#new_description_source_1')\" ></input>
                            </th>";
                        echo "<td style=\"display:none\">
                            <input type =\"text\" name=\"doc_desc_source_1\" id=\"doc_desc_source_1\">
                            </td>";
                        
                        echo "<th width='22%' style='text-align: center' id='user_name_1'>" . $this->user_name . "</th>";
                        $new_claim_flag = $this->new_claim_flag;
                        if($new_claim_flag == 0){
                            echo "<th width='12%' style='text-align: center'><input id=\"upload_p\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"UPLOAD\" onclick =\"javascript:upload(this)\"></input><input id=\"uplaod_p_submit\" style=\"display:none;color: #000;background: #ddd;border: 2px solid gray;margin: 0px;margin-left: 20%;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"submit\" name=\"submit\" value=\"UPLOAD_P\">" . "</input></th>"; 
                        }else{
                            echo "<th width='12%' style='text-align: center'><input id=\"upload_p\" disabled=\"disabled\" style=\"color: #BBB;border: 1px solid #BBB;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"UPLOAD\" onclick =\"javascript:upload(this)\"></input><input id=\"uplaod_p_submit\" style=\"display:none;color: #000;background: #ddd;border: 2px solid gray;margin: 0px;margin-left: 20%;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"submit\" name=\"submit\" value=\"UPLOAD_P\">" . "</input></th>"; 
                        
                        }
                        }
                        if ($i%2 == 1)
                        {echo "<form enctype=\"multipart/form-data\"  method=\"POST\"><tr >";
                        echo "<th width='22%' style='background:#eeeeee;text-align: center' >" . "<input name=\"uploadedfile\" type=\"file\" id=\"uploadedfile\" /></th>";
                        echo "<th id = \"select_desc_1\" width='22%' style='background:#eeeeee;text-align: center'><select name=\"doc_desc_1\" style = \"width:60%\" id=\"doc_desc_1\" onchange = \"javascript:desc_selfdef1()\">
                            <option value=\"\">Select</option>";
                        foreach ($this->patientdoctypes as $type) {
                            if(($type != "") && ($type != "NULL")){
                            echo"<option value=\"" . $type . "\">" . $type . "</option>";}
                        }
                        echo"<option value=\"selfdefinition\">Misc</option>
                            </select> " . "</th>";
                        echo "<th width = '22%' id = \"selfdefinition_1\" style='background:#eeeeee;display:none'>
                            <input style=\"margin-right:20%\" type=\"text\" name=\"new_description_type_1\"  id=\"new_description_type_1\" onkeyup=\"javascript:displaycheck('#new_description_type_1')\"></input>
                            </th>";
                        echo "<th id = \"select_desc_source_1\"  width='22%' style='background:#eeeeee;text-align: center'><select name=\"doc_desc_source_1_select\" id=\"doc_desc_source_1_select\" style = \"width:60%\" onchange = \"javascript:descsource_selfdef1()\">
                            <option value=\"\">Select</option>";
                        foreach ($this->patientdocsources as $insurance) {
                            echo"<option value=\"" . $insurance . "\">" . $insurance . "</option>";
                        }    
                        echo"<option value=\"selfdefinition\">Misc</option>
                            </select> " . "</th>";
                        echo "<th width = '22%' id = \"selfdefinition_source_1\" style='background:#eeeeee;display:none'>
                            <input style=\"margin-right:20%\"  type=\"text\" name=\"new_description_source_1\"  id=\"new_description_source_1\" onkeyup=\"javascript:displaycheck('#new_description_source_1')\"></input>
                            </th>";
                        echo "<td style=\"display:none\">
                            <input type =\"text\" name=\"doc_desc_source_1\" id=\"doc_desc_source_1\">
                            </td>";
                        echo "<th width='22%' style='background:#eeeeee;text-align: center' id='user_name_1'>" . $this->user_name . "</th>";
                        $new_claim_flag = $this->new_claim_flag;
                        if($new_claim_flag == 0){
                            echo "<th width='12%' style='background:#eeeeee;text-align: center'><input id=\"upload_p\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"UPLOAD\" onclick =\"javascript:upload(this)\"></input><input id=\"uplaod_p_submit\" style=\"display:none;color: #000;background: #ddd;border: 2px solid gray;margin: 0px;margin-left: 20%;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"submit\" name=\"submit\" value=\"UPLOAD_P\">" . "</input></th>"; 
                        }else{
                            echo "<th width='12%' style='background:#eeeeee;text-align: center'><input id=\"upload_p\" disabled=\"disabled\" style=\"color: #BBB;border: 1px solid #BBB;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"UPLOAD\" onclick =\"javascript:upload(this)\"></input><input id=\"uplaod_p_submit\" style=\"display:none;color: #000;background: #ddd;border: 2px solid gray;margin: 0px;margin-left: 20%;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"submit\" name=\"submit\" value=\"UPLOAD_P\">" . "</input></th>"; 
                            
                        }
                        }
                        echo "</tr></form>";
                ?>
             
        </table>
        <p style="height:50px">  </p>
        
             <table id="table_two">
                <tr>
                    <th align="center" colspan="15" style="font-size: larger;line-height:30px;background:#eeeeee">
                        <p align="center"><b><big>Claim Documents</big></b></p>
                    </th>
                </tr>
                <tr>
                    <th width="22%" style="background:#eeeeee;text-align: center"><button id="datasortbutton1" onclick="javascript:claimdatasort()" align="middle" type="button" name="submit">Data and Time</button></th>
                    <th width="22%" style="background:#eeeeee;text-align: center"><button onclick="javascript:claimdesctypesort()"  align="middle" type="button" name="submit">Type</button></th>
                    <th width="22%" style="background:#eeeeee;text-align: center"><button onclick="javascript:claimdescsourcesort()"  align="middle"  type="button" name="submit">Source</button></th>
                    <th width="22%" style="background:#eeeeee;text-align: center"><button onclick="javascript:claimownersort()"  align="middle" type="button" name="submit">User</button></th>
                    <th width="12%" style="background:#eeeeee;text-align: center"></th>
                    </tr>
                <?php
                    $new_claim_flag = $this->new_claim_flag;
                    if($new_claim_flag == 0){
                    $i = 0;
                    foreach($this->claim_doc_list as $rows)
                    {
                        if ($i%2 == 0)  
                        {echo"<tr id=\"claim_doc_" . $i . "\" bgcolor=\"#FF0000\">";
                        echo "<th width='22%' style='text-align: center' > <a href = \"/accendo/public/" . $rows['url'] . " \" target = \" _blank \">" . $rows['data'] . "</a></th>";
                        echo "<th width='22%' style='text-align: center'>" . $rows['description'] . "</th>";
                        echo "<th width='22%' style='text-align: center'>" . $rows['description_source'] . "</th>";
                        echo "<th width='22%' style='text-align: center'>" . $rows['owner'] . "</th>";
                        echo "<th width='12%' style='text-align: center'><input id = \"". $rows['url'] . "\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this)\">" . "</input></th>"; 
                        }
                        if ($i%2 == 1)
                        {echo "<tr id=\"claim_doc_" . $i . "\" bgcolor=\"#00FF00\">";
                        echo "<th width='22%' style='background:#eeeeee;text-align: center' > <a href = \"/accendo/public/" . $rows['url'] . " \" target = \" _blank \">" . $rows['data'] . "</a></th>";
                        echo "<th width='22%' style='background:#eeeeee;text-align: center'>" . $rows['description'] . "</th>";
                        echo "<th width='22%' style='background:#eeeeee;text-align: center'>" . $rows['description_source'] . "</th>";
                        echo "<th width='22%' style='background:#eeeeee;text-align: center'>" . $rows['owner'] . "</th>";
                        echo "<th width='12%' style='background:#eeeeee;text-align: center'><input id = \"". $rows['url'] . "\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"DELETE\" onclick = \"javascript:onDelete(this)\">" . "</input></th>"; 
                        
                        }
                        echo "</tr>";
                        $i = $i + 1; 
                    }
                    if ($i%2 == 0)  
                        {echo"<form enctype=\"multipart/form-data\"  method=\"POST\"><tr >";
                        echo "<th width='22%' style='text-align: center' >" . "<input name=\"uploadedfile_2\" type=\"file\" id=\"uploadedfile_2\" /></th>";
                        echo "<th id = \"select_desc_2\"  width='22%' style='text-align: center'><select name=\"doc_desc_2\" id=\"doc_desc_2\" style = \"width:60%\" onchange = \"javascript:desc_selfdef2()\">
                            <option value=\"\">Select</option>";
                        foreach ($this->claimdoctypes as $type) {
                            if(($type != "") && ($type != "NULL")){
                            echo"<option value=\"" . $type . "\">" . $type . "</option>";}
                        }
                        echo"<option value=\"selfdefinition\">Misc</option>
                            </select> " . "</th>";
                        echo "<th width = '22%' id = \"selfdefinition_2\" style='display:none'>
                            <input style=\"margin-right:20%\" type=\"text\" name=\"new_description_type_2\"  id=\"new_description_type_2\" onkeyup=\"javascript:displaycheck('#new_description_type_2')\" ></input>
                            </th>";
                        echo "<th id = \"select_desc_source_2\"  width='22%' style='text-align: center'><select name=\"doc_desc_source_2_select\" id=\"doc_desc_source_2_select\" style = \"width:60%\" onchange = \"javascript:descsource_selfdef2()\">
                            <option value=\"\">Select</option>";
                        foreach ($this->claimdocsources as $insurance) {
                              if(!strstr($insurance,"Self Pay"))
                            echo"<option value=\"" . $insurance . "\">" . $insurance . "</option>";
                        }    
                        echo"<option value=\"selfdefinition\">Misc</option>
                            </select> " . "</th>";
                        echo "<th width = '22%' id = \"selfdefinition_source_2\" style='display:none'>
                            <input style=\"margin-right:20%\"  type=\"text\" name=\"new_description_source_2\"  id=\"new_description_source_2\"  onkeyup=\"javascript:displaycheck('#new_description_source_2')\"></input>
                            </th>";
                        echo "<td style=\"display:none\">
                            <input type =\"text\" name=\"doc_desc_source_2\" id=\"doc_desc_source_2\">
                            </td>";
                        echo "<th width='22%' style='text-align: center' id='user_name_2'>" . $this->user_name . "</th>";
                        echo "<th width='12%' style='text-align: center'><input id=\"upload_c\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"UPLOAD\" onclick =\"javascript:upload(this)\"></input><input id=\"uplaod_c_submit\" style=\"display:none;color: #000;background: #ddd;border: 2px solid gray;margin: 0px;margin-left: 20%;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"submit\" name=\"submit\" value=\"UPLOAD_C\">" . "</input></th>"; 
                        }
                        if ($i%2 == 1)
                        {echo "<form enctype=\"multipart/form-data\"  method=\"POST\"><tr >";
                        echo "<th width='22%' style='background:#eeeeee;text-align: center' >" . "<input name=\"uploadedfile_2\" type=\"file\" id=\"uploadedfile_2\" /></th>";
                        echo "<th id = \"select_desc_2\" width='22%' style='background:#eeeeee;text-align: center'><select name=\"doc_desc_2\" style = \"width:60%\" id=\"doc_desc_2\" onchange = \"javascript:desc_selfdef2()\">
                            <option value=\"\">Select</option>";
                        foreach ($this->claimdoctypes as $type) {
                            if(($type != "") && ($type != "NULL")){
                            echo"<option value=\"" . $type . "\">" . $type . "</option>";}
                        }    
                        echo"<option value=\"selfdefinition\">Misc</option>
                            </select> " . "</th>";
                        echo "<th id = \"selfdefinition_2\" style='background:#eeeeee; width:22%;display:none'>
                            <input style=\"margin-right:20%\" type=\"text\" name=\"new_description_type_2\"  id=\"new_description_type_2\" onkeyup=\"javascript:displaycheck('#new_description_type_2')\" ></input>
                            </th>";
                        echo "<th id = \"select_desc_source_2\"  width='22%' style='background:#eeeeee;text-align: center'><select name=\"doc_desc_source_2_select\" id=\"doc_desc_source_2_select\" style = \"width:60%\" onchange = \"javascript:descsource_selfdef2()\">
                            <option value=\"\">Select</option>";
                        foreach ($this->claimdocsources as $insurance) {
                               echo"<option value=\"" . $insurance . "\">" . $insurance . "</option>";
                        }    
                        echo"<option value=\"selfdefinition\">Misc</option>
                            </select> " . "</th>";
                        echo "<th width = '22%' id = \"selfdefinition_source_2\" style='background:#eeeeee;display:none'>
                            <input style=\"margin-right:20%\"  type=\"text\" name=\"new_description_source_2\"  id=\"new_description_source_2\" onkeyup=\"javascript:displaycheck('#new_description_source_2')\" ></input>
                            </th>";
                        echo "<td style=\"display:none\">
                            <input type =\"text\" name=\"doc_desc_source_2\" id=\"doc_desc_source_2\">
                            </td>";
                        echo "<th width='22%' style='background:#eeeeee;text-align: center' id='user_name_2'>" . $this->user_name . "</th>";
                        echo "<th width='12%' style='background:#eeeeee;text-align: center'><input id=\"upload_c\" style=\"color: #000;background: #fff;border: 1px solid black;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"UPLOAD\" onclick =\"javascript:upload(this)\"></input><input id=\"uplaod_c_submit\" style=\"display:none;color: #000;background: #ddd;border: 2px solid gray;margin: 0px;margin-left: 20%;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"submit\" name=\"submit\" value=\"UPLOAD_C\">" . "</input></th>"; 
                        }
                        echo "</form></tr>";}else
                        {
                            echo "<th width='22%' style='text-align: center' >" . "<input name=\"uploadedfile_2\" type=\"file\" id=\"uploadedfile_2\" /></th>";
                            echo "<th width='22%' style='text-align: center' >ServiceComboSheets</th>";
                            echo "<th width='22%' style='text-align: center' >Facility</th>";
                            echo "<th width='22%' style='text-align: center' id='user_name_2'>" . $this->user_name . "</th>";
                            echo "<th width='12%' style='text-align: center'><input id=\"upload_c\" disabled = 'disabled' style=\"color: #BBB;border: 1px solid #BBB;margin: 0px;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"button\" name=\"button\" value=\"UPLOAD\" onclick =\"javascript:upload(this)\"></input><input id=\"uplaod_c_submit\" style=\"display:none;color: #000;background: #ddd;border: 2px solid gray;margin: 0px;margin-left: 20%;padding:0px;height:20px;width:60%;vertical-align:baseline;font: 12px Arial;\" align=\"middle\" type=\"submit\" name=\"submit\" value=\"UPLOAD_C\">" . "</input></th>"; 
                        
                        }
                ?>
            </table>
        <!-- One
            <p style="height:50px">  </p>
            <tr id="document_access">
                <td  align="center">
                    <button style="width: 100px " type="submit" name="submit" id="imigrate" value="imigrate" >imigrate</button>
                </td>


            </tr>
         -->   
             </form>
        </div>
    <script type="text/javascript">
        jQuery(function(){       
        jQuery(".megamenu").megamenu();
        });
    </script>
    </body>
</html>
