<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Accendo</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/layout.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/layout1.css" />
        <link rel="stylesheet" rev="stylesheet" type="text/css" media="screen, projection" href="<?php echo $this->baseUrl ?>/styles/pagenav.css" />
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery.js"></script>
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery-1.3.2.js"></script>
        <script  type="text/javascript" LANGUAGE="JavaScript" SRC="<?php echo $this->baseUrl ?>/scripts/validation.js"></script>
        <script type="text/javascript" language="Javascript">
            var num = 1;
            function addselect()
            {
                var add = document.all("addfile");
                add.innerHTML ="<input type=file size=50 name=user_upload_file[]><br/>"+add.innerHTML;
                num++;
            }
            
            function removeselect()
            {           
                var remove = document.all("addfile");                        
                var len = remove.innerHTML.length;
                if(num == 1)
                    return;
                remove.innerHTML = remove.innerHTML.substring(len/num,len);
                num--;
            }
            
            function CheckForm() 
            {
                if(document.form1.FileName.value=="")
                {
                    alert("Please select at least one ERA 835 file");
                    document.form1.FileName.focus();
                    return false;
                }
                document.form1.myfile.value = ""
            }
            
        </script>       
        
    </head>
    
    
    
    <body>
        <div id="navbar">
            <p>Your Location: <a  title="">Claims Management</a> &gt; ERA 835 Batch</p>
        </div>
          
        <div class="table-div" >
            <form action="" method="post"  enctype="multipart/form-data" name="process_era835"  onSubmit="return CheckForm()">
                <table>
                    <tr>
                        <th align="center" colspan="14" style="background:#eeeeee">
                            <p align="center"><b><big>ERA 835 Processing</big></b></p>
                        </th>
                    </tr>
                    
                    <tr>
                        <th style= "width:20% "><p align="center"> Choose ERA 835 File</p></th>
                        
                        
                        <th>    
                        <div id="addfile" align ="center"><input type="file" name="user_upload_file[]" size=50></input><br></div>
                        </th>
                       
                        
                        
                        <!--
                        <th>
                        <div id="addfile" align ="center">
                        <input type="button" id="btn1" value="Select File"/><input type="text" id="myfile" name="myfile" size="21" readonly/>
                        <input type="file" id="FileName" name="user_upload_file[]" size="30" onchange="myfile.value=this.value" style="width:0;position:absolute;left:119mm;filter:alpha(opacity=10);"/>
                        </div>
                        </th>
                        -->
                       
                        
                        
                         <th style ="width:20%">
                        <p align ="center">
                        <input type="button"style ="min-height:25px; min-width: 80" name="addmore" value="More" onclick="javascript:addselect()"/>
                        <input type="button"style ="min-height:25px; min-width: 80" name="remove" value="Less" onclick="javascript:removeselect()"/>
                        </p>
                        </th>      
                                     
                    </tr> 
                    <tr>
                        <th style ="width:20%"></th>                    
                        <th>
                        <p style="margin-right: 340px"><input type="submit" style =" min-height: 25px; min-width: 80px" name="install" value="ERA 835 Processing" /></p>
                        </th>
                    </tr>
                   
                </table>
            </form>
        </div>
    </body>
</html>