<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Accendo</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/layout.css" />
        <link rel="stylesheet" rev="stylesheet" type="text/css" media="screen, projection" href="<?php echo $this->baseUrl ?>/styles/pagenav.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl ?>/styles/navigation.css" />
         <link rel="stylesheet" href="<?php echo $this->baseUrl ?>/styles/jquery.megamenu.css" type="text/css" media="screen" />
        
        
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jquery.js"></script>
        <script type="text/javascript" language="Javascript" src="<?php echo $this->baseUrl ?>/scripts/jshelper.js"></script>
         <!--Add drop down for mid section-->
        <script src="<?php echo $this->baseUrl ?>/scripts/jquery-1.4.2.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl ?>/scripts/jquery.megamenu.js" type="text/javascript"></script>
        
        <!--Add drop down for mid section-->
        
        <!-- Add for testing insurance UI >
        <script type="text/javascript" src="jquery-1.4.2.min.js"></script>
        <  -->
        <script  type="text/javascript" LANGUAGE="JavaScript" SRC="<?php echo $this->baseUrl ?>/scripts/validation.js"></script>
<style>
table{ border:0;border-collapse:collapse;}
td{ font:normal 12px/17px Arial;padding:2px;width:100px;}
th{ font:bold 12px/17px Arial;text-align:left;padding:4px;border-bottom:1px solid #333;width:100px;}
.parent	{ background:#FFF38F;cursor:pointer;}  /* 偶数行样式*/
.odd{ background:#FFFFEE;}  /* 奇数行样式*/
.selected{ background:#FF6500;color:#fff;}
    
</style>
        <script type="text/javascript">
            $(document).ready(function()
            {            
                $('tr.parent').click(function(){   // 获取所谓的父行
			$(this) 
				//.toggleClass("selected")   // 添加/删除高亮
				.siblings('.child_'+this.id).toggle("Slow");  // 隐藏/显示所谓的子行
                }).click();
               /*Add for testing insurance UI*/
             
               /*Add for testing insurance UI*/
                
//                add by Pandazhao 
//                if the role is guset, the user can only read;\



               var role = "<?php echo $this->role; ?>";
                if(role=='guest'){
                    var inputList = document.getElementsByTagName("input");
                    var selectList = document.getElementsByTagName("select");
                     var textList = document.getElementsByTagName("textarea");
                    for(var i=0;i<textList.length;i++){
                        textList[i].disabled = "true";
                    }
                    for(var i = 0;i<inputList.length;i++){
                       if(inputList[i].type=='submit'&&(inputList[i].value=='Finish Claim'||inputList[i].value=='Save Claim')){
                            inputList[i].disabled="true";
                            inputList[i].style.background="url(<?php echo $this->baseUrl; ?>/images/tab_bg_2.png)";
                        }else{
                            if(inputList[i].type!='submit')
                                inputList[i].disabled="true";
                        }
                    }
                    for(var i = 0;i<selectList.length;i++){
                        selectList[i].disabled="true";
                    }
                }
            });
        </script>
        
        <script type="text/javascript">
              now_table_number = 1;
              function  addinsurancetable()
              {
                  if(now_table_number > 3)
                      return;
                  now_table_number = now_table_number + 1;
                  add_table_id = "insurance_table_"+now_table_number;
                  var add_table = document.getElementById(add_table_id);
                  add_table.style.display=null;                
              }
        </script>

        
    </head>

    <body>
        <a href="<?php echo $this->baseUrl ?>" target="_top" id="relogin" style="display: none" >wwwwww</a>
        <div class="table-div" >
            <form  method="post" action="" onsubmit="javascript:return check();">
                <table width="100%">
                    <tr class="navigation">
                        <td colspan="8" style="background:#ffffff">
                            <a href="#"><span> <input type="submit" name="submit" id="Previous"value="Previous"/></span></a>
                            <a href="#"><span> <input type="submit"name="submit"id="Patient"value="Patient" /></span></a>
                            <a href="#"><span> <input type="submit" name="submit"id="Insurance"value="Insurance" style="background:url(<?php echo $this->baseUrl ?>/images/tab_bg_3.png)"/></span></a>
                            <a href="#"><span> <input type="submit"name="submit"id="Service"value="Service" /></span></a>
                            <a href="#"><span> <input type="submit" name="submit"id="Claim"value="Claim" style="width:60px"/></span></a>
                            <a href="#"><span> <input type="submit"name="submit"id="Next"value="Next" /></span></a>

                           <!-- Fix the mid UI By Yu Lang-->           
                            <span style="margin:0 0 0 30px"> 
                             <div id="current">                                      
                             <ul class="megamenu">
                                 <li><?php echo $this->cur_service_info['patient_name'] ?>&nbsp;</li>
                                 <li>
                                     <a href="javascript:void(0)" style="color:#FF0000;">=</a>
                                     <div style="width: 535px;">
                                         <!-- <h3>Dropdown Example</h3> -->
                                         <table border="1" cellpadding="0" cellspacing="0" id="tabular-content">
                                             <tr>
                                                <!-- <th style="width: 15px">Number</th> -->
                                                 <th style="text-align:center">DOS</th>
                                                 <th style="width: 26%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Rendering Provider</th>
                                                 <th style="width: 25%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Referring Provider</th>
                                                 <th style="width: 32%;text-overflow:clip ; overflow:hidden; white-space:nowrap;text-align:center">Claim Status</th>
                                                  <!--<th style="width: 100px">DOS</th> -->
                                             </tr>
                                             
                                             
                                             <?php
                                             $tmp_baseUrl = $this->baseUrl;
                                             $tmp_claim_id = $this->cur_service_info['claim_id'];                                             
                                             foreach($this->tmpList as $row)
                                             {
                                                
                                                if( $row['claim_id'] == $tmp_claim_id )
                                                {
                                                    $rendering_provdier_name = $row['ren_last_name']. ', '. $row['ren_first_name'];
                                                    $referring_provider_name = $row['ref_last_name'].', '.$row['ref_first_name'];
                                                    
                                                    echo "<tr><td style= 'background-color: rgb(150,230,230);'>";                                                  
                                                     echo "<a href=\"". $this->baseUrl."/biller/claims/dropdown?patient_id=".$row['patient_id']. " & encounter_id=".$row['encounter_id'] ." & type=insurance \">";
                                                    echo $row['dos'];
                                                    echo "</a></td>";
                                                    echo "<td style= 'text-overflow:clip ; overflow:hidden; white-space:nowrap;background-color: rgb(150,230,230);'>";
                                                    echo substr($rendering_provdier_name,0,15)."</td>" ;
                                                    echo "<td style= 'text-overflow:clip ; overflow:hidden; white-space:nowrap;background-color: rgb(150,230,230);'>";
                                                    echo substr($referring_provider_name,0,15)."</td>";
                                                    echo "<td style= 'text-overflow:clip ; overflow:hidden; white-space:nowrap;background-color: rgb(150,230,230);'>";
                                                    echo substr($row['claim_status'],0,30);
                                                    echo "</td><tr>";
                                                }
                                                else
                                                {
                                                    $rendering_provdier_name = $row['ren_last_name']. ', '. $row['ren_first_name'];
                                                    $referring_provider_name = $row['ref_last_name'].', '.$row['ref_first_name'];
                                                    echo "<tr><td>";
                                                    echo "<a href=\"". $this->baseUrl."/biller/claims/dropdown?patient_id=".$row['patient_id']. " & encounter_id=".$row['encounter_id'] ." & type=insurance \">";
                                                    echo $row['dos'];
                                                    echo "</a></td>";
                                                    echo "<td style= 'text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo substr($rendering_provdier_name,0,15)."</td>" ;
                                                    echo "<td style= 'text-overflow:clip ; overflow:hidden; white-space:nowrap;'>";
                                                    echo substr($referring_provider_name,0,15)."</td>";
                                                   echo "<td style= 'text-overflow:clip ; overflow:hidden;  white-space:nowrap;'>";
                                                    echo substr($row['claim_status'],0,30);
                                                    echo "</td><tr>";
                                                }
                                             }
                                             ?>
                                         </table>
                                     </div>
                                 </li>
                                  <li>
                                     |&nbsp;<?php echo $this->cur_service_info['DOB'] ?>&nbsp;|&nbsp;<?php echo $this->cur_service_info['MRN'] ?>&nbsp;|&nbsp;
                                    <?php echo $this->cur_service_info['DOS'] ?>&nbsp;|&nbsp$<?php echo $this->cur_service_info['total_charge'] ?>
                                 </li>
                                    <?php echo $this->cur_service_info['secondary_cpt_code_1'] ?>&nbsp;
                                    |&nbsp;<?php echo $this->cur_service_info['provider_short_name'] ?>&nbsp;
                                    |&nbsp;<?php echo $this->cur_service_info['renderingprovider_name'] ?>&nbsp;
                                    |&nbsp;<?php echo $this->cur_service_info['insurance_name'] ?>&nbsp;
                                    |&nbsp;<?php echo $this->cur_service_info['insured_ID_number'] ?>
                                 
                             </ul>                                                                                                            
                           </div>
                           </span>
                            <!-- Fix the mid UI By Yu Lang-->

                            <a href="#"><span style="float:right;margin:2px 0px 0 0"> <input type="submit"name="submit"value="Finish Claim" style="width:80px"/></span></a>
                            <a href="#"><span style="float:right;margin:2px 0px 0 0"> <input type="submit"name="submit"value="Save Claim" style="width:80px"/></span></a>
                        </td>
                    </tr>
                   
                    <!-- add for new insurance UI -->
                      <!-- 收缩展开效果 -->
                      <tr><th colspan="8" style="background:#eeeeee"><p align="center"><b>Insured Information</b></p></th></tr>
                      
                      <table>
                        <!--
                        <thead>
			<tr><th>姓名</th><th>性别</th><th>暂住地</th></tr>
                        </thead>
                        -->
                        <tbody style="" id="insurance_table_1">
                               <tr class="parent" id="row_01"><td colspan="3" >Primary GEICO 32148412344123 Chen, Lin  +</td></tr>
                               <tr class="child_row_01">
                                    <th align="left" width="15%">Last Name</th><td ><input type="text" name="last_name" id="last_name" /></td>
                                    <th align="left" width="15%">First Name</th><td ><input type="text" name="first_name" id="first_name" /></td>
                                    <th align="left" width="28%">Date of Birth</th><td><input type="text" name="DOB" id="DOB" onkeyup="javascript:date('#DOB')" /></td>
                                    <th align="left" width="25%">Sex</th>
                                    <td ><select name="sex" id="sex" style= "width:100% ">
                                        <option value="">Select</option>
                                        <option value="m">Male</option>
                                        <option value="f">Female</option>
                                    </select>
                                    </td> 
                                </tr>
                            
                                <tr class="child_row_01">                                 
                                        <th  align="left">Street Address</th><td><input type="text" name="street_address" id="street_address" /></td>
                                        <th align="left">Zip Code</th><td><input type="text" name="zip"  id="zip"  onkeyup="javascript:zipcode('#zip')" onblur="javascript:zip2citystate()"/></td>
                                        <th align="left">City</th><td><input type="text" name="city"  id="city" /></td>
                                        <th align="left">State</th><td><input type="text" name="state"  id="state" /></td>
                                </tr>
                            
                                 <tr class="child_row_01">                                 
                                        <th align="left">SSN</th><td><input type="text" name="SSN"  id="SSN"  onkeyup="javascript:ssn('#SSN')"/></td>
                                        <th  align="left">Phone Number</th><td><input type="text" name="phone_number" id="phone_number" onkeyup="javascript:phone('#phone_number')"/></td>
                                        <th  align="left">Secondary Number</th><td><input type="text" name="second_phone_number"  id="second_phone_number" onkeyup="javascript:phone('#second_phone_number')"/></td>
                                </tr>
                            
                                <tr class="child_row_01">                                 
                                        <th align="left">Insurance ID</th><td><input type="text" name="ID_number" id="ID_number" /></td>
                                        <th align="left">Group Policy Number</th><td><input type="text" name="policy_group_or_FECA_number" id="policy_group_or_FECA_number"  /></td>
                                        <th align="left">Employer Name</th><td><input type="text" name="employer_or_school_name" id="employer_or_school_name" /></td>
                                </tr>
                            
                                 <tr class="child_row_01">                                 
                                        <th align="left">Company Name</th>
                                        <td>
                                            <select class="select" name="insurance_id" id="insurance_id"  onchange="javascript:auto_complete()" style= "width:100% ">
                                            <option value="">Select Company</option>
                                            <?php
                                                foreach ($this->insuranceList as $row) {
                                                echo "<option value='" . $row['id'] . "'>" . $row['insurance_name'] . "</option>";
                                                }
                                            ?>
                                            </select>
                                            <input type="text" name="insurance_name"  id="insurance_name" style= "display:none "/>
                                        </td>
                                        <th align="left">Phone Number</th><td ><input type="text" name="insurance_phone_number" id="insurance_phone_number" readonly= "true"/></td>
                                        <th align="left">Fax Number</th><td><input type="text" name="fax_number" id="fax_number" readonly= "true "/></td>
                                        <th align="left">Crosswalk Overwrite</th><td><input type="text" name="anesthesia_crosswalk_overwrite" id="anesthesia_crosswalk_overwrite" readonly= "true "/></td>
                                </tr>
                            
                                <tr class="child_row_01">
                                     <th  align="left">Street Address</th><td><input type="text" name="insurance_street_address" id="insurance_street_address" readonly= "true "/></td>
                                     <th align="left">City</th><td><input type="text" name="insurance_city" id="insurance_city"  readonly= "true "/></td>
                                     <th align="left">State</th><td><input type="text" name="insurance_state" id="insurance_state"  readonly= "true "/></td>
                                     <th align="left">Zip Code</th><td><input type="text" name="insurance_zip" id="insurance_zip"  readonly= "true "/></td>             
                                </tr>
                                
                                </tbody>
                        
                                <tbody style="display:none" id="insurance_table_2">
                                <tr class="parent" id="row_02"><td colspan="3" >Secondary UHC W172345 Chen, Lin  +</td></tr>
                               <tr class="child_row_02">
                                    <th align="left" width="15%">Last Name</th><td ><input type="text" name="last_name" id="last_name" /></td>
                                    <th align="left" width="15%">First Name</th><td ><input type="text" name="first_name" id="first_name" /></td>
                                    <th align="left" width="28%">Date of Birth</th><td><input type="text" name="DOB" id="DOB" onkeyup="javascript:date('#DOB')" /></td>
                                    <th align="left" width="25%">Sex</th>
                                    <td ><select name="sex" id="sex" style= "width:100% ">
                                        <option value="">Select</option>
                                        <option value="m">Male</option>
                                        <option value="f">Female</option>
                                    </select>
                                    </td> 
                                </tr>
                            
                                <tr class="child_row_02">                                 
                                        <th  align="left">Street Address</th><td><input type="text" name="street_address" id="street_address" /></td>
                                        <th align="left">Zip Code</th><td><input type="text" name="zip"  id="zip"  onkeyup="javascript:zipcode('#zip')" onblur="javascript:zip2citystate()"/></td>
                                        <th align="left">City</th><td><input type="text" name="city"  id="city" /></td>
                                        <th align="left">State</th><td><input type="text" name="state"  id="state" /></td>
                                </tr>
                            
                                 <tr class="child_row_02">                                 
                                        <th align="left">SSN</th><td><input type="text" name="SSN"  id="SSN"  onkeyup="javascript:ssn('#SSN')"/></td>
                                        <th  align="left">Phone Number</th><td><input type="text" name="phone_number" id="phone_number" onkeyup="javascript:phone('#phone_number')"/></td>
                                        <th  align="left">Secondary Number</th><td><input type="text" name="second_phone_number"  id="second_phone_number" onkeyup="javascript:phone('#second_phone_number')"/></td>
                                </tr>
                            
                                <tr class="child_row_02">                                 
                                        <th align="left">Insurance ID</th><td><input type="text" name="ID_number" id="ID_number" /></td>
                                        <th align="left">Group Policy Number</th><td><input type="text" name="policy_group_or_FECA_number" id="policy_group_or_FECA_number"  /></td>
                                        <th align="left">Employer Name</th><td><input type="text" name="employer_or_school_name" id="employer_or_school_name" /></td>
                                </tr>
                            
                                 <tr class="child_row_02">                                 
                                        <th align="left">Company Name</th>
                                        <td>
                                            <select class="select" name="insurance_id" id="insurance_id"  onchange="javascript:auto_complete()" style= "width:100% ">
                                            <option value="">Select Company</option>
                                            <?php
                                                foreach ($this->insuranceList as $row) {
                                                echo "<option value='" . $row['id'] . "'>" . $row['insurance_name'] . "</option>";
                                                }
                                            ?>
                                            </select>
                                            <input type="text" name="insurance_name"  id="insurance_name" style= "display:none "/>
                                        </td>
                                        <th align="left">Phone Number</th><td ><input type="text" name="insurance_phone_number" id="insurance_phone_number" readonly= "true"/></td>
                                        <th align="left">Fax Number</th><td><input type="text" name="fax_number" id="fax_number" readonly= "true "/></td>
                                        <th align="left">Crosswalk Overwrite</th><td><input type="text" name="anesthesia_crosswalk_overwrite" id="anesthesia_crosswalk_overwrite" readonly= "true "/></td>
                                </tr>
                            
                                <tr class="child_row_02">
                                     <th  align="left">Street Address</th><td><input type="text" name="insurance_street_address" id="insurance_street_address" readonly= "true "/></td>
                                     <th align="left">City</th><td><input type="text" name="insurance_city" id="insurance_city"  readonly= "true "/></td>
                                     <th align="left">State</th><td><input type="text" name="insurance_state" id="insurance_state"  readonly= "true "/></td>
                                     <th align="left">Zip Code</th><td><input type="text" name="insurance_zip" id="insurance_zip"  readonly= "true "/></td>             
                                </tr>
                                
                                
                               </tbody>
                        
                              <tbody style="display:none" id="insurance_table_3">
                               <tr class="parent" id="row_03"><td colspan="3" >Tertiary GEICO 32148412344123 Chen, Lin  +</td></tr>
                               <tr class="child_row_03">
                                    <th align="left" width="15%">Last Name</th><td ><input type="text" name="last_name" id="last_name" /></td>
                                    <th align="left" width="15%">First Name</th><td ><input type="text" name="first_name" id="first_name" /></td>
                                    <th align="left" width="28%">Date of Birth</th><td><input type="text" name="DOB" id="DOB" onkeyup="javascript:date('#DOB')" /></td>
                                    <th align="left" width="25%">Sex</th>
                                    <td ><select name="sex" id="sex" style= "width:100% ">
                                        <option value="">Select</option>
                                        <option value="m">Male</option>
                                        <option value="f">Female</option>
                                    </select>
                                    </td> 
                                </tr>
                            
                                <tr class="child_row_03">                                 
                                        <th  align="left">Street Address</th><td><input type="text" name="street_address" id="street_address" /></td>
                                        <th align="left">Zip Code</th><td><input type="text" name="zip"  id="zip"  onkeyup="javascript:zipcode('#zip')" onblur="javascript:zip2citystate()"/></td>
                                        <th align="left">City</th><td><input type="text" name="city"  id="city" /></td>
                                        <th align="left">State</th><td><input type="text" name="state"  id="state" /></td>
                                </tr>
                            
                                 <tr class="child_row_03">                                 
                                        <th align="left">SSN</th><td><input type="text" name="SSN"  id="SSN"  onkeyup="javascript:ssn('#SSN')"/></td>
                                        <th  align="left">Phone Number</th><td><input type="text" name="phone_number" id="phone_number" onkeyup="javascript:phone('#phone_number')"/></td>
                                        <th  align="left">Secondary Number</th><td><input type="text" name="second_phone_number"  id="second_phone_number" onkeyup="javascript:phone('#second_phone_number')"/></td>
                                </tr>
                            
                                <tr class="child_row_03">                                 
                                        <th align="left">Insurance ID</th><td><input type="text" name="ID_number" id="ID_number" /></td>
                                        <th align="left">Group Policy Number</th><td><input type="text" name="policy_group_or_FECA_number" id="policy_group_or_FECA_number"  /></td>
                                        <th align="left">Employer Name</th><td><input type="text" name="employer_or_school_name" id="employer_or_school_name" /></td>
                                </tr>
                            
                                 <tr class="child_row_03">                                 
                                        <th align="left">Company Name</th>
                                        <td>
                                            <select class="select" name="insurance_id" id="insurance_id"  onchange="javascript:auto_complete()" style= "width:100% ">
                                            <option value="">Select Company</option>
                                            <?php
                                                foreach ($this->insuranceList as $row) {
                                                echo "<option value='" . $row['id'] . "'>" . $row['insurance_name'] . "</option>";
                                                }
                                            ?>
                                            </select>
                                            <input type="text" name="insurance_name"  id="insurance_name" style= "display:none "/>
                                        </td>
                                        <th align="left">Phone Number</th><td ><input type="text" name="insurance_phone_number" id="insurance_phone_number" readonly= "true"/></td>
                                        <th align="left">Fax Number</th><td><input type="text" name="fax_number" id="fax_number" readonly= "true "/></td>
                                        <th align="left">Crosswalk Overwrite</th><td><input type="text" name="anesthesia_crosswalk_overwrite" id="anesthesia_crosswalk_overwrite" readonly= "true "/></td>
                                </tr>
                            
                                <tr class="child_row_03">
                                     <th  align="left">Street Address</th><td><input type="text" name="insurance_street_address" id="insurance_street_address" readonly= "true "/></td>
                                     <th align="left">City</th><td><input type="text" name="insurance_city" id="insurance_city"  readonly= "true "/></td>
                                     <th align="left">State</th><td><input type="text" name="insurance_state" id="insurance_state"  readonly= "true "/></td>
                                     <th align="left">Zip Code</th><td><input type="text" name="insurance_zip" id="insurance_zip"  readonly= "true "/></td>             
                                </tr>
                                
                            </tbody>
                        
                           <tbody style="display:none" id="insurance_table_4">
                                <tr class="parent" id="row_04"><td colspan="3" >Other UHC W172345 Chen, Lin  +</td></tr>
                               <tr class="child_row_04">
                                    <th align="left" width="15%">Last Name</th><td ><input type="text" name="last_name" id="last_name" /></td>
                                    <th align="left" width="15%">First Name</th><td ><input type="text" name="first_name" id="first_name" /></td>
                                    <th align="left" width="28%">Date of Birth</th><td><input type="text" name="DOB" id="DOB" onkeyup="javascript:date('#DOB')" /></td>
                                    <th align="left" width="25%">Sex</th>
                                    <td ><select name="sex" id="sex" style= "width:100% ">
                                        <option value="">Select</option>
                                        <option value="m">Male</option>
                                        <option value="f">Female</option>
                                    </select>
                                    </td> 
                                </tr>
                            
                                <tr class="child_row_04">                                 
                                        <th  align="left">Street Address</th><td><input type="text" name="street_address" id="street_address" /></td>
                                        <th align="left">Zip Code</th><td><input type="text" name="zip"  id="zip"  onkeyup="javascript:zipcode('#zip')" onblur="javascript:zip2citystate()"/></td>
                                        <th align="left">City</th><td><input type="text" name="city"  id="city" /></td>
                                        <th align="left">State</th><td><input type="text" name="state"  id="state" /></td>
                                </tr>
                            
                                 <tr class="child_row_04">                                 
                                        <th align="left">SSN</th><td><input type="text" name="SSN"  id="SSN"  onkeyup="javascript:ssn('#SSN')"/></td>
                                        <th  align="left">Phone Number</th><td><input type="text" name="phone_number" id="phone_number" onkeyup="javascript:phone('#phone_number')"/></td>
                                        <th  align="left">Secondary Number</th><td><input type="text" name="second_phone_number"  id="second_phone_number" onkeyup="javascript:phone('#second_phone_number')"/></td>
                                </tr>
                            
                                <tr class="child_row_04">                                 
                                        <th align="left">Insurance ID</th><td><input type="text" name="ID_number" id="ID_number" /></td>
                                        <th align="left">Group Policy Number</th><td><input type="text" name="policy_group_or_FECA_number" id="policy_group_or_FECA_number"  /></td>
                                        <th align="left">Employer Name</th><td><input type="text" name="employer_or_school_name" id="employer_or_school_name" /></td>
                                </tr>
                            
                                 <tr class="child_row_04">                                 
                                        <th align="left">Company Name</th>
                                        <td>
                                            <select class="select" name="insurance_id" id="insurance_id"  onchange="javascript:auto_complete()" style= "width:100% ">
                                            <option value="">Select Company</option>
                                            <?php
                                                foreach ($this->insuranceList as $row) {
                                                echo "<option value='" . $row['id'] . "'>" . $row['insurance_name'] . "</option>";
                                                }
                                            ?>
                                            </select>
                                            <input type="text" name="insurance_name"  id="insurance_name" style= "display:none "/>
                                        </td>
                                        <th align="left">Phone Number</th><td ><input type="text" name="insurance_phone_number" id="insurance_phone_number" readonly= "true"/></td>
                                        <th align="left">Fax Number</th><td><input type="text" name="fax_number" id="fax_number" readonly= "true "/></td>
                                        <th align="left">Crosswalk Overwrite</th><td><input type="text" name="anesthesia_crosswalk_overwrite" id="anesthesia_crosswalk_overwrite" readonly= "true "/></td>
                                </tr>
                            
                                <tr class="child_row_04">
                                     <th  align="left">Street Address</th><td><input type="text" name="insurance_street_address" id="insurance_street_address" readonly= "true "/></td>
                                     <th align="left">City</th><td><input type="text" name="insurance_city" id="insurance_city"  readonly= "true "/></td>
                                     <th align="left">State</th><td><input type="text" name="insurance_state" id="insurance_state"  readonly= "true "/></td>
                                     <th align="left">Zip Code</th><td><input type="text" name="insurance_zip" id="insurance_zip"  readonly= "true "/></td>             
                                </tr>
                           </tbody>                 
                   
                                
                                
                   <tr>
                        <th colspan="7" >&nbsp</th>
                        <td><input type="button"  value="MORE" id="" onclick="javascript:addinsurancetable()"/></td>
                   </tr>
                                
                   <tr><th colspan="8" style="background:#eeeeee"><p align="center"><b>Expired Information</b></p></th></tr>
                   
                    <tbody style="" id="expired_insurance_table_5">
                     <tr class="parent" id="row_05" style=""><td colspan="3" >Expired GEICO 32148412344123 Chen, Lin +</td></tr>
                               <tr class="child_row_05">
                                    <th align="left" width="15%">Last Name</th><td ><input type="text" name="last_name" id="last_name" /></td>
                                    <th align="left" width="15%">First Name</th><td ><input type="text" name="first_name" id="first_name" /></td>
                                    <th align="left" width="28%">Date of Birth</th><td><input type="text" name="DOB" id="DOB" onkeyup="javascript:date('#DOB')" /></td>
                                    <th align="left" width="25%">Sex</th>
                                    <td ><select name="sex" id="sex" style= "width:100% ">
                                        <option value="">Select</option>
                                        <option value="m">Male</option>
                                        <option value="f">Female</option>
                                    </select>
                                    </td> 
                                </tr>
                               
                                <tr class="child_row_05">                                 
                                        <th  align="left">Street Address</th><td><input type="text" name="street_address" id="street_address" /></td>
                                        <th align="left">Zip Code</th><td><input type="text" name="zip"  id="zip"  onkeyup="javascript:zipcode('#zip')" onblur="javascript:zip2citystate()"/></td>
                                        <th align="left">City</th><td><input type="text" name="city"  id="city" /></td>
                                        <th align="left">State</th><td><input type="text" name="state"  id="state" /></td>
                                </tr>
                            
                                 <tr class="child_row_05">                                 
                                        <th align="left">SSN</th><td><input type="text" name="SSN"  id="SSN"  onkeyup="javascript:ssn('#SSN')"/></td>
                                        <th  align="left">Phone Number</th><td><input type="text" name="phone_number" id="phone_number" onkeyup="javascript:phone('#phone_number')"/></td>
                                        <th  align="left">Secondary Number</th><td><input type="text" name="second_phone_number"  id="second_phone_number" onkeyup="javascript:phone('#second_phone_number')"/></td>
                                </tr>
                            
                                <tr class="child_row_05">                                 
                                        <th align="left">Insurance ID</th><td><input type="text" name="ID_number" id="ID_number" /></td>
                                        <th align="left">Group Policy Number</th><td><input type="text" name="policy_group_or_FECA_number" id="policy_group_or_FECA_number"  /></td>
                                        <th align="left">Employer Name</th><td><input type="text" name="employer_or_school_name" id="employer_or_school_name" /></td>
                                </tr>
                            
                                 <tr class="child_row_05">                                 
                                        <th align="left">Company Name</th>
                                        <td>
                                            <select class="select" name="insurance_id" id="insurance_id"  onchange="javascript:auto_complete()" style= "width:100% ">
                                            <option value="">Select Company</option>
                                            <?php
                                                foreach ($this->insuranceList as $row) {
                                                echo "<option value='" . $row['id'] . "'>" . $row['insurance_name'] . "</option>";
                                                }
                                            ?>
                                            </select>
                                            <input type="text" name="insurance_name"  id="insurance_name" style= "display:none "/>
                                        </td>
                                        <th align="left">Phone Number</th><td ><input type="text" name="insurance_phone_number" id="insurance_phone_number" readonly= "true"/></td>
                                        <th align="left">Fax Number</th><td><input type="text" name="fax_number" id="fax_number" readonly= "true "/></td>
                                        <th align="left">Crosswalk Overwrite</th><td><input type="text" name="anesthesia_crosswalk_overwrite" id="anesthesia_crosswalk_overwrite" readonly= "true "/></td>
                                </tr>
                            
                                <tr class="child_row_05">
                                     <th  align="left">Street Address</th><td><input type="text" name="insurance_street_address" id="insurance_street_address" readonly= "true "/></td>
                                     <th align="left">City</th><td><input type="text" name="insurance_city" id="insurance_city"  readonly= "true "/></td>
                                     <th align="left">State</th><td><input type="text" name="insurance_state" id="insurance_state"  readonly= "true "/></td>
                                     <th align="left">Zip Code</th><td><input type="text" name="insurance_zip" id="insurance_zip"  readonly= "true "/></td>             
                                </tr>
                                </tbody>
                   
                                <tbody style="" id="expired_insurance_table_6">
                                <tr class="parent" id="row_06"><td colspan="3" >Expired UHC W172345 Chen, Lin  +</td></tr>
                               <tr class="child_row_06">
                                    <th align="left" width="15%">Last Name</th><td ><input type="text" name="last_name" id="last_name" /></td>
                                    <th align="left" width="15%">First Name</th><td ><input type="text" name="first_name" id="first_name" /></td>
                                    <th align="left" width="28%">Date of Birth</th><td><input type="text" name="DOB" id="DOB" onkeyup="javascript:date('#DOB')" /></td>
                                    <th align="left" width="25%">Sex</th>
                                    <td ><select name="sex" id="sex" style= "width:100% ">
                                        <option value="">Select</option>
                                        <option value="m">Male</option>
                                        <option value="f">Female</option>
                                    </select>
                                    </td> 
                                </tr>
                            
                                <tr class="child_row_06">                                 
                                        <th  align="left">Street Address</th><td><input type="text" name="street_address" id="street_address" /></td>
                                        <th align="left">Zip Code</th><td><input type="text" name="zip"  id="zip"  onkeyup="javascript:zipcode('#zip')" onblur="javascript:zip2citystate()"/></td>
                                        <th align="left">City</th><td><input type="text" name="city"  id="city" /></td>
                                        <th align="left">State</th><td><input type="text" name="state"  id="state" /></td>
                                </tr>
                            
                                 <tr class="child_row_06">                                 
                                        <th align="left">SSN</th><td><input type="text" name="SSN"  id="SSN"  onkeyup="javascript:ssn('#SSN')"/></td>
                                        <th  align="left">Phone Number</th><td><input type="text" name="phone_number" id="phone_number" onkeyup="javascript:phone('#phone_number')"/></td>
                                        <th  align="left">Secondary Number</th><td><input type="text" name="second_phone_number"  id="second_phone_number" onkeyup="javascript:phone('#second_phone_number')"/></td>
                                </tr>
                            
                                <tr class="child_row_06">                                 
                                        <th align="left">Insurance ID</th><td><input type="text" name="ID_number" id="ID_number" /></td>
                                        <th align="left">Group Policy Number</th><td><input type="text" name="policy_group_or_FECA_number" id="policy_group_or_FECA_number"  /></td>
                                        <th align="left">Employer Name</th><td><input type="text" name="employer_or_school_name" id="employer_or_school_name" /></td>
                                </tr>
                            
                                 <tr class="child_row_06">                                 
                                        <th align="left">Company Name</th>
                                        <td>
                                            <select class="select" name="insurance_id" id="insurance_id"  onchange="javascript:auto_complete()" style= "width:100% ">
                                            <option value="">Select Company</option>
                                            <?php
                                                foreach ($this->insuranceList as $row) {
                                                echo "<option value='" . $row['id'] . "'>" . $row['insurance_name'] . "</option>";
                                                }
                                            ?>
                                            </select>
                                            <input type="text" name="insurance_name"  id="insurance_name" style= "display:none "/>
                                        </td>
                                        <th align="left">Phone Number</th><td ><input type="text" name="insurance_phone_number" id="insurance_phone_number" readonly= "true"/></td>
                                        <th align="left">Fax Number</th><td><input type="text" name="fax_number" id="fax_number" readonly= "true "/></td>
                                        <th align="left">Crosswalk Overwrite</th><td><input type="text" name="anesthesia_crosswalk_overwrite" id="anesthesia_crosswalk_overwrite" readonly= "true "/></td>
                                </tr>
                            
                                <tr class="child_row_06">
                                     <th  align="left">Street Address</th><td><input type="text" name="insurance_street_address" id="insurance_street_address" readonly= "true "/></td>
                                     <th align="left">City</th><td><input type="text" name="insurance_city" id="insurance_city"  readonly= "true "/></td>
                                     <th align="left">State</th><td><input type="text" name="insurance_state" id="insurance_state"  readonly= "true "/></td>
                                     <th align="left">Zip Code</th><td><input type="text" name="insurance_zip" id="insurance_zip"  readonly= "true "/></td>             
                                </tr>                               
                               </tbody> 
                               
                      </table>
                   
                    <!-- add for new insurance UI -->
                    
                    
                    
                    
                    
                    
                    <tr id="document_access">
                        <td align="right"><input  type="button" name="upload" id="upload"value="Document Input" onclick= "javascript:window.open( '<?php echo $this->baseUrl ?>/biller/claims/upload/pageno/2 ','upload',
                            'height=220,width=500,status=no,toolbar=no,menubar=no,location=no,scrollbars=no') "/></td></tr>
                </table>
            </form>
        </div>
        
     <script type="text/javascript">
      jQuery(function(){       
            jQuery(".megamenu").megamenu();
      });
      </script>
        
        
    </body>
</html>
